### ISSUE TITLE
Ruby gems are only recognised if they are executed as sudo

### ISSUE THREAD

**Issue by dialex** [docker/for-mac#1967]
### Expected behavior

After installing Ruby and gem X through the Dockerfile, after I bash into the image, I'm able to run X.

### Actual behavior

Ruby tells me X is not installed. However if I prepend sudo, the command is executed.

### Information

This is one of those "works on my machine" type of issues. It doesn't work on my and another colleague's machine. However works on three other machines. We all use Macs. It also works on an Ubuntu machine.

### Steps to reproduce the behavior

  1. Get a Mac with Docker for Mac.
  2. Build the image.
  3. Step into the image's bash.

Command under test

```sh
$ inspec
$ sudo inspec
```

Error

```
root@2da1c6c83575:/share# inspec
/usr/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'inspec' (>= 0.a) among 5 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/dnunes/.rvm/gems/ruby-2.3.0:/Users/dnunes/.rvm/gems/ruby-2.3.0@global', execute `gem env` for more information
	from /usr/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /usr/local/bin/inspec:22:in `<main>'
```

Dockerfile

```Dockerfile
FROM microsoft/vsts-agent
RUN apt-get update
RUN apt-get --yes install ruby-full
RUN apt-get --yes install gettext
RUN apt-get --yes install inotify-tools
RUN gem install rake -N
RUN gem install inspec -N

# This fixes "bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)"
RUN apt-get --yes install locales
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8
ENV LANG en_US.UTF-8
```

Listing of gems has a similar behaviour

```
root@2da1c6c83575:/share# gem list

*** LOCAL GEMS ***
bigdecimal (1.2.8)
io-console (0.4.5)
json (1.8.3)
psych (2.0.17)
rdoc (4.2.1)

root@2da1c6c83575:/share# sudo gem list

*** LOCAL GEMS ***
addressable (2.5.1)
...10 more...
inspec (1.33.1)
...10 more...
net-scp (1.2.1)
...10 more...
rake (12.0.0, 10.5.0)
rdoc (4.2.1)
rspec (3.6.0)
...another 20...
```

**Comment by dialex** [comment]
I have RVM installed on my local machine, maybe that's causing some conflict?

Output from `gem env`

```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-linux-gnu]
  - INSTALLATION DIRECTORY: /Users/dnunes/.rvm/gems/ruby-2.3.0
  - USER INSTALLATION DIRECTORY: /Users/dnunes/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/bin/ruby2.3
  - EXECUTABLE DIRECTORY: /Users/dnunes/.rvm/gems/ruby-2.3.0/bin
  - SPEC CACHE DIRECTORY: /Users/dnunes/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /Users/dnunes/.rvm/gems/ruby-2.3.0
     - /Users/dnunes/.rvm/gems/ruby-2.3.0@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/dnunes/.rbenv/shims
     - /Users/dnunes/.rbenv/shims
     - /Users/dnunes/.rvm/gems/ruby-2.3.0/bin
     - /Users/dnunes/.rvm/gems/ruby-2.3.0@global/bin
     - /Users/dnunes/.rvm/rubies/ruby-2.3.0/bin
     - /Users/dnunes/.nvm/versions/node/v6.3.0/bin
     - /usr/local/sbin
     - ~/bin
     - /usr/local/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /opt/X11/bin
     - /usr/local/share/dotnet
     - /Library/Frameworks/Mono.framework/Versions/Current/Commands
     - /Users/dnunes/.rvm/bin
     - /Users/dnunes/.rvm/bin
```

output from `sudo gem env`

```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-linux-gnu]
  - INSTALLATION DIRECTORY: /var/lib/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /Users/dnunes/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/bin/ruby2.3
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /Users/dnunes/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /var/lib/gems/2.3.0
     - /usr/lib/x86_64-linux-gnu/rubygems-integration/2.3.0
     - /usr/share/rubygems-integration/2.3.0
     - /usr/share/rubygems-integration/all
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /snap/bin
```

**Comment by dialex** [comment]
Nevermind, that happened because I was importing all my host env vars into the docker image. Since I have RVM installed on my local machine, it was confusing the ruby/gem installed inside the image.
