### ISSUE TITLE
UnicodeDecodeError on docker-compose up

### ISSUE THREAD

**Issue by mtoothman** [docker/for-mac#2162]
### Expected behavior
compose starts desired container according to compose file
### Actual behavior
Error is thrown
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior
E5A44811-5C26-4167-A454-99B6EBE398C3  
```
$ docker-compose up
Building db_migration
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 68, in main
  File "compose/cli/main.py", line 121, in perform_command
  File "compose/cli/main.py", line 938, in up
  File "compose/project.py", line 430, in up
  File "compose/service.py", line 317, in ensure_image_exists
  File "compose/service.py", line 918, in build
  File "site-packages/docker/api/build.py", line 238, in build
  File "site-packages/docker/api/build.py", line 285, in _set_auth_headers
  File "site-packages/docker/auth.py", line 97, in resolve_authconfig
  File "site-packages/docker/auth.py", line 125, in _resolve_authconfig_credstore
  File "site-packages/dockerpycreds/store.py", line 25, in get
  File "site-packages/dockerpycreds/store.py", line 57, in _execute
  File "subprocess.py", line 711, in __init__
  File "subprocess.py", line 1343, in _execute_child
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
Failed to execute script docker-compose
```

Able to `docker pull`, `run`, `exec`, and `docker-compose ps` without error, but any `docker-compose up` command throws the above.

  1. ...
  2. ...

**Comment by mtoothman** [comment]
Moving the `.docker/config.json` and recreating it solved this problem.
