### ISSUE TITLE
docker compose up Is not working after latest updated

### ISSUE THREAD

**Issue by ravindrakhokharia** [docker/for-mac#2755]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue

Diagnose id 
9572E436-4BBC-4A13-857A-3CA9CB7A283B/20180331-182757

Diagnose details 

Docker for Mac: version: 18.03.0-ce-mac60 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E199)
logs: /tmp/9572E436-4BBC-4A13-857A-3CA9CB7A283B/20180331-182757.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk

### Expected behavior
it should work
### Actual behavior
throwing error 
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1018, in up
  File "compose/cli/main.py", line 1508, in warn_for_swarm_mode
  File "site-packages/docker/api/daemon.py", line 88, in info
  File "site-packages/docker/utils/decorators.py", line 46, in inner
  File "site-packages/docker/api/client.py", line 194, in _get
  File "site-packages/requests/sessions.py", line 521, in get
  File "site-packages/requests/sessions.py", line 499, in request
  File "site-packages/requests/sessions.py", line 672, in merge_environment_settings
  File "site-packages/requests/utils.py", line 692, in get_environ_proxies
  File "site-packages/requests/utils.py", line 676, in should_bypass_proxies
  File "urllib/request.py", line 2612, in proxy_bypass
  File "urllib/request.py", line 2589, in proxy_bypass_macosx_sysconf
  File "urllib/request.py", line 2575, in _proxy_bypass_macosx_sysconf
ValueError: negative shift count
[9881] Failed to execute script docker-compose
### Information

docker-compose is not working but docker is working fine
if I start manually each docker image and link them it will work fine.
its not working even for hello-world

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. create a file docker-compose.yml
version: '2'
services:
  powwownowcom:
    image: npm
    volumes:
     - ./:/app
    command: ["npm", "--version"]
  2. run docker-compose up 
that will throw following error
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1018, in up
  File "compose/cli/main.py", line 1508, in warn_for_swarm_mode
  File "site-packages/docker/api/daemon.py", line 88, in info
  File "site-packages/docker/utils/decorators.py", line 46, in inner
  File "site-packages/docker/api/client.py", line 194, in _get
  File "site-packages/requests/sessions.py", line 521, in get
  File "site-packages/requests/sessions.py", line 499, in request
  File "site-packages/requests/sessions.py", line 672, in merge_environment_settings
  File "site-packages/requests/utils.py", line 692, in get_environ_proxies
  File "site-packages/requests/utils.py", line 676, in should_bypass_proxies
  File "urllib/request.py", line 2612, in proxy_bypass
  File "urllib/request.py", line 2589, in proxy_bypass_macosx_sysconf
  File "urllib/request.py", line 2575, in _proxy_bypass_macosx_sysconf
ValueError: negative shift count
[10244] Failed to execute script docker-compose

**Comment by kiss69** [comment]
同样的问题， 希望得到解答

**Comment by rainabba** [comment]
For anyone else reading this, the message above translates to English as "Hello I have the same problem, I hope to get your answer, thank you!"
