### ISSUE TITLE
Clean install generates kube-apiserver cert with invalid DNS SAN

### ISSUE THREAD

**Issue by emmanuel** [docker/for-mac#2798]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue

### Expected behavior

Certs generated by Docker for `kube-apiserver` should have valid subject alternate names (SANs).

### Actual behavior

Cert generated for `kube-apiserver` has an invalid SAN, according to macOS Quicklook.
![screen shot 2018-04-10 at 3 15 12 pm](https://user-images.githubusercontent.com/7657/38586677-8e7281f6-3cd3-11e8-972e-3bae81a4c1c0.png)

### Information

```
Docker for Mac: version: 18.03.0-ce-mac58 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E199)
logs: /tmp/C5932665-F52D-4F51-87E2-2BA3A167BB5F/20180410-152144.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk
```

### Steps to reproduce the behavior

  1. Install `version/18.04.0-ce-rc2-mac61`
  2. Inspect certificate presented by `kube-apiserver`
  
To clarify, `kubectl` works fine with the certificate, but I'm getting a failure from a Python Kubernetes client when trying to connect to the apiserver:

```
      File "/opt/conda/lib/python3.5/site-packages/kubernetes/client/apis/core_v1_api.py", line 13060, in list_namespaced_pod
        (data) = self.list_namespaced_pod_with_http_info(namespace, **kwargs)
      File "/opt/conda/lib/python3.5/site-packages/kubernetes/client/apis/core_v1_api.py", line 13162, in list_namespaced_pod_with_http_info
        collection_formats=collection_formats)
      File "/opt/conda/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 335, in call_api
        _preload_content, _request_timeout)
      File "/opt/conda/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 148, in __call_api
        _request_timeout=_request_timeout)
      File "/opt/conda/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 371, in request
        headers=headers)
      File "/opt/conda/lib/python3.5/site-packages/kubernetes/client/rest.py", line 250, in GET
        query_params=query_params)
      File "/opt/conda/lib/python3.5/site-packages/kubernetes/client/rest.py", line 223, in request
        headers=headers)
      File "/opt/conda/lib/python3.5/site-packages/urllib3/request.py", line 66, in request
        **urlopen_kw)
      File "/opt/conda/lib/python3.5/site-packages/urllib3/request.py", line 87, in request_encode_url
        return self.urlopen(method, url, **extra_kw)
      File "/opt/conda/lib/python3.5/site-packages/urllib3/poolmanager.py", line 321, in urlopen
        response = conn.urlopen(method, u.request_uri, **kw)
      File "/opt/conda/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
        chunked=chunked)
      File "/opt/conda/lib/python3.5/site-packages/urllib3/connectionpool.py", line 346, in _make_request
        self._validate_conn(conn)
      File "/opt/conda/lib/python3.5/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
        conn.connect()
      File "/opt/conda/lib/python3.5/site-packages/urllib3/connection.py", line 337, in connect
        cert = self.sock.getpeercert()
      File "/opt/conda/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 348, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "/opt/conda/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 222, in get_subj_alt_name
        for name in ext.get_values_for_type(x509.DNSName)
      File "/opt/conda/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 222, in <listcomp>
        for name in ext.get_values_for_type(x509.DNSName)
      File "/opt/conda/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 175, in _dnsname_to_stdlib
        name = idna_encode(name)
      File "/opt/conda/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 173, in idna_encode
        return idna.encode(name)
      File "/opt/conda/lib/python3.5/site-packages/idna/core.py", line 350, in encode
        raise IDNAError('Empty domain')
    idna.core.IDNAError: Empty domain
```

FWIW, the broken cert is here:
```
-----BEGIN CERTIFICATE-----
MIIDZDCCAkygAwIBAgIIMxJs+Eeq0UUwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
AxMKa3ViZXJuZXRlczAeFw0xODA0MTAyMjExNThaFw0xOTA0MTAyMjExNThaMBkx
FzAVBgNVBAMTDmt1YmUtYXBpc2VydmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEAu+Wv/IVY3qJqZgVDYkBDEfOxp6rPhWejKJWzgc0ju3jJL0zDAInH
DxSd9RZ5ufdaQoglj4PaTjYfWhHspULICh7u2so/cfuTXBQz4qmgDtS0kv1cwLpm
x8JNGegGVmxhDygWCgzaR6s+dHYXNyKJXNWNBujiiZev7VmqG4KRGC4MOKfFfHka
6de9hibFkHUIXWgKHF6JhFszP/2KiMxwpUjRuEl9rJlAoKozxIK3SebdrgrtIVZs
vGwpGd+/AUBOHNDH+Bysuz2UwqOaf9wsYB4jlK/bwUzuI7WPyqMuvcRIMTtFh6i9
lZqWENUnBXmHmQEmRFdLBE4OqADS/kL/sQIDAQABo4GzMIGwMA4GA1UdDwEB/wQE
AwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATCBiAYDVR0RBIGAMH6CEmRvY2tlci1m
b3ItZGVza3RvcIIKa3ViZXJuZXRlc4ISa3ViZXJuZXRlcy5kZWZhdWx0ghZrdWJl
cm5ldGVzLmRlZmF1bHQuc3ZjgiRrdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0
ZXIubG9jYWyHBApgAAGHBMCoQQMwDQYJKoZIhvcNAQELBQADggEBAKIcuNdtaFU4
AmPXWTMLeyugDCXz0BAzHL8Z23FG2lydE3KDUXJeV7rW2FSAivApZee/Ai3gJqK1
3CooqLji3MOUqzjEoDQ0PQTvniquGfu7yxNOqvZ8gqgekm11q16A7P09eKyZxrQU
kPl3dMG6cqIGNil+GqVvKckNp4h64zPTHaWtfHhKA1vRyIZMptFLkuy1wI7A24zW
uEEbk4rWxf2m2NkutwXpmW9DCfRvSbtiVbtqPJU59fy0VTt8meWFXtyYpBTVcSAR
gvDKVkDq0zoldEx+jy8KU3pmAW6yvTK6V5nyAROSMCJ1P/iwP76CuXLRK92lzx6i
piZfmtquxys=
-----END CERTIFICATE-----
```

And this is the cert that works, from `version: 18.03.0-ce-mac58 `:
```
-----BEGIN CERTIFICATE-----
MIIDZDCCAkygAwIBAgIIMxJs+Eeq0UUwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
AxMKa3ViZXJuZXRlczAeFw0xODA0MTAyMjExNThaFw0xOTA0MTAyMjExNThaMBkx
FzAVBgNVBAMTDmt1YmUtYXBpc2VydmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEAu+Wv/IVY3qJqZgVDYkBDEfOxp6rPhWejKJWzgc0ju3jJL0zDAInH
DxSd9RZ5ufdaQoglj4PaTjYfWhHspULICh7u2so/cfuTXBQz4qmgDtS0kv1cwLpm
x8JNGegGVmxhDygWCgzaR6s+dHYXNyKJXNWNBujiiZev7VmqG4KRGC4MOKfFfHka
6de9hibFkHUIXWgKHF6JhFszP/2KiMxwpUjRuEl9rJlAoKozxIK3SebdrgrtIVZs
vGwpGd+/AUBOHNDH+Bysuz2UwqOaf9wsYB4jlK/bwUzuI7WPyqMuvcRIMTtFh6i9
lZqWENUnBXmHmQEmRFdLBE4OqADS/kL/sQIDAQABo4GzMIGwMA4GA1UdDwEB/wQE
AwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATCBiAYDVR0RBIGAMH6CEmRvY2tlci1m
b3ItZGVza3RvcIIKa3ViZXJuZXRlc4ISa3ViZXJuZXRlcy5kZWZhdWx0ghZrdWJl
cm5ldGVzLmRlZmF1bHQuc3ZjgiRrdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0
ZXIubG9jYWyHBApgAAGHBMCoQQMwDQYJKoZIhvcNAQELBQADggEBAKIcuNdtaFU4
AmPXWTMLeyugDCXz0BAzHL8Z23FG2lydE3KDUXJeV7rW2FSAivApZee/Ai3gJqK1
3CooqLji3MOUqzjEoDQ0PQTvniquGfu7yxNOqvZ8gqgekm11q16A7P09eKyZxrQU
kPl3dMG6cqIGNil+GqVvKckNp4h64zPTHaWtfHhKA1vRyIZMptFLkuy1wI7A24zW
uEEbk4rWxf2m2NkutwXpmW9DCfRvSbtiVbtqPJU59fy0VTt8meWFXtyYpBTVcSAR
gvDKVkDq0zoldEx+jy8KU3pmAW6yvTK6V5nyAROSMCJ1P/iwP76CuXLRK92lzx6i
piZfmtquxys=
-----END CERTIFICATE-----
```

It appears that the SAN that's broken is the one that used to hold `docker-for-desktop`.

**Comment by emmanuel** [comment]
I screwed up my diagnostics above. The reported diagnostics is from the older working version of Docker for Mac (`version/18.03.0-ce-mac58`), whereas the reported problem occurs on the newer reported release, `18.04.0-ce-rc2-mac61`. Given that Docker itself appears to work fine, and even `kubectl` works with the `kube-apiserver` launched on `18.04.0-ce-rc2-mac61`. In other words, I am confident that diagnostics would not describe any problems with the newer release, because the problem described is in a specific interaction with an alpha subsystem (viz., the `kube-apiserver` cert).

**Comment by glortho** [comment]
We appear to be having a related issue. One machine running 18.04.0-ce-rc2-mac61 is fine, but one running 18.04.0-ce-mac62 gets the `IDNAError('Empty domain')` error when trying to hit the kubernetes api via dask-kubernetes https://github.com/dask/dask-kubernetes.

The problematic one was a clean install, whereas the one that is working has been upgraded a couple of times on the edge channel. Not sure if that's relevant.

**Comment by cmcarthur** [comment]
👍 to what @glortho said.

I'm seeing the same error `IDNAError('Empty domain')` when trying to access kube-apiserver via the python client in my application, after loading the incluster config:

```
>>> import kubernetes
>>> kubernetes.config.load_incluster_config()
>>> core_v1_api = kubernetes.client.CoreV1Api()
>>> v1.list_node()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/client/apis/core_v1_api.py", line 13233, in list_node
    (data) = self.list_node_with_http_info(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/client/apis/core_v1_api.py", line 13330, in list_node_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/client/rest.py", line 231, in GET                                                                   [170/419]
    query_params=query_params)
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/client/rest.py", line 205, in request
    headers=headers)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/request.py", line 66, in request
    **urlopen_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/poolmanager.py", line 321, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 337, in connect
    cert = self.sock.getpeercert()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/contrib/pyopenssl.py", line 348, in getpeercert
    'subjectAltName': get_subj_alt_name(x509)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/contrib/pyopenssl.py", line 222, in get_subj_alt_name
    for name in ext.get_values_for_type(x509.DNSName)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/contrib/pyopenssl.py", line 222, in <listcomp>
    for name in ext.get_values_for_type(x509.DNSName)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/contrib/pyopenssl.py", line 175, in _dnsname_to_stdlib
    name = idna_encode(name)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/contrib/pyopenssl.py", line 173, in idna_encode
    return idna.encode(name)
  File "/usr/local/lib/python3.5/dist-packages/idna/core.py", line 350, in encode
    raise IDNAError('Empty domain')
idna.core.IDNAError: Empty domain
```
