### ISSUE TITLE
Remove reference to old CA Cert

### ISSUE THREAD

**Issue by bsnodgrass** [docker/for-mac#2817]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue

### Expected behavior

Docker starts and Diagnostics report everything ok and Docker commands work as expected (they are not)

### Actual behavior

Output from any command results in the following message
$ docker info
could not read CA certificate "/Users/bobsnodgrass/.docker/machine/machines/amazeeio-cachalot/ca.pem": open /Users/bobsnodgrass/.docker/machine/machines/amazeeio-cachalot/ca.pem: no such file or directory

### Information

https://github.com/docker/for-mac/issues/2775 [Related Issue - determined not the problem]

On my last attempt I used all the options in succession on Preferences/Reset and installed with lando dependencies.
I've also removed the old references to the machines/amazeeio-cachalot.

### How can I find and remove whatever is referencing this deleted .pem file? 

872A2CF8-3C58-4993-8D48-7900D2F21649/20180417-073124

```
Docker for Mac: version...
Docker for Mac: version: 18.03.0-ce-mac60 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.4 (build: 17E199)
logs: /tmp/872A2CF8-3C58-4993-8D48-7900D2F21649/20180417-073124.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk

```

**Comment by bsnodgrass** [comment]
### I have attempted to Reset Docker and reinstall using the Lando package.
The Docker running it reports 
$ docker-machine ls
NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS
Bobs-MBP-2:~ bobsnodgrass$ docker info
could not read CA certificate "/Users/bobsnodgrass/.docker/machine/machines/amazeeio-cachalot/ca.pem": open /Users/bobsnodgrass/.docker/machine/machines/amazeeio-cachalot/ca.pem: no such file or directory

### I also tried to reinstall Amazeeio-cachalot using brew instructions at https://github.com/MidCamp/midcamp
brew tap amazeeio/cachalot
brew install docker docker-machine docker-compose cachalot
cachalot create --provider virtualbox  <--- this command reports the same as cachalot (a similar docker error?)

Bobs-MBP-2:~ bobsnodgrass$ cachalot
/usr/local/Cellar/cachalot/0.12.3/cli/amazeeio_cachalot.rb:89:in `version': Could not check docker --version, is it installed? (RuntimeError)
	from /usr/local/Cellar/cachalot/0.12.3/cli/amazeeio_cachalot.rb:69:in `block in version_check'
	from /usr/local/Cellar/cachalot/0.12.3/cli/amazeeio_cachalot.rb:68:in `each'
	from /usr/local/Cellar/cachalot/0.12.3/cli/amazeeio_cachalot.rb:68:in `version_check'
	from /usr/local/Cellar/cachalot/0.12.3/cli/amazeeio_cachalot.rb:37:in `run_checks'
	from /usr/local/bin/_amazeeio-cachalot_command:11:in `<main>'

**Comment by bsnodgrass** [comment]
It turns out I still had the environment variable in .bash_profile, once that was removed and a new terminal window was started... everything is working.
