### ISSUE TITLE
Error about user name or passphrase not being correct

### ISSUE THREAD

**Issue by daveisfera** [docker/for-mac#2973]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C18223FD-44DC-4ACD-B197-B660FC33917F

### Expected behavior
Continues to work like it did yesterday

### Actual behavior
I'm getting this error and I don't understand how to fix it:
```
> docker-compose -f postgres.yml pull
Pulling postgres           ... 

ERROR: for postgres  Credentials store error: StoreError('Credentials store docker-credential-osxkeychain exited with "The user name or passphrase you entered is not correct.".',)
Traceback (most recent call last):
  File "site-packages/dockerpycreds/store.py", line 71, in _execute
  File "subprocess.py", line 336, in check_output
  File "subprocess.py", line 418, in run
subprocess.CalledProcessError: Command '['/usr/local/bin/docker-credential-osxkeychain', 'get']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/docker/auth.py", line 126, in _resolve_authconfig_credstore
  File "site-packages/dockerpycreds/store.py", line 33, in get
  File "site-packages/dockerpycreds/store.py", line 84, in _execute
dockerpycreds.errors.StoreError: Credentials store docker-credential-osxkeychain exited with "The user name or passphrase you entered is not correct.".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 729, in pull
  File "compose/project.py", line 556, in pull
  File "compose/parallel.py", line 105, in parallel_execute
  File "compose/parallel.py", line 203, in producer
  File "compose/project.py", line 549, in pull_service
  File "compose/service.py", line 1163, in pull
  File "site-packages/docker/api/image.py", line 380, in pull
  File "site-packages/docker/auth.py", line 47, in get_config_header
  File "site-packages/docker/auth.py", line 94, in resolve_authconfig
  File "site-packages/docker/auth.py", line 143, in _resolve_authconfig_credstore
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-osxkeychain exited with "The user name or passphrase you entered is not correct.".',)
[1225] Failed to execute script docker-compose
```

I tried logging in and still got an error:
```
> docker login
error getting credentials - err: exit status 1, out: `The user name or passphrase you entered is not correct.`
```

### Information
  - macOS Version: 10.13.3

### Diagnostic logs
```
Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.3 (build: 17D102)
logs: /tmp/C18223FD-44DC-4ACD-B197-B660FC33917F/20180605-102233.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk
```

### Steps to reproduce the behavior
Run any docker command

**Comment by danjellesma** [comment]
Having the same issue. 

**Diagnostics ID**: 03508FB6-9C24-43BE-8A81-EA46E0F23677

Docker for Mac: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.12.6 (build: 16G1314)

[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  kubernetes

Issue: Cannot login to private registries, although am logged into Dockerhub successfully. 

**Error seen:** 
`Error saving credentials: error storing credentials - err: exit status 1, out: `The user name or passphrase you entered is not correct.``

**Docker:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true
```
