### ISSUE TITLE
COPYed files not appearing in image if run with docker-compose, but do appear if image run with docker

### ISSUE THREAD

**Issue by jamiegau** [docker/for-mac#3073]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
docker-compose (Mac 1.21.1, build 5a3f1a3) used to create production images and push to private registry.  d-c up works fine.
production system, ubuntu 18.04 d-compose version (1.21.2, build a133471), docker version (18.03.1-ce, build 9ee9f40)
Expected behaviour is for images to run as expected as does on the Mac dev machine.

### Actual behavior
When docker-compose up on Linux/prod system, the main application container does not have the "Dockerfile" COPY files.  If I bring up the same container using docker command, the files are then present and the container works as expected.  It is only if compose brings up the container that the files (The python application) do not appear and the container errors.

-- Dockerfile from dev machine:
```
FROM alpine:3.7

RUN mkdir -p /data/backend
WORKDIR /data/backend
COPY requirements.txt /data/backend/

RUN echo "http://dl-4.alpinelinux.org/alpine/v3.7/main" >> /etc/apk/repositories && \
    echo "http://dl-4.alpinelinux.org/alpine/v3.7/community" >> /etc/apk/repositories

RUN apk update
RUN apk upgrade
RUN apk add --update --no-cache python3 python3-dev postgresql-client postgresql-dev build-base gettext
RUN apk add --update --no-cache g++ gcc libxslt-dev libffi-dev build-base py2-pip python2-dev bash
RUN apk add --update --no-cache chromium chromium-chromedriver
RUN pip3 install --upgrade pip
RUN pip3 install cffi
RUN pip3 install -r requirements.txt

RUN apk del -r python3-dev postgresql

COPY ./manage.py /data/backend/
COPY ./cine_data /data/backend/cine_data
COPY ./CineDataApp /data/backend/CineDataApp
RUN mkdir -p cine_data/static/admin
```

** Linux machine, running backend container with docker-compose **

```
# docker-compose ps
Name   Command   State   Ports
------------------------------
root@ctg:/opt/cine_data.config# docker-compose up
Creating network "cine_dataconfig_redis_network" with the default driver
Creating network "cine_dataconfig_nginx_network" with the default driver
Creating network "cine_dataconfig_postgres_network" with the default driver
Creating cine_dataconfig_redis_1 ... done
Creating cine_dataconfig_backend_1 ... done
Creating cine_dataconfig_nginx_1   ... done
Attaching to cine_dataconfig_redis_1, cine_dataconfig_backend_1, cine_dataconfig_nginx_1
backend_1  | [2018-07-11 00:05:25 +0000] [1] [INFO] Starting gunicorn 19.3.0
redis_1    | 1:C 11 Jul 00:05:22.770 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1    | 1:C 11 Jul 00:05:22.770 # Redis version=4.0.10, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1    | 1:C 11 Jul 00:05:22.770 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1    | 1:M 11 Jul 00:05:22.772 * Running mode=standalone, port=6379.
redis_1    | 1:M 11 Jul 00:05:22.772 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1    | 1:M 11 Jul 00:05:22.772 # Server initialized
redis_1    | 1:M 11 Jul 00:05:22.772 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1    | 1:M 11 Jul 00:05:22.772 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1    | 1:M 11 Jul 00:05:22.772 * Ready to accept connections
backend_1  | [2018-07-11 00:05:25 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
backend_1  | [2018-07-11 00:05:25 +0000] [1] [INFO] Using worker: sync
backend_1  | [2018-07-11 00:05:25 +0000] [7] [INFO] Booting worker with pid: 7
backend_1  | [2018-07-11 00:05:25 +0000] [7] [ERROR] Exception in worker process:
backend_1  | Traceback (most recent call last):
backend_1  |   File "/usr/lib/python3.6/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
backend_1  |     worker.init_process()
backend_1  |   File "/usr/lib/python3.6/site-packages/gunicorn/workers/base.py", line 118, in init_process
backend_1  |     self.wsgi = self.app.wsgi()
backend_1  |   File "/usr/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
backend_1  |     self.callable = self.load()
backend_1  |   File "/usr/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
backend_1  |     return self.load_wsgiapp()
backend_1  |   File "/usr/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
backend_1  |     return util.import_app(self.app_uri)
backend_1  |   File "/usr/lib/python3.6/site-packages/gunicorn/util.py", line 355, in import_app
backend_1  |     __import__(module)
backend_1  | ModuleNotFoundError: No module named 'cine_data'
backend_1  | Traceback (most recent call last):
backend_1  |   File "/usr/lib/python3.6/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
backend_1  |     worker.init_process()
backend_1  |   File "/usr/lib/python3.6/site-packages/gunicorn/workers/base.py", line 118, in init_process
backend_1  |     self.wsgi = self.app.wsgi()
backend_1  |   File "/usr/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
backend_1  |     self.callable = self.load()
backend_1  |   File "/usr/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
backend_1  |     return self.load_wsgiapp()
backend_1  |   File "/usr/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
backend_1  |     return util.import_app(self.app_uri)
backend_1  |   File "/usr/lib/python3.6/site-packages/gunicorn/util.py", line 355, in import_app
backend_1  |     __import__(module)
backend_1  | ModuleNotFoundError: No module named 'cine_data'
backend_1  | [2018-07-11 00:05:25 +0000] [7] [INFO] Worker exiting (pid: 7)
backend_1  | Traceback (most recent call last):
backend_1  |   File "/usr/bin/gunicorn", line 11, in <module>
backend_1  |     sys.exit(run())
backend_1  |   File "/usr/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
backend_1  |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
backend_1  |   File "/usr/lib/python3.6/site-packages/gunicorn/app/base.py", line 189, in run
backend_1  |     super(Application, self).run()
backend_1  |   File "/usr/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
backend_1  |     Arbiter(self).run()
backend_1  |   File "/usr/lib/python3.6/site-packages/gunicorn/arbiter.py", line 174, in run
backend_1  |     self.manage_workers()
backend_1  |   File "/usr/lib/python3.6/site-packages/gunicorn/arbiter.py", line 477, in manage_workers
backend_1  |     self.spawn_workers()
backend_1  |   File "/usr/lib/python3.6/site-packages/gunicorn/arbiter.py", line 541, in spawn_workers
backend_1  |     time.sleep(0.1 * random.random())
backend_1  |   File "/usr/lib/python3.6/site-packages/gunicorn/arbiter.py", line 214, in handle_chld
backend_1  |     self.reap_workers()
backend_1  |   File "/usr/lib/python3.6/site-packages/gunicorn/arbiter.py", line 459, in reap_workers
backend_1  |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
backend_1  | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
cine_dataconfig_backend_1 exited with code 1

```

*** attache to image via docker-compose ***

```
# docker-compose run backend bash
Starting cine_dataconfig_redis_1 ... done
bash-4.4# pwd
/data/backend
bash-4.4# ls
bash-4.4# 
```
no files present.

Image used..
```
# docker-compose images
        Container                      Repository                Tag       Image Id      Size  
-----------------------------------------------------------------------------------------------
cine_dataconfig_backend_1   docker-reg:5000/cine_data_backend   2        a111137f4786   682 MB
```
a111137f4786 being thr image.
Now attach to image using docker  (Shut down all containers first of course.)

```
# docker run  -i -t a111137f4786 bash
bash-4.4# pwd
/data/backend
bash-4.4# ls
CineDataApp       cine_data         manage.py         requirements.txt
bash-4.4# 
```
Files NOW exist.

Please explain!!!!!

**Comment by ayshrimali** [comment]
Resolved COPY not working.

I was facing issue on Cent OS 7 with Docker version - 1.7.0, build 0baf609

Solution: (May be a dirty one)
Don't use relative path as dest path. 
Like,

`COPY xxx-yyy.tar.gz .`

Instead, use

`COPY xxx-yyy.tar.gz /absolute/path/to/copy`
