### ISSUE TITLE
docker-compose build HTTPS timeout

### ISSUE THREAD

**Issue by RobertFischer** [docker/for-mac#3606]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: EB3B66A2-84C8-4D32-BD12-29EDD989667A/20190402203426

### Expected behavior

`docker-compose build` works

### Actual behavior

```
$docker-compose --verbose build
compose.config.config.find: Using configuration files: ./docker-compose.yml
docker.utils.config.find_config_file: Trying paths: ['/Users/robert/.docker/config.json', '/Users/robert/.dockercfg']
docker.utils.config.find_config_file: Found file at path: /Users/robert/.docker/config.json
docker.auth.load_config: Found 'auths' section
docker.auth.parse_auth: Auth data for https://index.docker.io/v1/ is absent. Client might be using a credentials store instead.
urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): 192.168.99.105:2376
Traceback (most recent call last):
  File "site-packages/urllib3/connection.py", line 159, in _new_conn
  File "site-packages/urllib3/util/connection.py", line 80, in create_connection
  File "site-packages/urllib3/util/connection.py", line 70, in create_connection
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/urllib3/connectionpool.py", line 600, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 343, in _make_request
  File "site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
  File "site-packages/urllib3/connection.py", line 301, in connect
  File "site-packages/urllib3/connection.py", line 164, in _new_conn
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x10fb364e0>, 'Connection to 192.168.99.105 timed out. (connect timeout=60)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/requests/adapters.py", line 449, in send
  File "site-packages/urllib3/connectionpool.py", line 638, in urlopen
  File "site-packages/urllib3/util/retry.py", line 398, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.99.105', port=2376): Max retries exceeded with url: /v1.25/version (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x10fb364e0>, 'Connection to 192.168.99.105 timed out. (connect timeout=60)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 124, in perform_command
  File "compose/cli/command.py", line 42, in project_from_options
  File "compose/cli/command.py", line 123, in get_project
  File "compose/cli/command.py", line 97, in get_client
  File "site-packages/docker/api/daemon.py", line 181, in version
  File "site-packages/docker/utils/decorators.py", line 46, in inner
  File "site-packages/docker/api/client.py", line 215, in _get
  File "site-packages/requests/sessions.py", line 537, in get
  File "site-packages/requests/sessions.py", line 524, in request
  File "site-packages/requests/sessions.py", line 637, in send
  File "site-packages/requests/adapters.py", line 504, in send
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='192.168.99.105', port=2376): Max retries exceeded with url: /v1.25/version (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x10fb364e0>, 'Connection to 192.168.99.105 timed out. (connect timeout=60)'))
[57059] Failed to execute script docker-compose
```

### Information

  - macOS Version: 10.14.4

### Diagnostic logs
Just said "Diagnostics were successful" and then I was pitched over here

### Steps to reproduce the behavior

Here's the `docker-compose.yml` file that I am trying to bring up:

[docker-compose.yml.txt](https://github.com/docker/for-mac/files/3035856/docker-compose.yml.txt)

**Comment by RobertFischer** [comment]
My `~/.docker/config.json` is simply:

```json
{
  "stackOrchestrator" : "swarm",
  "auths" : {
    "https://index.docker.io/v1/" : {

    }
  },
  "credSstore" : "osxkeychain"
}
```
