### ISSUE TITLE
Building via docker-compose fails

### ISSUE THREAD

**Issue by tobiashinz** [docker/for-mac#3805]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Build image

### Actual behavior
Build process fails with message `no hostname in URL`

```bash
Traceback (most recent call last):
  File "site-packages/dockerpycreds/store.py", line 80, in _execute
  File "subprocess.py", line 356, in check_output
  File "subprocess.py", line 438, in run
subprocess.CalledProcessError: Command '['/usr/local/bin/docker-credential-desktop', 'get']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/docker/auth.py", line 264, in _resolve_authconfig_credstore
  File "site-packages/dockerpycreds/store.py", line 35, in get
  File "site-packages/dockerpycreds/store.py", line 93, in _execute
dockerpycreds.errors.StoreError: Credentials store docker-credential-desktop exited with "error getting credentials - err: exit status 1, out: `no hostname in URL`".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1085, in up
  File "compose/cli/main.py", line 1081, in up
  File "compose/project.py", line 527, in up
  File "compose/service.py", line 360, in ensure_image_exists
  File "compose/service.py", line 1084, in build
  File "site-packages/docker/api/build.py", line 260, in build
  File "site-packages/docker/api/build.py", line 307, in _set_auth_headers
  File "site-packages/docker/auth.py", line 304, in get_all_credentials
  File "site-packages/docker/auth.py", line 281, in _resolve_authconfig_credstore
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exit status 1, out: `no hostname in URL`".',)
[2002] Failed to execute script docker-compose
```
### Information
  - macOS Version: 10.14.6 (18G84)
  - Docker for Mac Version: 19.03.1, build 74b1e89

### Steps to reproduce the behavior
Dockerfile:
```bash
FROM jboss/keycloak
```

`docker-compose.yml`:

```
version: '2'
services:
    keycloak:
        build:
            context: .
        container_name: "keycloak"
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - DB_USER=keycloak
            - DB_DATABASE=keycloak
            - DB_PASSWORD=password mariadb
        ports:
            - 8090:8080
        links:
            - mariadb
        depends_on:
            - mariadb
        volumes:
            - ./themes:/opt/jboss/keycloak/themes
    mariadb:
        image: mariadb
        container_name: "mariadb"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=keycloak
            - MYSQL_USER=keycloak
            - MYSQL_PASSWORD=password mariadb
        volumes:
            - ./data/db:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: "phpmyadmin"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - PMA_HOST=mariadb
            - PMA_ARBITRARY=1
        ports:
            - 8100:80
        links:
            - mariadb
        depends_on:
            - mariadb
```

  1. I tried to reinstalling Docker for Mac

**Comment by larsdecker** [comment]
Maybe it is a little bit related to https://github.com/docker/compose/issues/6517 .

**Comment by tobiashinz** [comment]
I "fixed" it by replacing my ` ~/.docker/config.json` with the following one.

```json
{"auths":{},"credsStore":"","experimental":"disabled","stackOrchestrator":"swarm"}
```

**Important** is the part `"credsStore":""`

I keep the issue open as it is definitely a problem.

**Comment by GJKrupa** [comment]
I had the same thing.  @tobiashinz's workaround worked for me although when I increased the VM RAM it added the "credsStore":"desktop" entry back into config.json.

I'm using the 2.1.0.0 (36792) Edge version of Docker for Mac and the same version of MacOS.

**Comment by davidpelayo** [comment]
Confirmed and happened to me after upgraded to 2.1.0.0 stable. Please address this issue. I'll proceed downgrading ASAP

**Comment by davidpelayo** [comment]
The only reliable way to make it work for me is the following (I tried and working fine now):
1. Close any terminal you had opened.
2. Delete your previous Docker for Desktop from your system (by simply removing it from your Applications).
3. Download the latest stable release `Docker Community Edition 2.0.0.3 2019-02-15`: https://download.docker.com/mac/stable/31259/Docker.dmg.
4. (Be careful not to delete unwanted info from your config) Initialize your credentials configuration by running: `docker-credential-gcr configure-docker`

**Comment by tobiashinz** [comment]
Update: Version 2.1.0.1. **did not** fix it for me

**Comment by larsdecker** [comment]
I can confirm that, the issue is still the same.
Please address that issue in the next update, it is really annoying.

**Comment by tuler** [comment]
For me it's trying to use `docker-credentials-pass` no matter what I have in my `~/.docker/config`.
MacOS Catalina 10.15

```
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1085, in up
  File "compose/cli/main.py", line 1081, in up
  File "compose/project.py", line 527, in up
  File "compose/service.py", line 360, in ensure_image_exists
  File "compose/service.py", line 1084, in build
  File "site-packages/docker/api/build.py", line 260, in build
  File "site-packages/docker/api/build.py", line 307, in _set_auth_headers
  File "site-packages/docker/auth.py", line 310, in get_all_credentials
  File "site-packages/docker/auth.py", line 262, in _resolve_authconfig_credstore
  File "site-packages/docker/auth.py", line 287, in _get_store_instance
  File "site-packages/dockerpycreds/store.py", line 25, in __init__
dockerpycreds.errors.InitializationError: docker-credential-pass not installed or not available in PATH
[14279] Failed to execute script docker-compose
```

```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

```
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2
 Built:             Tue Oct  8 00:55:12 2019
 OS/Arch:           darwin/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2
  Built:            Tue Oct  8 01:01:15 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by glensc** [comment]
yes. this is super annoying. the only workaround so far is **not** to use `credsStore=desktop`.

the error is pretty obvious, it calls `docker-credential-desktop get`, as seen it has no url, and command fails, this I believe is docker-compose fault. this happens if the image is without registry, i.e docker.io images.

```
$ grep FROM Dockerfile
FROM debian:9-slim

$ cat ~/.docker/config.json
{
  "HttpHeaders" : {
    "User-Agent" : "Docker-Client/19.03.0-beta3 (darwin)"
  },
  "credsStore" : "desktop"
}

$ docker-compose build
Building griffith
Traceback (most recent call last):
  File "site-packages/dockerpycreds/store.py", line 80, in _execute
  File "subprocess.py", line 356, in check_output
  File "subprocess.py", line 438, in run
subprocess.CalledProcessError: Command '['/usr/local/bin/docker-credential-desktop', 'get']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/docker/auth.py", line 264, in _resolve_authconfig_credstore
  File "site-packages/dockerpycreds/store.py", line 35, in get
  File "site-packages/dockerpycreds/store.py", line 93, in _execute
dockerpycreds.errors.StoreError: Credentials store docker-credential-desktop exited with "error getting credentials - err: exit status 1, out: `no hostname in URL`".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 287, in build
  File "compose/project.py", line 386, in build
  File "compose/project.py", line 368, in build_service
  File "compose/service.py", line 1084, in build
  File "site-packages/docker/api/build.py", line 260, in build
  File "site-packages/docker/api/build.py", line 307, in _set_auth_headers
  File "site-packages/docker/auth.py", line 304, in get_all_credentials
  File "site-packages/docker/auth.py", line 281, in _resolve_authconfig_credstore
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exit status 1, out: `no hostname in URL`".',)
[89066] Failed to execute script docker-compose
$
```

**Comment by hixus** [comment]
I didn't have this issue before but now after 2.1.0.4 update I have

**Comment by hixus** [comment]
But yeah, update enabled credstore so disabling it helped.

**Comment by glensc** [comment]
(cross post https://github.com/docker/compose/issues/6686#issuecomment-560296898)

> 
> my current (better) workaround is to force use of buildkit, which does not invoke docker-credential helper without arguments:
> 
> ```
> $ COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose up
> ```
> 
> ```
> $ docker --version
> Docker version 19.03.5, build 633a0ea
> $ docker-compose --version
> docker-compose version 1.25.0-rc4, build 8f3c9c58
> ```
