### ISSUE TITLE
Can't open menu items (About Docker Desktop, Preferences, Troubleshoot etc.)

### ISSUE THREAD

**Issue by bschultz** [docker/for-mac#3981]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
When clicking on Preferences in the menu the preferences dialog should open.

### Actual behavior
Getting the following error dialog:

Uncaught Exception:
Error: Command failed: ioreg -rd1 -c IOPlatformExpertDevice
/bin/sh: ioreg: command not found

    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:665:15)
    at electron/js2c/asar.js:744:23
    at electron/js2c/asar.js:744:23
    at u (/Applications/Docker.app/Contents/MacOS/Docker Desktop.app/Contents/Resources/app.asar/node_modules/node-machine-id/dist/index.js:1:7825)
    at Object.<anonymous> (/Applications/Docker.app/Contents/MacOS/Docker Desktop.app/Contents/Resources/app.asar/src/service/platform.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)

### Information

  - macOS Version: 10.14.6

$ which ioreg
/usr/sbin/ioreg

### Diagnostic logs

```
Docker for Mac: 2.1.40.

```

### Steps to reproduce the behavior

  1. Try to open docker preferences

**Comment by SarahRiley** [comment]
/remove-lifecycle stale

Also seeing this on the most recent docker for mac.

**Comment by toshipp** [comment]
I also see the issue.
BTW, the issue has been solved after making symlink from /usr/sbin/ioreg to /usr/local/bin.

**Comment by commanderfun** [comment]
Running these two commands and restarting fixed this issue for me:

rm -rf ~/Library/Group\ Containers/group.com.docker/pki/
ln -s /usr/sbin/ioreg to /usr/local/bin
