### ISSUE TITLE
docker-compose: Mounts denied error on Catalina

### ISSUE THREAD

**Issue by rally25rs** [docker/for-mac#4123]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BA91BD80-2D07-466D-B7FE-7A87AFD3659B/20191212163126

### Expected behavior

I have a docker compose yaml that has some relative volume paths:

```
version: '3.7'

services:
  cloud-services-ui:
    build:
      context: '../../cloud-services-ui'
      dockerfile: Dockerfile.dev
    expose:
      - "3000"
    volumes:
      - ../../cloud-services-ui:/usr/src/app
    environment:
      - PORT=3000
    working_dir: /usr/src/app
```

This had been working for quite a while...

### Actual behavior

Today I upgraded to latest Catalina 10.15.2 (I don't know if this is even related, but it's the only thing that changed)

and now I get the error:

```
ERROR: for cloud-services-ui  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 261, in _raise_for_status
  File "site-packages/requests/models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.38/containers/bd30ee0d73b435b4eb5f05a2a3098fab00d0098487f99b6e67a6908e06ba80af/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "compose/service.py", line 625, in start_container
  File "compose/container.py", line 241, in start
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 1095, in start
  File "site-packages/docker/api/client.py", line 263, in _raise_for_status
  File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'Mounts denied: \r\nThe path /users/jvalore/Projects/cloud-services-ui\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1106, in up
  File "compose/cli/main.py", line 1102, in up
  File "compose/project.py", line 570, in up
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/project.py", line 556, in do
  File "compose/service.py", line 546, in execute_convergence_plan
  File "compose/service.py", line 467, in _execute_convergence_create
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/service.py", line 465, in <lambda>
  File "compose/service.py", line 457, in create_and_start
  File "compose/service.py", line 627, in start_container
TypeError: a bytes-like object is required, not 'str'
[5271] Failed to execute script docker-compose
```

This seems to be related to the `../../` relative path. If I replace it with

```
    volumes:
      - ~/cloud-services-ui:/usr/src/app
```

then it starts working again.

### Information

  - macOS Version: Catalina 10.15.2
  - Docker for Mac 2.1.6.0 (edge). I also tried 2.1.7.0.

One thing that I found odd is that the message says:

```
The path /users/jvalore/Projects/cloud-services-ui\r\nis not shared from OS X
```
Notice that `users` is all lowercase.
On OSX it is Titlecase
```
/Users
```
so I don't know where it's getting that lowercase `users` from or if this is even part of the issue.

### Diagnostic logs

(diag uploaded. ID is above)

### Steps to reproduce the behavior
`docker-compose -f ...` with the above yaml snippet.

**Comment by rally25rs** [comment]
Found my mistake... I actually had a lowercase `/users` in a script that was starting docker-compose. Strangely it seems like `docker-compose -f` was having no trouble finding the yaml files via a lowercase `/users` even though that doesn't seem to actually exist. Might be some weird internal OSX filesystem thing that allows `/users` to resolve to `/Users` under certain conditions 🤷‍♂
