### ISSUE TITLE
Exception in thread Thread-N: Bad response from Docker engine, dial unix: connection refused

### ISSUE THREAD

**Issue by f3ndot** [docker/for-mac#423]
### Expected behavior

Docker starts all of the micro services just fine.

### Actual behavior

All contains fail with exit status 1 when they're all starting up.

### Information

Diagnostic ID: B06EB172-1ECD-412A-9A1D-19492C239FE6
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

### Steps to reproduce

Starting up a bunch of micro services, around 26, for development of our front-end system.

```
$ docker-compose build #succeeds
foobar uses an image, skipping
...
Building nginx
...
Successfully built 4756ebaef52d
$ docker-compose up -d # appears to succeed
Starting serverapps_foobar_1
Creating serverapps_nginx_1
...
```

Having all of the containers boot, they eventually all exit as 1. So now if I try again and then immediately launch `logs -f` to follow why it all falls down:

```
$ docker-compose logs -f
Attaching to serverapps_nginx_1, serverapps_foobar_1 # etc.
# ... logs happen here, as expected. Then suddenly (1x):
Exception in thread Thread-29:
Traceback (most recent call last):
  File "threading.py", line 810, in __bootstrap_inner
  File "threading.py", line 763, in run
  File "compose/cli/log_printer.py", line 190, in watch_events
  File "compose/project.py", line 343, in events
  File "site-packages/docker/client.py", line 253, in _stream_helper
  File "json/__init__.py", line 338, in loads
  File "json/decoder.py", line 369, in decode
ValueError: Extra data: line 2 column 1 - line 3 column 1 (char 698 - 1392)
# ... Some more logs happen, then suddenly (3x):
Exception in thread Thread-11:
Traceback (most recent call last):
  File "threading.py", line 810, in __bootstrap_inner
  File "threading.py", line 763, in run
  File "compose/cli/log_printer.py", line 149, in tail_container_logs
  File "compose/cli/log_printer.py", line 179, in wait_on_exit
  File "compose/container.py", line 239, in wait
  File "site-packages/docker/utils/decorators.py", line 21, in wrapped
  File "site-packages/docker/api/container.py", line 441, in wait
  File "site-packages/docker/client.py", line 174, in _raise_for_status
APIError: 502 Server Error: Bad Gateway ("Bad response from Docker engine")
# Followed by (~20x):
Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.py", line 810, in __bootstrap_inner
  File "threading.py", line 763, in run
  File "compose/cli/log_printer.py", line 149, in tail_container_logs
  File "compose/cli/log_printer.py", line 179, in wait_on_exit
  File "compose/container.py", line 239, in wait
  File "site-packages/docker/utils/decorators.py", line 21, in wrapped
  File "site-packages/docker/api/container.py", line 441, in wait
  File "site-packages/docker/client.py", line 174, in _raise_for_status
APIError: 500 Server Error: Internal Server Error ("dial unix /Users/jbull/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused")
```

At this point, doing `docker-compose ps` shows all entry states are `Exit 1`.

I'm not even remotely sure what the root cause is. According to other developers who prefer the Docker Toolbox have no issues with the same repo.

This issue may be related to a discussion going on in the Docker forums: https://forums.docker.com/t/exception-in-thread-thread-n-in-beta-13/13663/16

**Comment by f3ndot** [comment]
Was able to use `docker-machine` as a workaround, for those who are googling.

**Comment by inlanger** [comment]
Solved issue by increasing ram and after that change back it to default  (2gb ). Looks like it's showing that it used 2gb but on deal it's used much less. And after setup it's become normal 2gb

**Comment by tzvika-m-ironsrc** [comment]
Ever since I'm working with more dockers in my docker-compose (7 right now) I get this errors 
constantly. 
mac os: 10.11.5 
Docker for Mac: 1.12.1-beta26.1 (build: 12100)

Exception in thread Thread-11:
Traceback (most recent call last):
  File "threading.py", line 810, in __bootstrap_inner
  File "threading.py", line 763, in run
  File "compose/cli/log_printer.py", line 149, in tail_container_logs
  File "compose/cli/log_printer.py", line 179, in wait_on_exit
  File "compose/container.py", line 239, in wait
  File "site-packages/docker/utils/decorators.py", line 21, in wrapped
  File "site-packages/docker/api/container.py", line 441, in wait
  File "site-packages/docker/client.py", line 174, in _raise_for_status
APIError: 502 Server Error: Bad Gateway ("Bad response from Docker engine")

Exception in thread Thread-13:
Traceback (most recent call last):
  File "threading.py", line 810, in __bootstrap_inner
  File "threading.py", line 763, in run
  File "compose/cli/log_printer.py", line 149, in tail_container_logs
  File "compose/cli/log_printer.py", line 179, in wait_on_exit
  File "compose/container.py", line 239, in wait
  File "site-packages/docker/utils/decorators.py", line 21, in wrapped
  File "site-packages/docker/api/container.py", line 441, in wait
  File "site-packages/docker/client.py", line 174, in _raise_for_status
APIError: 502 Server Error: Bad Gateway ("Bad response from Docker engine")

etc... etc...

**Comment by soundsgoodsofar** [comment]
Same issue.  Running 7 containers and I get that same trace after its up for a few minutes.  Completely unusable atm.

os x 10.11.6 (15G31)
Docker Version 1.12.1 (build: 12133)
2d5b4d9c3daa089e3869e6355a47dd96dbf39856

**Comment by samoht** [comment]
@f3ndot 

Detected symptom of problem 'aufs-corruption' in B06EB172-1ECD-412A-9A1D-19492C239FE6/20160825-110732.

The daemon cannot start because some files in /var/lib/docker are corrupt. This can happen if the filesystem is unmounted uncleanly. The workaround is to reset to factory defaults which will unfortunately delete /var/lib/docker: all containers and images will need to be rebuilt.

May be related to docker/for-mac#20

The following log matches:
```
time="2016-08-25T13:59:51.927326085Z" level=debug msg="Using default logging driver json-file"
time="2016-08-25T13:59:51.928065274Z" level=debug msg="Golang's threads limit set to 13950"
time="2016-08-25T13:59:51.928519575Z" level=debug msg="[graphdriver] trying provided driver \"aufs\""
time="2016-08-25T13:59:51.932519190Z" level=debug msg="Using graph driver aufs"
time="2016-08-25T13:59:53.387187334Z" level=debug msg="Failed to load mount 40ad704fe6134c7f451af905e69a993c026d0a928a63b7369d816fc0e7562a46: invalid mount id value"
time="2016-08-25T13:59:53.396900141Z" level=debug msg="Max Concurrent Downloads: 3"
time="2016-08-25T13:59:53.397385589Z" level=debug msg="Max Concurrent Uploads: 5"
time="2016-08-25T13:59:53.466140705Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2016-08-25T13:59:53.468270213Z" level=debug msg="Loaded container 02fcf42e924e9d6f80f8e991ca14e50743f51b6e133c8d2b61ff1b3f99d23e54"
time="2016-08-25T13:59:53.469346682Z" level=debug msg="Loaded container 08dc0f54f5437f5fd69823e6f034581556fc7b9bc7761d3085c33f54910b184a"
```
---

@tzvika-m-ironsrc and @soundsgoodsofar please open a new issue with a Diagnostic ID so that we can investigate your issue. Thanks!
