### ISSUE TITLE
After installing MacOS version 10.15.6

### ISSUE THREAD

**Issue by henkdonker** [docker/for-mac#4934]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by henkdonker** [comment]
> * ...

After trying to run docker-compose up -d i get the following errors:
Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 259, in _raise_for_status
  File "site-packages/requests/models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 205, in _retrieve_server_version
  File "site-packages/docker/api/daemon.py", line 181, in version
  File "site-packages/docker/api/client.py", line 265, in _result
  File "site-packages/docker/api/client.py", line 261, in _raise_for_status
  File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'dial unix docker.raw.sock: connect: connection refused'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 123, in perform_command
  File "compose/cli/command.py", line 69, in project_from_options
  File "compose/cli/command.py", line 132, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "site-packages/docker/api/client.py", line 188, in __init__
  File "site-packages/docker/api/client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: 500 Server Error: Internal Server Error ("b'dial unix docker.raw.sock: connect: connection refused'")
[3317] Failed to execute script docker-compose

**Comment by j-avila** [comment]
same here but in windows 10

**Comment by JuanmanDev** [comment]
> same here but in windows 10

I have the same issue, try with **admin powershell**, it worked for me.

**Comment by necipallef** [comment]
`docker container prune` worked in my case.

**Comment by helro154** [comment]
so has anyone figured this out yet?

**Comment by tannerhallman** [comment]
@necipallef's solution worked for me, and 27 others it seems.
