### ISSUE TITLE
Docker is stuck in starting phase

### ISSUE THREAD

**Issue by colceagus** [docker/for-mac#5141]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 9D5A396D-5356-4934-B054-652D905CDB47/20201217113826

### Expected behavior
Docker starts
### Actual behavior
Docker is stuck in starting phase
### Information

Please, help us understand the problem.  For instance:
  - Is it reproducible? YES
  - Is the problem new? YES. have never experienced this error before.
  - Did the problem appear with an update? YES. Docker for Mac 3.0.1 and McAfee 10.7.5 (enterprise)
  
  - macOS Version: 10.15.7
  - Docker for Mac: 3.0.1
  - have read on github that it appeared before, and tried the proposed solutions/workarounds, but didn't work for me.
  - have never experienced this error before.
  - the problem appeared with the update to v3.0.1 of Docker for Mac and McAfee 10.7.5
  - disabling or adding a rule in the McAfee Firewall fixes it. This was not needed before. The rules disappear after a while so it's not sustainable. 
  - I have tried: clean/purge data from docker for mac, reset to factory defaults, reinstall, uninstall from docker from mac and reinstall using both homebrew and dmg from docker.

### Diagnostic logs

```
Docker for Mac: 3.0.1
There was only: "Diagnose succeeded"
I've looked into the archive with the diagnose:
Mac Console: com.docker.driver.amd64-linux - cannot ask lifecycle-server to start docker: Get "http://unix/docker/start": context deadline exceeded
System.json:   "hypervisor_status": "FAIL: impossible case" 
log-asl.txt: 2020-12-11 15:57:07+02 dhcp-10-175-32-105 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-11 15:57:07+02 dhcp-10-175-32-105 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-11 15:57:07+02 dhcp-10-175-32-105 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-11 15:57:08+02 dhcp-10-175-32-105 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit, error = 2: No such file or directory
2020-12-15 15:55:43+02 dhcp-10-175-37-54 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-15 15:55:43+02 dhcp-10-175-37-54 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-15 15:55:43+02 dhcp-10-175-37-54 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-15 15:55:43+02 dhcp-10-175-37-54 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-15 15:55:45+02 dhcp-10-175-37-54 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit, error = 2: No such file or directory
2020-12-16 18:48:29+02 dhcp-10-175-50-113 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-16 18:48:29+02 dhcp-10-175-50-113 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-16 18:48:30+02 dhcp-10-175-50-113 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-16 18:48:31+02 dhcp-10-175-50-113 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit, error = 2: No such file or directory
2020-12-16 18:53:44+02 dhcp-10-175-50-113 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-16 18:53:44+02 dhcp-10-175-50-113 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-16 18:53:44+02 dhcp-10-175-50-113 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-16 18:53:48+02 dhcp-10-175-50-113 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-16 18:53:49+02 dhcp-10-175-50-113 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit, error = 2: No such file or directory
2020-12-16 18:57:57+02 dhcp-10-175-50-113 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-16 18:57:58+02 dhcp-10-175-50-113 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit, error = 2: No such file or directory
2020-12-16 18:59:49+02 dhcp-10-175-50-113 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-16 18:59:50+02 dhcp-10-175-50-113 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit, error = 2: No such file or directory
2020-12-16 19:01:01+02 dhcp-10-175-50-113 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-16 19:01:01+02 dhcp-10-175-50-113 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-16 19:01:02+02 dhcp-10-175-50-113 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-16 19:01:03+02 dhcp-10-175-50-113 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-16 19:01:03+02 dhcp-10-175-50-113 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit, error = 2: No such file or directory
2020-12-16 19:12:54+02 dhcp-10-175-0-89 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-16 19:12:54+02 dhcp-10-175-0-89 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-16 19:12:54+02 dhcp-10-175-0-89 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-16 19:12:55+02 dhcp-10-175-0-89 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit, error = 2: No such file or directory
2020-12-16 19:14:28+02 dhcp-10-175-0-89 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit, error = 2: No such file or directory
2020-12-16 19:14:29+02 dhcp-10-175-0-89 log[com.apple.log][2660] <Notice>: log run noninteractively, parent: 2625 (com.docker.diagnose), args: '/usr/bin/log' 'show' '--debug' '--info' '--style' 'syslog' '--last' '1d' '--predicate' 'process matches ".*[Dd]ocker.*" || (process in {"kernel", "launchservicesd", "taskgated-helper"} &

```

### Steps to reproduce the behavior

  1. Upgrade to Docker for Mac 3.0.1 
  2. Start Docker for Mac

**Comment by blakestoddard** [comment]
I also saw this and found that everything worked on my second launch attempt.

**Comment by colceagus** [comment]
What happened to solve my problem: 

Disabling McAfee firewall. Tried adding the whole docker.app to the exclusion list in the firewall for all ports and all interfaces, didn't work. I have to figure out which process or address to add to exclude http://unix/docker/start

**Comment by harrouet** [comment]
I have the exact same issue, except I do not have McAfee and disabling the system's firewall does not help.

It seems to be linked to an issue with `docker-credential-osxkeychain`, as it hangs on any `docker-credential-osxkeychain store` or `docker-credential-osxkeychain get` cli command.

**Comment by marcelloromani** [comment]
FWIW I have Big Sur (11.0.1 build 20B50)
Docker wouldn't start (stuck in 'docker is starting' phase).
When I clicked "updated" it told me I already had the latest version 3.0.1

My workaround was "reset to factory defaults"
The daemon status changed to "Docker is updating", it asked me for privileged access and eventually started.

I hope this helps someone.

**Comment by harrouet** [comment]
> FWIW I have Big Sur (11.0.1 build 20B50)
> Docker wouldn't start (stuck in 'docker is starting' phase).
> When I clicked "updated" it told me I already had the latest version 3.0.1
> 
> My workaround was "reset to factory defaults"
> The daemon status changed to "Docker is updating", it asked me for privileged access and eventually started.
> 
> I hope this helps someone.

Good for you, in my case I cannot even change preferences or reset defaults. `Docker is starting...` forever.

**Comment by hananabud** [comment]
> I have the exact same issue, except I do not have McAfee and disabling the system's firewall does not help.
> 
> It seems to be linked to an issue with `docker-credential-osxkeychain`, as it hangs on any `docker-credential-osxkeychain store` or `docker-credential-osxkeychain get` cli command.

Can you share how did you get to this stage? I have this issue for a few days now and I've tried every suggestions that I could find. I don't have McAfee installed too. Downgrading, reinstalling or reset to factory defaults doesn't work. I checked the logs from `~/Library/Containers/com.docker.docker/Data/vms/0/console-ring` and it says `error copying: write unix /run/host-services/backend.sock->@: write: broken pipe`

**Comment by marcelloromani** [comment]
@harrouet I had to first Quit Docker and relaunch it

**Comment by harrouet** [comment]
> > I have the exact same issue, except I do not have McAfee and disabling the system's firewall does not help.
> > It seems to be linked to an issue with `docker-credential-osxkeychain`, as it hangs on any `docker-credential-osxkeychain store` or `docker-credential-osxkeychain get` cli command.
> 
> Can you share how did you get to this stage? I have this issue for a few days now and I've tried every suggestions that I could find. I don't have McAfee installed too. Downgrading, reinstalling or reset to factory defaults doesn't work.

Sure, you may find details in [the following issue](https://github.com/docker/for-mac/issues/5137)

If I just try a `docker-credential-osxkeychain list`, I get the following in the logs (`syslog | tail`):
```
Dec 18 21:49:51 JDs-MBP com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.docker-credenti.76445) <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
```

**Comment by harrouet** [comment]
> @harrouet I had to first Quit Docker and relaunch it

lucky you. I can't even `stop Docker`, I have to kill the processes manually. `Docker.app`is not unresponsive per say, but it fails to control the docker processes, e.g. `backend` or `hyperkit`, which become CPU hogs. 
I can't even change the settings: the page appears but everything is greyed out.

**Comment by hananabud** [comment]
I have the same issue

- [x] I have tried with the latest version of my channel (Stable or Edge)
- [x] I have uploaded Diagnostics
- Diagnostics ID: 7A7AE7A5-2E7E-4A4D-B590-1053131723AA/20201219044624

### Expected behavior
* Docker should be able to start

### Actual behavior
* Docker is in _starting_ mode forever

### Information

  - macOS Version: Catalina 10.15.7

### Diagnostic logs

From the screen, I have only `Diagnose succeeded`

<img width="354" alt="Screenshot 2020-12-19 at 12 55 22" src="https://user-images.githubusercontent.com/16091840/102681076-76c1b300-41f9-11eb-80ae-c65973fd813d.png">

After going through the log (log-asl.txt):

```
Docker for Mac: 3.0.2
2020-12-19 12:33:20+08 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit, error = 2: No such file or directory
2020-12-19 12:42:10+08 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-19 12:42:10+08 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-19 12:42:10+08 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-19 12:42:10+08 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
2020-12-19 12:42:33+08 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit, error = 2: No such file or directory
2020-12-19 12:48:17+08 com.apple.xpc.launchd[user][1] <Error>: Failed to bootstrap path: path = /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit, error = 2: No such file or directory
2020-12-19 12:48:17+08 log[com.apple.log][28167] <Notice>: log run noninteractively, parent: 28019 (com.docker.diagnose), args: '/usr/bin/log' 'show' '--debug' '--info' '--style' 'syslog' '--last' '1d' '--predicate' 'process matches ".*[Dd]ocker.*" || (process in {"kernel", "launchservicesd", "taskgated-helper"}

```

### Steps to reproduce the behavior


  1. Upgrade Docker when there was a prompt for an update
  2. Reinstalling, downgrading or reset to factory defaults will bring me to the same state.

I opened an issue #5158 but closed it as it is a duplicate of this. Please advise. Thank you :)

**Comment by ebriney** [comment]
Hello.
I created a ticket in our backlog, but unfortunately that's not straightforward to fix.
I wonder why McAfee is blocking http connexions on sockets!
Is it blocking any other Intra Process Communications?  (such as grpc over sockets or Mach ports)

**Comment by henrahmagix** [comment]
I have this problem too on `3.1.0`: running `docker-credential-osxkeychain list` myself returns `{}` but I also see the same error in syslog:
```
Jan 21 09:31:48 MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.docker-credenti.9374) <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
```

Also, running `docker-credential-osxkeychain get` hangs indefinitely, so that's what Docker startup is getting stuck on.

I don't have McAfee or any antivirus or any firewall blocking.

```
henry@mac: ~
$ ll /usr/local/bin/docker-credential-osxkeychain
lrwxr-xr-x  1 root  admin  77 17 May  2020 /usr/local/bin/docker-credential-osxkeychain -> /Applications/Docker.app/Contents/Resources/bin/docker-credential-osxkeychain
henry@mac: ~
$ ll /Applications/Docker.app/Contents/Resources/bin/docker-credential-osxkeychain
-rwxr-xr-x  1 henry  admin  2551168 13 Jan 21:29 /Applications/Docker.app/Contents/Resources/bin/docker-credential-osxkeychain
```

This immediately started after upgrading to `3.1.0`. I forget what version I was on before. I cannot factory reset or anything because I don't want to lose my local DB volume data.

**Comment by harrouet** [comment]
I see many people with similar issues. Is anyone working on it ? 
How can we help ? Any log we can provide ?
I guess we'll have to find docker alternatives for now :(

**Comment by marcelloromani** [comment]
@harrouet as far as I can tell it's an issue specific to Docker Desktop for Mac. You can always install docker using vagrant or virtualbox. (Also out of curiosity: what alternatives to Docker would you suggest? )

**Comment by rgov** [comment]
> Also, running `docker-credential-osxkeychain get` hangs indefinitely, so that's what Docker startup is getting stuck on.

Are you sure about this? This tool is waiting for a URL on standard input.

    $ echo 'id.docker.com' | ./bin/docker-credential-osxkeychain get
    credentials not found in native keychain

**Comment by harrouet** [comment]
> @harrouet as far as I can tell it's an issue specific to Docker Desktop for Mac. You can always install docker using vagrant or virtualbox. (Also out of curiosity: what alternatives to Docker would you suggest? )

I am at the `search google` stage in this endeavour. :) 
`Nanobox`, `Singularity` or `Packer` seems to be trying to be just that. But obviously to code something that will need a good uptime, I start to wonder if docker is fit for the task. What if `docker can't start` on your production server tomorrow ? 

This `docker can't start` issue has been around for months, but no one seems to be looking at the issue. I'd rather pay for something that works.

> Are you sure about this? This tool is waiting for a URL on standard input.

I also get `docker-credential-osxkeychain` to hang. I believe this is where `Docker Desktop` for Mac is having issues.

**Comment by rgov** [comment]
@harrouet The `docker-credential-osxkeychain` tool is open source and I reviewed the code and it isn't doing much, just talking to the macOS Keychain APIs. How are you determining it is hanging -- is it stuck running in Activity Monitor, and if so can you take a sample? Or are you trying to run it yourself from the command line, and if so, how are you invoking it?

**Comment by harrouet** [comment]
> @harrouet The `docker-credential-osxkeychain` tool is open source and I reviewed the code and it isn't doing much, just talking to the macOS Keychain APIs. How are you determining it is hanging -- is it stuck running in Activity Monitor, and if so can you take a sample? Or are you trying to run it yourself from the command line, and if so, how are you invoking it (arguments, standard input, etc.)?

Details [here](https://github.com/docker/for-mac/issues/5137#issue-768702141)

Basically when I launch Docker for Mac, I get this in my logs:
```
Dec 16 11:31:19 MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.docker-credenti.1401) <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory
```
trying to run in command line `docker-credential-osxkeychain list` returns `{}`, but `store` or `get` don't return until a `^C`. 
So I assumed that the issue was with `docker-credential-osxkeychain`.

But I might be wrong, as I see many `Docker won't start` issues with a similar path error in the logs (`Failed to bootstrap path: path[...]`) but with a different command than `docker-credential-osxkeychain`.

**Comment by rgov** [comment]
Yeah, 

> trying to run in command line `docker-credential-osxkeychain list` returns `{}`, but `store` or `get` don't return until a `^C`.

They don't return because they are waiting for you to provide input, just like if you type `cat` it seems to hang until you type something and then hit <kbd>Ctrl</kbd> + <kbd>D</kbd> (^D). I think this is not the root cause.

**Comment by harrouet** [comment]
> Yeah,
> 
> > trying to run in command line `docker-credential-osxkeychain list` returns `{}`, but `store` or `get` don't return until a `^C`.
> 
> They don't return because they are waiting for you to provide input, just like if you type `cat` it seems to hang until you type something and then hit Ctrl + D (^D). I think this is not the root cause.

Indeed... I wish I could isolate the issue. I still have these `com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.docker-credenti.1401) <Error>: Failed to bootstrap path: path = /usr/local/bin/docker-credential-osxkeychain, error = 2: No such file or directory` error, like many of us.

**Comment by harrouet** [comment]
Actually I might have a hint in the logs from `com.docker.backend`:
```
time="2021-02-01T12:24:07+01:00" level=error msg="error accepting multiplexer data connection: EOF"
goroutine 28 [running]:
github.com/moby/vpnkit/go/pkg/vpnkit/log.Errorf(...)
        /Users/administrator/jenkins/workspace/desktop_desktop-build_master/src/github.com/docker/pinata/vendor/github.com/moby/vpnkit/go/pkg/vpnkit/log/log.go:23
github.com/moby/vpnkit/go/pkg/vpnkit/control.(*Control).handleDataConn(0xc000597830, 0xc32d1a0, 0xc000516170, 0xc0000a24e0, 0xc000516100)
        /Users/administrator/jenkins/workspace/desktop_desktop-build_master/src/github.com/docker/pinata/vendor/github.com/moby/vpnkit/go/pkg/vpnkit/control/control.go:170 +0x13a
github.com/moby/vpnkit/go/pkg/vpnkit/control.(*Control).ListenOnListener(0xc000597830, 0x55a3bc0, 0xc000597bf0, 0xc000359a00, 0x15, 0xc0000a24e0)
        /Users/administrator/jenkins/workspace/desktop_desktop-build_master/src/github.com/docker/pinata/vendor/github.com/moby/vpnkit/go/pkg/vpnkit/control/control.go:143 +0x28c
created by main.startPortControl
        /Users/administrator/jenkins/workspace/desktop_desktop-build_master/src/github.com/docker/pinata/common/cmd/com.docker.backend/main.go:148 +0x2eb
time="2021-02-01T12:24:07+01:00" level=info msg="listening on unix:vpnkit.data.sock for data connection"
time="2021-02-01T12:24:10+01:00" level=info msg="internal: GET /ping 200 \"DockerDesktopGo\" \"\""
time="2021-02-01T12:24:12+01:00" level=info msg="internal: GET /vm/init 500 \"DockerDesktopGo\" \"during /vm/init: cannot fetch ca-certificates.crt: exit status 49\""
time="2021-02-01T12:24:14+01:00" level=info msg="internal: GET /vm/init 500 \"DockerDesktopGo\" \"during /vm/init: cannot fetch ca-certificates.crt: exit status 49\""
time="2021-02-01T12:24:17+01:00" level=info msg="internal: GET /vm/init 500 \"DockerDesktopGo\" \"during /vm/init: cannot fetch ca-certificates.crt: exit status 49\""
```

So it all starts from an error line 148 in `com.docker.backend/main.go`.
Note that this is after an all-fresh install, i.e. uninstall Docker (manually as per [this post](https://stackoverflow.com/questions/44346109/how-to-easily-install-and-uninstall-docker-on-macos), since `Docker --uninstall` would not work either), then re-installing the lastest version (3.1.0).

**Comment by gtskaushik** [comment]
Disabling McAfee solved the problem. Still trying to figure what exclusions I have to add in McAfee

**Comment by guycalledseven** [comment]
I got stuck in this after updated to v3.2.0. removed everything reinstalled.
Then I wanted to change Resources / File sharing directories (to speed it up) and after Apply & Restart I again got it stuck again in the same starting phase. Had to remove and reinstall again.
