### ISSUE TITLE
docker login  panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ligson** [docker/for-mac#5423]
docker version:

```bash
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

docker desktop version:

```bash
3.1.0(51484)
```

mac version:
```bash
 系统版本：	macOS 11.2.2 (20D80)
 内核版本：	Darwin 20.3.0
```

docker login  

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x46742b4]

goroutine 1 [running]:
github.com/docker/cli/cli/command.ConfigureAuth(0x5d83020, 0xc000525ad0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5ce7500, 0xc0005f0b40, 0xc000673968)
	/go/src/github.com/docker/cli/cli/command/registry.go:128 +0x44
github.com/docker/cli/cli/command/registry.runLogin(0x5d83020, 0xc000525ad0, 0x7ffeefbfeb6c, 0x17, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/cli/cli/command/registry/login.go:123 +0x221
github.com/docker/cli/cli/command/registry.NewLoginCommand.func1(0xc0005cd600, 0xc0005f0a50, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/cli/cli/command/registry/login.go:45 +0xca
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc0005cd600, 0xc000540af0, 0x1, 0x1, 0xc0005cd600, 0xc000540af0)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:850 +0x460
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00011bb80, 0xc000540ae0, 0x2, 0x2)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:958 +0x349
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:895
main.runDocker(0xc000525ad0, 0x5cea220, 0xc0000e4010)
	/go/src/github.com/docker/cli/cmd/docker/docker.go:287 +0x1d1
main.main()
	/go/src/github.com/docker/cli/cmd/docker/docker.go:298 +0xf1
```

**Comment by ligson** [comment]
这个版本已经解决！

```bash
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
