### ISSUE TITLE
3.3.0 RC3 M1: executor failed running [/bin/sh -c make build]: exit code: 2

### ISSUE THREAD

**Issue by andig** [docker/for-mac#5506]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A913E1F9-1085-4C2B-A79D-4B6862C0EA1E/20210325161003

### Expected behavior

Docker-based build finishes

### Actual behavior

Build error:

```
...
#33 12.07 github.com/influxdata/influxdb-client-go/v2
#33 12.12 github.com/andig/evcc/server
#33 12.18 github.com/andig/evcc/server/updater
#33 12.18 github.com/andig/evcc/hems/semp
#33 12.24 github.com/andig/evcc/hems
#33 12.32 make: *** [Makefile:55: build] Error 2
------
executor failed running [/bin/sh -c make build]: exit code: 2
```

### Information

  - macOS Version: 11.2.3 (20D91)
  - Docker Desktop Version: 3.3.0

### Steps to reproduce the behavior

    docker build -t andig/evcc:latest .

It looks like a `Makefile` problem. However, the process finished while running docker 3.1.0 tech preview (M1), but does no longer run on 3.3.0

**Comment by felri** [comment]
I just rolled back to 3.1 until this 3.3 problems are fixed

https://desktop.docker.com/mac/stable/arm64/60984/Docker.dmg

**Comment by andig** [comment]
Got another one today during compile that looks similar:

```
#30 80.35 github.com/hashicorp/hcl/hcl/printer
#30 80.46 github.com/hashicorp/hcl/json/parser
#30 80.58 github.com/pelletier/go-toml
#30 81.03 github.com/hashicorp/hcl
#30 81.11 github.com/spf13/afero/mem
#30 81.45 # github.com/hashicorp/hcl
#30 81.45 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

Also saw a Linux kernel crash but could not generate the diagnostics. Rolling back to 3.1.0.

**Comment by andig** [comment]
> I just rolled back to 3.1 until this 3.3 problems are fixed

@felri OT, but how did you do this? After going back to 3.1, I'm no longer to start it, it just doesn't come up. Process is visible but no UI, daemon not reachable?

**Comment by djs55** [comment]
Thanks for your report. This error
```
#30 81.45 # github.com/hashicorp/hcl
#30 81.45 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```
suggests a bug in the `qemu` emulation of Intel binaries on Apple Silicon. Unfortunately this is fairly common and the only reliable workaround for now is to switch to native `arm64`/`aarch64` images. I recommend checking your `Dockerfile`, and looking at the base images (`FROM ...`) and then checking on hub.docker.com whether these are multiarch already or not.

**Comment by andig** [comment]
> Unfortunately this is fairly common and the only reliable workaround for now is to switch to native arm64/aarch64 images.

It's what I'm running imho- just plain alpine:1.13. I have since seen a number more compile failures both on 3.1.0 and 3.3.0 that I've never seen on amd64.

**Comment by andig** [comment]
For what it's worth: the errors include random corruptions like this one:

```
=> ERROR [builder 8/8] RUN make build                                                                                                                  50.2s
------
 > [builder 8/8] RUN make build:
#15 0.194 fatal: No names found, cannot describe anything.
#15 0.237 Version: 5edc9da 2021-03-31_20:42:03
#15 0.238 go build -ldflags='-s -w'
#15 31.15 # github.com/andig/evcc-cloud/vehicle
#15 31.15 vehicle/carwings.go:108:22: undefined: api.ErrNotAv��S
#15 50.15 make: *** [Makefile:20: build] Error 2
------
```

**Comment by andig** [comment]
These corruptions appear regularly:

```
 => ERROR [builder 8/8] RUN make build                                                                                                                                                                                                  47.6s
------
 > [builder 8/8] RUN make build:
#17 0.226 fatal: No names found, cannot describe anything.
#17 0.269 Version: 209440e 2021-04-02_09:28:32
#17 0.270 go build -ldflags='-s -w'
#17 47.51 # google.golang.org/grpc
#17 47.51 /go/pkg/mod/google.golang.org/grpc@v1.36.1/clientconn.go:19:9: package ; expected grpc
#17 47.51 /go/pkg/mod/google.golang.org/grpc@v1.36.1/server.go:299:24: undefined: ServerOp��S
#17 47.55 make: *** [Makefile:20: build] Error 2
```

I've never seen them on the old Intel Mac/ old Docker, same multiarch setup. I can only assume it's something with Docker.

**Comment by andig** [comment]
Another one, this time crash:

```
 => ERROR [builder 8/8] RUN make build                                                                                                                                                                                                  46.4s
------
 > [builder 8/8] RUN make build:
#17 0.268 fatal: No names found, cannot describe anything.
#17 0.314 Version: 209440e 2021-04-02_09:34:23
#17 0.315 go build -ldflags='-s -w'
#17 45.27 # google.golang.org/grpc/status
#17 45.27 SIGILL: illegal instruction
#17 45.27 PC=0xc0003f3d28 m=4 sigcode=3967520
#17 45.27 instruction bytes: 0x26 0x31 0xa9 0x0 0x0 0x0 0x0 0x0 0x58 0x3d 0x3f 0x0 0xc0 0x0 0x0 0x0
#17 45.27
#17 45.27 goroutine 1 [running]:
#17 45.27 runtime: unknown pc 0xc0003f3d28
#17 45.27 stack: frame={sp:0x206, fp:0x0} stack=[0xc0003f0000,0xc0003f8000)
#17 45.27
#17 45.27 runtime: unknown pc 0xc0003f3d28
#17 45.27 stack: frame={sp:0x206, fp:0x0} stack=[0xc0003f0000,0xc0003f8000)
#17 45.27
#17 45.27
#17 45.27 rax    0xc000551260
#17 45.27 rbx    0xc0005508a0
#17 45.27 rcx    0xc000551740
#17 45.27 rdx    0xc000550c00
#17 45.27 rdi    0xc000542600
#17 45.27 rsi    0xc000543620
#17 45.27 rbp    0xc000549380
#17 45.27 rsp    0x206
#17 45.27 r8     0xc000524de0
#17 45.27 r9     0xc000525380
#17 45.27 r10    0xc000538600
#17 45.27 r11    0xc0005392c0
#17 45.27 r12    0xc0005394a0
#17 45.27 r13    0xc00053ed80
#17 45.27 r14    0xc00053f6e0
#17 45.27 r15    0xc00053fb00
#17 45.27 rip    0xc0003f3d28
#17 45.27 rflags 0xc00005a230
#17 45.27 cs     0x2e40
#17 45.27 fs     0xc0
#17 45.27 gs     0x56
#17 46.31 make: *** [Makefile:20: build] Error 2
------
executor failed running [/bin/sh -c make build]: exit code: 2
make: *** [multiarch] Error 1
```

**Comment by andig** [comment]
I've upgraded to RC3 and wiped the disk image. Build is still crashing, this time in qemu:

```
 => ERROR [builder 8/8] RUN make build                                                                                                                                                                                                  46.3s
------
 > [builder 8/8] RUN make build:
#17 0.195 fatal: No names found, cannot describe anything.
#17 0.238 Version: 209440e 2021-04-02_09:49:24
#17 0.239 go build -ldflags='-s -w'
#17 23.92 # golang.org/x/net/html
#17 23.92 SIGSEGV: segmentation violation
#17 23.92 PC=0x0 m=5 sigcode=0
#17 23.92
#17 23.92 goroutine 18 [running]:
#17 23.92 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
#17 46.30 make: *** [Makefile:20: build] Error 2
------
executor failed running [/bin/sh -c make build]: exit code: 2
make: *** [multiarch] Error 1
```

**Comment by andig** [comment]
@djs55 anything else I could try to get back to reproducible builds? Would full reinstall likely do anything?

**Comment by andig** [comment]
Still seeing various patterns of unclear corruptions with plain alpine base image even after full reinstall:

```
❯ make publish-server
docker build -f soc/Dockerfile --platform linux/amd64 -t andig/evcc-cloud .
[+] Building 10.1s (18/21)
 => [internal] load build definition from Dockerfile                                                                                                                                                                                     0.3s
 => => transferring dockerfile: 37B                                                                                                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                        0.5s
 => => transferring context: 35B                                                                                                                                                                                                         0.1s
 => [internal] load metadata for docker.io/library/alpine:3.13                                                                                                                                                                           2.1s
 => [internal] load metadata for docker.io/library/golang:1.16-alpine                                                                                                                                                                    2.2s
 => [auth] library/golang:pull token for registry-1.docker.io                                                                                                                                                                            0.0s
 => [auth] library/alpine:pull token for registry-1.docker.io                                                                                                                                                                            0.0s
 => [builder  1/10] FROM docker.io/library/golang:1.16-alpine@sha256:6c35b28ceee082c621c818c097f418cd55104a16e51003120c1bf37111ed9cfe                                                                                                    0.0s
 => [internal] load build context                                                                                                                                                                                                        0.5s
 => => transferring context: 922.62kB                                                                                                                                                                                                    0.2s
 => [stage-1 1/4] FROM docker.io/library/alpine:3.13@sha256:ec14c7992a97fc11425907e908340c6c3d6ff602f5f13d899e6b7027c9b4133a                                                                                                             0.0s
 => CACHED [builder  2/10] RUN apk update && apk add --no-cache git ca-certificates tzdata alpine-sdk && update-ca-certificates                                                                                                          0.0s
 => CACHED [builder  3/10] WORKDIR /build                                                                                                                                                                                                0.0s
 => CACHED [builder  4/10] COPY Makefile .                                                                                                                                                                                               0.0s
 => CACHED [builder  5/10] COPY go.mod .                                                                                                                                                                                                 0.0s
 => CACHED [builder  6/10] COPY go.sum .                                                                                                                                                                                                 0.0s
 => CACHED [builder  7/10] RUN make install                                                                                                                                                                                              0.0s
 => CACHED [builder  8/10] RUN go mod download                                                                                                                                                                                           0.0s
 => [builder  9/10] COPY . .                                                                                                                                                                                                             2.3s
 => ERROR [builder 10/10] RUN make server                                                                                                                                                                                                4.4s
------
 > [builder 10/10] RUN make server:
#18 1.084 Version: 0.50 2021-04-10_09:29:50
#18 1.085 go build -o soc-server -tags=release -ldflags='-X github.com/andig/evcc/server.Version=0.50 -X github.com/andig/evcc/server.Commit=85e8bafe' github.com/andig/evcc/soc/server
#18 4.038 internal/vehicle/bluelink/bluelink.go:16:2: unlinkat /go/pkg/mod/github.com/google/uuid@v1.1.5: bad message
#18 4.038 /go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.3.1/websocket.go:11:2: unlinkat /go/pkg/mod/github.com/gorilla/websocket@v1.4.2: structure needs cleaning
#18 4.038 internal/vehicle/bluelink/bluelink.go:17:2: open /go/pkg/mod/github.com/imdario: bad message
#18 4.038 util/jq/jq.go:8:2: open /go/pkg/mod/github.com/itchyny: bad message
#18 4.038 internal/vehicle/carwings.go:10:2: open /go/pkg/mod/github.com/joeshaw: bad message
#18 4.038 provider/script.go:12:2: open /go/pkg/mod/github.com/kballard: bad message
#18 4.038 util/decoder.go:4:2: open /go/pkg/mod/github.com/mitchellh: bad message
```

**Comment by ryanschneider** [comment]
For what it's worth I'm seeing these too:

`docker build --platform linux/amd64 -t ${IMAGE}:${TAG} .`

```
 => ERROR [builder 4/4] RUN CGO_ENABLED=0 GOOS=linux go build -mod vendor -a -installsuffix nocgo -o /out main.go                                                                                                                                                                                                                                                   56.7s
------
 > [builder 4/4] RUN CGO_ENABLED=0 GOOS=linux go build -mod vendor -a -installsuffix nocgo -o /out main.go:
#8 5.717 # github.com/alicebob/miniredis/v2/geohash
#8 5.717 SIGSEGV: segmentation violation
#8 5.717 PC=0x0 m=4 sigcode=0
#8 5.717
#8 5.717 goroutine 35 [running]:
#8 5.717 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
#8 26.62 # golang.org/x/sys/unix
#8 26.62 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
#8 31.79 # net/http
#8 31.79 /usr/local/go/src/net/http/transport.go:10:9: package ��S; expected http
#8 41.19 # text/template
#8 41.19 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
#8 45.32 # google.golang.org/protobuf/proto
#8 45.32 vendor/google.golang.org/protobuf/proto/messageset.go:5:9: package pro��; expected proto
------
executor failed running [/bin/sh -c CGO_ENABLED=0 GOOS=linux go build -mod vendor -a -installsuffix nocgo -o /out main.go]: exit code: 2
```

If I force a restart of the underlaying linux VM (e.g. by changing the amount of RAM under `Preferences | Resources | Advanced | Memory`) it seems to work for a build or two then fails again, almost always with that weird `package ??S` corruption in the stack trace message (but usually in different locations).

**Comment by andig** [comment]
Thanks for confirming.

**Comment by andig** [comment]
For what it's worth: the random corruptions are looking exactly similar if using qemu or virtualization-framework...

**Comment by andig** [comment]
Same on 3.3.1

**Comment by stephen-turner** [comment]
In version 3.3.2, we are launching qemu with an additional argument that may help in some cases. We would be interested to know whether it has solved this problem.

However, note that qemu emulation should only ever be regarded as "best effort". Even when it works it will use more memory and have worse performance. The real solution is to run arm64 containers on M1 hardware.

I'm going to close this ticket now, because there's nothing further that we can do.

**Comment by ryanschneider** [comment]
FWIW this still happens w/ 3.3.3, for example building the Dockerfile included in the go-ethereum project here: https://github.com/ethereum/go-ethereum/blob/master/Dockerfile

Dies with the same corrupt package names:

```
#11 32.58 # runtime
#11 32.58 /usr/local/go/src/runtime/metrics.go:5:9: package run��S; expected runtime
#11 33.01 golang.org/x/net/html/atom
#11 33.01 golang.org/x/text/encoding/internal/identifier
#11 33.01 container/ring
#11 33.23 golang.org/x/text/internal/utf8internal
#11 33.29 google.golang.org/protobuf/internal/flags
#11 33.36 google.golang.org/protobuf/internal/fieldnum
#11 33.37 google.golang.org/protobuf/internal/set
#11 33.48 google.golang.org/protobuf/internal/genname
#11 33.51 github.com/ethereum/go-ethereum/internal/web3ext
#11 41.91 util.go:46: exit status 2
#11 41.91 exit status 1
```

**Comment by andig** [comment]
@ryanschneider see @stephen-turner's comment in https://github.com/docker/for-mac/issues/5555#issuecomment-836332986
