### ISSUE TITLE
Cannot connect to postgresql db running on the host

### ISSUE THREAD

**Issue by cemysf** [docker/for-mac#5514]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C9BC0946-8448-4D73-816E-362B0A40DE2D/20210328114237
### Expected behavior
Can connect to db server which is running on the host machine (see case below)

- This run on host machine within the python environment in the test case
```
% python connect_to_db.py
host:localhost
result proxy:<sqlalchemy.engine.result.ResultProxy object at 0x101514670>
```

### Actual behavior
Cannot connect to db server which is running on the host machine (see case below)

```
% docker run -p 5432:5432 dockerdbbug
host:host.docker.internal
Traceback (most recent call last):
  File "/usr/src/venv3/lib/python3.6/site-packages/postgresql/driver/pq3.py", line 2427, in connect
    self._establish()
  File "/usr/src/venv3/lib/python3.6/site-packages/postgresql/driver/pq3.py", line 2553, in _establish
    self.typio.raise_client_error(could_not_connect, creator = self, cause = exc)
  File "/usr/src/venv3/lib/python3.6/site-packages/postgresql/driver/pq3.py", line 514, in raise_client_error
    raise client_error
postgresql.exceptions.ClientCannotConnectError: could not establish connection to server
  CODE: 08001
  LOCATION: CLIENT
CONNECTION: [failed]
  failures[0]:
    NOSSL socket('192.168.64.1', 5432)
    postgresql.exceptions.ProtocolError: server did not support SSL negotiation
      CODE: 08P01
      LOCATION: CLIENT
      HINT: The server is probably not PostgreSQL.
  failures[1]:
    socket('192.168.64.1', 5432)
    postgresql.exceptions.ConnectionFailureError: unexpected EOF from server
      CODE: 08006
      LOCATION: CLIENT
      DETAIL: Zero-length read from the connection's socket.
CONNECTOR: [Host] pq://spanflug_dev:***@host.docker.internal:5432/spanflug_dev
  category: None
DRIVER: postgresql.driver.pq3.Driver

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/src/venv3/lib/python3.6/site-packages/postgresql/driver/dbapi20.py", line 418, in connect
    return driver.connect(**params)
  File "/usr/src/venv3/lib/python3.6/site-packages/postgresql/driver/pq3.py", line 3037, in connect
    c.connect()
  File "/usr/src/venv3/lib/python3.6/site-packages/postgresql/driver/dbapi20.py", line 358, in connect
    super().connect(*args, **kw)
  File "/usr/src/venv3/lib/python3.6/site-packages/postgresql/driver/pq3.py", line 2430, in connect
    self.close()
  File "/usr/src/venv3/lib/python3.6/site-packages/postgresql/driver/dbapi20.py", line 368, in close
    creator = self
postgresql.exceptions.Error: connection already closed
  LOCATION: CLIENT
CONNECTION: [failed]
  failures[0]:
    NOSSL socket('192.168.64.1', 5432)
    postgresql.exceptions.ProtocolError: server did not support SSL negotiation
      CODE: 08P01
      LOCATION: CLIENT
      HINT: The server is probably not PostgreSQL.
  failures[1]:
    socket('192.168.64.1', 5432)
    postgresql.exceptions.ConnectionFailureError: unexpected EOF from server
      CODE: 08006
      LOCATION: CLIENT
      DETAIL: Zero-length read from the connection's socket.
CONNECTOR: [Host] pq://spanflug_dev:***@host.docker.internal:5432/spanflug_dev
  category: None
DRIVER: postgresql.driver.pq3.Driver

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "connect_to_db.py", line 15, in <module>
    with engine.connect() as connection:
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2263, in connect
    return self._connection_cls(self, **kwargs)
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 104, in __init__
    else engine.raw_connection()
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2370, in raw_connection
    self.pool.unique_connection, _connection
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2340, in _wrap_pool_connect
    e, dialect, self
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1584, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/src/venv3/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/src/venv3/lib/python3.6/site-packages/postgresql/driver/dbapi20.py", line 418, in connect
    return driver.connect(**params)
  File "/usr/src/venv3/lib/python3.6/site-packages/postgresql/driver/pq3.py", line 3037, in connect
    c.connect()
  File "/usr/src/venv3/lib/python3.6/site-packages/postgresql/driver/dbapi20.py", line 358, in connect
    super().connect(*args, **kw)
  File "/usr/src/venv3/lib/python3.6/site-packages/postgresql/driver/pq3.py", line 2430, in connect
    self.close()
  File "/usr/src/venv3/lib/python3.6/site-packages/postgresql/driver/dbapi20.py", line 368, in close
    creator = self
sqlalchemy.exc.DBAPIError: (postgresql.exceptions.Error) connection already closed
  LOCATION: CLIENT
CONNECTION: [failed]
  failures[0]:
    NOSSL socket('192.168.64.1', 5432)
    postgresql.exceptions.ProtocolError: server did not support SSL negotiation
      CODE: 08P01
      LOCATION: CLIENT
      HINT: The server is probably not PostgreSQL.
  failures[1]:
    socket('192.168.64.1', 5432)
    postgresql.exceptions.ConnectionFailureError: unexpected EOF from server
      CODE: 08006
      LOCATION: CLIENT
      DETAIL: Zero-length read from the connection's socket.
CONNECTOR: [Host] pq://spanflug_dev:***@host.docker.internal:5432/spanflug_dev
  category: None
DRIVER: postgresql.driver.pq3.Driver
(Background on this error at: http://sqlalche.me/e/13/dbapi)
```

### Information

  - macOS Version:
  ```
  % sw_vers
ProductName:	macOS
ProductVersion:	11.2.3
BuildVersion:	20D91
  ```
  - Docker Desktop Version:
```
% docker version

Client: Docker Engine - Community
 Cloud integration: 1.0.10
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64 (rosetta)
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:48 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- postgresql version:
```
% postgres --version
postgres (PostgreSQL) 12.6
```

-python version: 3.6

### Steps to reproduce the behavior

My use case is as following: I have MacBook Pro with M1 chip. Postgresql server running on this machine. Inside an ubuntu 18.04 based docker container I need to access this database.

  1. (host machine) Install python3.9, postgresql 12.6, init db etc..
  2. Setup container with following:
```python
# connect_to_db.py
from sqlalchemy import create_engine
import os
running_in_docker = os.environ.get('AM_I_IN_A_DOCKER_CONTAINER', False)
if running_in_docker:
    host = "host.docker.internal"
else:
    host = "localhost"

dbapi = "pypostgresql"

SQLALCHEMY_DATABASE_URI = f"postgresql+{dbapi}://spanflug_dev:development@{host}/spanflug_dev"
engine =create_engine(SQLALCHEMY_DATABASE_URI, pool_pre_ping=True)

with engine.connect() as connection:
    result = connection.execute("select 1")
    print(f"result proxy:{result}")
```

requirements.txt
```
alembic==1.5.8
amqp==2.5.2
appdirs==1.4.4
atomicwrites==1.3.0
attrs==19.3.0
bcrypt==3.2.0
billiard==3.6.3.0
black==20.8b1
blinker==1.4
boto3==1.12.12
botocore==1.15.12
celery==4.4.0
certifi==2019.11.28
cffi==1.14.5
cfgv==3.2.0
chardet==4.0.0
click==7.1.2
coverage==5.0.3
dictdiffer==0.8.1
distlib==0.3.1
docutils==0.15.2
dparse==0.5.1
factory-boy==2.12.0
Faker==4.0.1
filelock==3.0.12
flake8==3.8.4
Flask==1.1.1
Flask-Login==0.5.0
Flask-Migrate==2.5.2
Flask-Script==2.0.6
Flask-SQLAlchemy==2.4.1
flask-talisman==0.7.0
Flask-WTF==0.14.3
freezegun==0.3.15
fuzzywuzzy==0.18.0
gevent==21.1.2
greenlet==1.0.0
identify==1.5.5
idna==2.9
importlib-metadata==1.5.0
infinity==1.4
intervals==0.8.1
isort==5.6.4
itsdangerous==1.1.0
Jinja2==2.11.3
jmespath==0.9.5
kombu==4.6.8
Mako==1.1.2
MarkupSafe==1.1.1
mccabe==0.6.1
more-itertools==8.2.0
mypy-extensions==0.4.3
names==0.3.0
nodeenv==1.5.0
packaging==20.1
pathspec==0.8.0
pluggy==0.13.1
postmarker==0.13.0
pre-commit==2.7.1
py==1.10.0
py-postgresql==1.2.2
pycodestyle==2.6.0
pycparser==2.19
pydantic==1.7.3
pyflakes==2.2.0
pyparsing==2.4.6
pytest==5.3.5
pytest-cov==2.8.1
pytest-flask==0.15.1
python-dateutil==2.8.1
python-dotenv==0.12.0
python-editor==1.0.4
python-Levenshtein==0.12.0
pytz==2019.3
PyYAML==5.4.1
redis==3.4.1
regex==2020.10.23
requests==2.25.1
s3transfer==0.3.3
safety==1.10.3
sentry-sdk==0.20.3
six==1.15.0
SQLAlchemy==1.3.23
SQLAlchemy-Utils==0.36.8
text-unidecode==1.3
toml==0.10.1
typed-ast==1.4.1
typing-extensions==3.7.4.3
urllib3==1.25.9
vine==1.3.0
virtualenv==20.0.31
wcwidth==0.1.8
Werkzeug==1.0.1
WTForms==2.2.1
xmltodict==0.12.0
zipp==3.1.0
zope.event==4.5.0
zope.interface==5.3.0
```

```Dockerfile
FROM ubuntu:18.04

RUN apt-get update -q && \
    DEBIAN_FRONTEND=noninteractive apt-get install -qy locales && \
    locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN apt-get update -q && \
    DEBIAN_FRONTEND=noninteractive apt-get install -qy software-properties-common

RUN  apt-get update -q &&  apt install software-properties-common && \ 
    DEBIAN_FRONTEND=noninteractive apt-get install -qy python3-pip python3-tk python3 python3-pip python3-venv libpq-dev 

RUN python3 -m venv /usr/src/venv3

ADD requirements.txt /app/requirements.txt
RUN /usr/src/venv3/bin/pip install --upgrade pip
RUN /usr/src/venv3/bin/pip install -r /app/requirements.txt

ADD ./connect_to_db.py /app
ENV AM_I_IN_A_DOCKER_CONTAINER Yes

WORKDIR /app
ENTRYPOINT ["/usr/src/venv3/bin/python", "connect_to_db.py"]
```
3. Build and run
```
docker build -f Dockerfile -t dockerdbbug .
docker run -p 5432:5432 dockerdbbug
```

**Comment by cemysf** [comment]
As a quick workaround editing PostgreSQL config solved the problem

Add this to pg_hba.conf
`hostnossl    all             all        192.168.64.0/24         trust`

Add this to postgresql.conf
`listen_addresses = '192.168.64.1, localhost'`
