### ISSUE TITLE
[3.3.0] TLS connections without SNI are dropped - no proxy configured

### ISSUE THREAD

**Issue by jsuchenia** [docker/for-mac#5568]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: EB534CD9-75D4-466D-A913-258112B96218/20210413125544
  

### Expected behavior
TLS connection on 443 without SNI should be passed to the destination machine

### Actual behavior
TLS connections on 443 without SNI are terminated, as http-proxy is enabled by default

### Information
Starting from 3.3.0 connections on port 443 are intercepted by https-proxy

### Steps to reproduce the behavior
  1. Test code:
  ```
#!/usr/bin/python

import socket
import ssl

sock = socket.socket()
conn = ssl.wrap_socket(sock)
conn.connect(("www.google.com", 443))
conn.write(b"GET /\nHost: www.google.com\n\n")
print(conn.read())
```

and command to run it:
```
docker run --rm -it -v `pwd`:/test:ro python:latest /test/test.py
```

## Expected output
Google HTTP response

## Current output
Dropped connection
```
Traceback (most recent call last):
  File "/test/test.py", line 8, in <module>
    conn.connect(("www.google.com", 443))
  File "/usr/lib/python2.7/ssl.py", line 864, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python2.7/ssl.py", line 855, in _real_connect
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
socket.error: [Errno 0] Error
```

## Workaround
Downgrade to 3.2.2

**Comment by jsuchenia** [comment]
Partially the same issue as https://github.com/docker/for-mac/issues/2467 however it could be good to implement a fix in an intercepting-proxy to correctly discover destination IP and pass it to it to allows non-SNI traffic over proxy

**Comment by joual** [comment]
I've lost so much time debugging this. https://stackoverflow.com/questions/67114041/cannot-reach-ssl-ip-when-in-docker-container-over-bridge-getting-ssl-error-sysc 

Thank you @jsuchenia

**Comment by aaronhmiller** [comment]
I see similar behavior re: TLS handshakes failing when calling AWS Lambda thru Docker v 3.3.x

Downgrading to Docker 3.2.x fixed the issue. I've isolated the change to just that.

**Comment by ManuelBauer** [comment]
I get a similar behavior here: An application inside of a Docker container tries to connect to an external service on port 443 to transmit raw binary data (no use of TLS/SSL). Till 3.3.0 everything worked fine. Since the 3.3.0 release the connection is just being terminated as soon as I want to transfer data.

For now I've downgraded to 3.2.2, but it would be great if there is only a http(s) proxy active, when proxy settings are really set 😉

**Comment by timhaak** [comment]
Anyone know of a work around. 

More as 3.2.2 just auto-updated :( back to the broken one.

The ability to prevent auto-update doesn't seem to be available in 3.2.2

**Comment by arbaadrian** [comment]
This issue has been bugging us as well, code that was working in a container on DD for Mac 3.2.2 now failing with an ambiguous error in DD 3.3.0/3.3.1

The container has some python code that uses boto to retrieve a SAML assertion, and it fails when attempting to connect to the AWS api:

`from boto import sts as botosts

(...)
def assert_roles(region, role_arn, principal_arn, assertion, duration_seconds, privileges_type):
    conn = botosts.connect_to_region(region)
    token = conn.assume_role_with_saml(role_arn, principal_arn, assertion, duration_seconds=duration_seconds)`

The workaround, currently, was to downgrade to DD for Mac 3.2.2.

Error reported by script:
`(...)
  File "/usr/local/lib/python3.8/ssl.py", line 1405, in wrap_socket
    return context.wrap_socket(
  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error`

**Comment by embano1** [comment]
Oh man, I spend a couple of hours figuring out what's going on, until I gave up an downgraded again...

**Comment by nuttmeister** [comment]
Yeah, any workaround for this? Because the preview builds for M1 is not available for download.
Or anyone have a download link? Can't wait anymore to get some actual work done... Can't assume a role with aws cli at the moment.

**Comment by mimek** [comment]
I'm using currently: https://desktop.docker.com/mac/stable/arm64/60984/Docker.dmg which is 3.1.0 PREVIEW without auto-update feature. Connection from container to AWS endpoints seems to be working for me

**Comment by nuttmeister** [comment]
@mimek getting 403 forbidden from the URL so no luck. Would be nice if the Docker team could provide links for the previous preview builds that actually work since these are quite broken for many.

**Comment by embano1** [comment]
> @mimek getting 403 forbidden from the URL so no luck. Would be nice if the Docker team could provide links for the previous preview builds that actually work since these are quite broken for many.

If it helps, I downgraded using one of the links (and working binaries) provided here: https://docs.docker.com/docker-for-mac/release-notes/

**Comment by nuttmeister** [comment]
@embano1 thats what my co-workers with Intel also did. But they didn't keep links to any of the AS preview / RC builds.
So if you're on AS you're out of luck basically.

Have no idea why they scrubbed the internet so hard of the preview builds. Haha.

**Comment by nuttmeister** [comment]
Got a tip from another co-worker that works in bypassing the broken forced proxy.
Running with "--net host" works. So anyone else stuck with M1 can do that.

**Comment by hendyp** [comment]
I think I encountered this or a similar problem as well, downgrade of Docker for macOS to 3.2.2 fixed it for me.

I was building an nginx proxy configuration with an HTTPS upstream, using an internal IP address, but should be using SNI. When accessing the proxied address I got the following error message from nginx, but I could never track any corresponding TCP packets, neither on my machine nor on the upstream:

```
2021/04/26 08:26:48 [error] 37#37: *3 peer closed connection in SSL handshake while SSL handshaking to upstream, client: 172.17.0.1, server: _, request: "GET /some/path HTTP/1.1", upstream: "https://10.85.82.76:443/some/other/path", host: "localhost:8088"
```

After reading this thread I discovered that Docker's proxy settings have different ports for HTTPS when you compare 3.3.1 and 3.2.0:
```
# 3.3.1
$ docker info | grep -i proxy
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128

# 3.2.0
$ docker info | grep -i proxy
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
```
So my wild guess is, maybe my nginx is trying to connect with TLS to a port not supporting TLS?

**Comment by tomwoods** [comment]
I ran into the same issue after upgrading on OSX. Finally was able to fix by going to Resources > Proxies and turn off Manual proxy configuration, that for some reason had an override for Secure Web Server to 444.

After turning off and restarting, it worked.

**Comment by rkrv** [comment]
My team has Manual Proxy Configuration disabled, we are having difficulties connecting to local secure domains, getting the following error:

```
nginx-gateway | 2021/04/27 08:45:01 [warn] 14#14: *9 upstream server temporarily disabled while SSL handshaking to upstream, client: <redacted IP>, server: <empty string>, request: "GET /api/endpoint?per_page=20 HTTP/1.1", upstream: "https://<IP>:443/endpoint?per_page=20", host: "localhost.local", referrer: "https://localhost.local/"
```

Worked until we upgraded to Docker for Desktop OSX 3.3.1

**Comment by HunsonlAbadeer** [comment]
I dont know, if it`s the same. But looks familiar,  with new docker for mac 3.3.1. Nginx ssl proxy, started to throw this warning:
`nginx-dev_1                           | 2021/04/26 15:25:23 [info] 1#1: *230 client sent plain HTTP request to HTTPS port while reading client request headers, client: 10.254.1.1, server: , request: "GET / HTTP/1.1", host: "example.com:8000"`

We don`t use docker proxy. 

Downgrading to 3.2. Solves the issue

**Comment by sshishov** [comment]
Guys, how the stable release for a tool like `Docker`, which is used by millions of people, can have such a BLOCKER issue? Everyone is having SSL problems here and there. This is not an alpha/beta/edge release even? How you are testing it on your end?
Moreover the issue has been created more than 2 weeks ago and the fix for P1 issue is not released yet even. Frustrating...

**Comment by rkrv** [comment]
Seems to work in 3.3.2

**Comment by gkontokotsios** [comment]
> Seems to work in 3.3.2

When did v3.3.2 get released? I just had to downgrade to v3.2.2 about 1h ago because I couldn't find any other solution...

**Comment by rkrv** [comment]
Just a few hours earlier https://docs.docker.com/docker-for-mac/release-notes/#docker-desktop-332

**Comment by gkontokotsios** [comment]
> Just a few hours earlier https://docs.docker.com/docker-for-mac/release-notes/#docker-desktop-332

These are some really good news! 🎉
Thanks!

**Comment by caguro** [comment]
> Got a tip from another co-worker that works in bypassing the broken forced proxy.
> Running with "--net host" works. So anyone else stuck with M1 can do that.

Thanks for that suggestion!

Just spent 3 days trying to troubleshoot my ssltest.sh setup as I didn't receive sane answers when testing our web sites with new SSL/TLS settings.
Yesterday when i tested the exact same container on Linux it just worked. Not until then I understood that there is something wrong with DD.

Annoying.

**Comment by jsuchenia** [comment]
Yes, fixed

**Comment by sshishov** [comment]
Thank you for fixing it. Very appreciated!
