### ISSUE TITLE
[3.3.1 (63152)] com.docker.backend high CPU usage after upgrade

### ISSUE THREAD

**Issue by aspacca** [docker/for-mac#5586]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
 There are no instructions for uploading Diagnostics, and I cannot see a button's location obviously in the GUI.

### Expected behavior
"Normal" CPU usage (I have no metrics to compare to since before this huge spike in CPU usage after the latest upgrade I didn't check what was the normal one)

### Actual behavior
`com.docker.backend` process shows between 320% and 340% CPU usage on Activity Monitor after upgrade to 3.3.1 (63152)

### Information

  - macOS Version: 10.15.7 (19H524)
  - Intel chip or Apple chip: Intel Chip
  - Docker Desktop Version: 3.3.1 (63152)

### Steps to reproduce the behavior

The following stack trace appears every second in `~/Library/Containers/com.docker.docker/Data/log/host/com.docker.backend.log`

```
goroutine 3210 [running]:
github.com/docker/pinata/common/pkg/dns.lookupOne(0x58a4098, 0xc00012e008, 0x584f072, 0x1, 0xc0009f0006, 0xc0002e2800, 0x2, 0x58708c0, 0xc0008c7e90, 0x58708c0)
	/Users/administrator/jenkins/workspace/desktop_desktop-build_master/src/github.com/docker/pinata/common/pkg/dns/lookup_darwin.go:26 +0x20e
github.com/docker/pinata/common/pkg/dns.doLookup(0x58a4098, 0xc00012e008, 0x584f072, 0x1, 0x6, 0xc0009f5b40, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/administrator/jenkins/workspace/desktop_desktop-build_master/src/github.com/docker/pinata/common/pkg/dns/lookup.go:90 +0x21a
github.com/docker/pinata/common/pkg/dns.distinguishNodataNxdomain(0x58a4098, 0xc00012e008, 0x584f072, 0x1, 0xc0009f5b40, 0xc0009f5b40, 0x0, 0x0, 0x0, 0x58708c0)
	/Users/administrator/jenkins/workspace/desktop_desktop-build_master/src/github.com/docker/pinata/common/pkg/dns/lookup.go:58 +0x67
github.com/docker/pinata/common/pkg/dns.lookup(0x58a4098, 0xc00012e008, 0x584f072, 0x1, 0x2, 0xc000b96480, 0x0, 0xc0009f5c78, 0x40528ac, 0x18)
	/Users/administrator/jenkins/workspace/desktop_desktop-build_master/src/github.com/docker/pinata/common/pkg/dns/lookup.go:53 +0x138
github.com/docker/pinata/common/pkg/dns.(*SystemResolver).Answer(0x65613e8, 0x584f072, 0x1, 0xc000010002, 0x0, 0x0, 0x0, 0x586e920, 0xc0005b2798)
	/Users/administrator/jenkins/workspace/desktop_desktop-build_master/src/github.com/docker/pinata/common/pkg/dns/system.go:20 +0x172
github.com/docker/pinata/common/pkg/dns.createReply(0xc00068f3a0, 0x2, 0x2, 0xc000552900, 0x584f072)
	/Users/administrator/jenkins/workspace/desktop_desktop-build_master/src/github.com/docker/pinata/common/pkg/dns/server.go:164 +0x23d
github.com/docker/pinata/common/pkg/dns.NewServer.func1(0x58b5560, 0xc00099ad80, 0xc000552900)
	/Users/administrator/jenkins/workspace/desktop_desktop-build_master/src/github.com/docker/pinata/common/pkg/dns/server.go:35 +0x4a
github.com/miekg/dns.HandlerFunc.ServeDNS(0xc00068f3e0, 0x58b5560, 0xc00099ad80, 0xc000552900)
	/Users/administrator/jenkins/workspace/desktop_desktop-build_master/src/github.com/docker/pinata/vendor/github.com/miekg/dns/server.go:37 +0x44
github.com/miekg/dns.(*ServeMux).ServeDNS(0xc00068f3c0, 0x58b5560, 0xc00099ad80, 0xc000552900)
	/Users/administrator/jenkins/workspace/desktop_desktop-build_master/src/github.com/docker/pinata/vendor/github.com/miekg/dns/serve_mux.go:103 +0x5d
github.com/miekg/dns.(*Server).serveDNS(0xc00098ea20, 0xc0002a1e00, 0x11, 0x200, 0xc00099ad80)
	/Users/administrator/jenkins/workspace/desktop_desktop-build_master/src/github.com/docker/pinata/vendor/github.com/miekg/dns/server.go:650 +0x2fd
github.com/miekg/dns.(*Server).serveUDPPacket(0xc00098ea20, 0xc00040cf00, 0xc0002a1e00, 0x11, 0x200, 0x58b2238, 0xc000996700, 0x0, 0x587cd40, 0xc000a06e40)
	/Users/administrator/jenkins/workspace/desktop_desktop-build_master/src/github.com/docker/pinata/vendor/github.com/miekg/dns/server.go:590 +0xed
created by github.com/miekg/dns.(*Server).serveUDP
	/Users/administrator/jenkins/workspace/desktop_desktop-build_master/src/github.com/docker/pinata/vendor/github.com/miekg/dns/server.go:520 +0x395
time="2021-04-16T14:58:43+02:00" level=error msg="unexpected error from dnssd: Bad Param (-65540)"
```

**Comment by danielporto** [comment]
I noticed the same thing on my Mac m1.

**Comment by stephen-turner** [comment]
What files are you sharing into containers? The most common cause of excessive CPU is sharing too many files, for example if you share the whole of their home directory. Unlike on Linux, where all containers have direct access to the file system, on Mac the files have to be shared into the VM that is running the containers, which is an inherently expensive operation. We have some tips in the documentation (https://docs.docker.com/docker-for-mac/#resources) about ways to reduce the load, including sharing only the files/directories you need to, and using named volumes instead of bind mounts for things like databases. For certain write-heavy workloads, switching from grpcfuse to osxfs in the preferences may also help.

PS There are instructions for uploading diagnostics in the issue template that you filled in.

**Comment by aspacca** [comment]
@stephen-turner I haven't changed anything between previous version and after the upgrade. the issue started after the upgrade. I tried both GRPC Fuse sharing enabled/disabled, with no difference in CPU usage

Disabling all sharings seems to resolve the problem of CPU usage on `com.docker.backend`, but now it is `com.docker.hyperkit` up to 175%

There's no containers (stopped or running), neither volumes.

I found the instruction for the diagnostics: but I cannot find a way to uplod them only after checking what's collected.

**Comment by aspacca** [comment]
Diagnostics data reports too much content (including my mac serial number, firewall statuses, launch agents etc) for me to be confident to share

**Comment by harrouet** [comment]
I guess this is a duplicate for #5507  and #5137. 
Docker not starting as `com.docker.backend` enters what seem like an infinite loop and eats up all the CPU.

**Comment by danielporto** [comment]
Is there a workaround? How can we downgrade it while the issue is fixed? The old dmg is not really easy to find in the docker website.

**Comment by harrouet** [comment]
Not sure. In my case the “Docker not starting” issue has been here for 6 months, while the `com.docker.backend` eating all the CPU issue has disappeared in the latest version.

**Comment by danielporto** [comment]
I've reset docker to factory settings. Rebooted and it stopped eating up the CPU.

**Comment by denisbabineau** [comment]
@stephen-turner diagnostic ID: 4F10A3B4-D763-4946-B062-0FF6F56B0740/20210428130855

In my case hyperkit pins all 4 cores (%400 cpu) most frequently when using the devilbox lamp stack and seems to be most aggravated when I'm running the mysql container although the db is using a named volume. It sometimes comes down from full %400 as if something stopped but typically remains in the 100%-300% range regardless. The diagnostic was in progress during the %400 period and briefly came down slightly near the end. The environment is virtually unusable.

**Comment by aspacca** [comment]
I've uninstalled and reinstalled docker and the problem in my case is related to enabling k8s

**Comment by c3-grant-gasser** [comment]
@stephen-turner This may be a rudimentary question but how do we know which files/directories we're _using_? Here are the files/directories I'm sharing, not sure which ones I can safely remove (already tried removing /var/folders). 

<img width="654" alt="Screen Shot 2021-06-17 at 1 20 10 PM" src="https://user-images.githubusercontent.com/82407008/122467058-e4fbee00-cf6e-11eb-8a8d-15a05c9fd53b.png">


Originally unchecking gprc fuse temporarily resolved the issue for me but now its back to ~200-400% usage. Been a big problem for me. I've tried most other tricks listed in the series of issues for this.

I downloaded my image via `docker-compose.yml` which has
```
volumes:
  - ./mount-....
  - ./mount-...
  
  # and a few more mounts ...
```
