### ISSUE TITLE
Update on 3.3.1 Failed 

### ISSUE THREAD

**Issue by devilmind81** [docker/for-mac#5605]
Hi All,
I'm using windows 10 and since today I used Docker Desktop 3.2.2.
Today morning I have accepted the Docker Desktop update to 3.3.1.
At the end of installation I obtain the error:

```
Failed to finish background job: The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
```

Docker seems not be installed and I cannot reinstall a previous versions.
If I try to reinstall the 3.2.2 I'm obtaining:

```
Failed to register product: The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
```

The is 2.5.0 installation works but docker not starting, i see the try icon for 10 sec and disappear why?

The informations here https://github.com/docker/for-win/issues/9758 not solved till now.

Please help me.

**Comment by 89z** [comment]
https://github.com/docker/for-mac/issues/5605
https://github.com/docker/for-win/issues/9758
https://github.com/docker/for-win/issues/9780
