### ISSUE TITLE
qemu: uncaught target signal 6 (Aborted) - core dumped on Apple Silicon M1 arm64

### ISSUE THREAD

**Issue by richardsondx** [docker/for-mac#5705]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

When I run `docker-compose up` and the command `bundle install` is ran it should be successfull

### Actual behavior

```
 > [5/6] RUN bundle install --jobs 4 --path .bundle/:
#10 4.104 Fetching gem metadata from https://rubygems.org/./usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.17.1/lib/bundler/worker.rb:90: [BUG] Segmentation fault at 0x00004318cbf428
#10 4.110 ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]
#10 4.110
#10 4.111 SEGV received in SEGV handler
#10 4.111 -- Control frame information -----------------------------------------------
#10 4.111 SEGV received in SEGV handler
#10 4.111 qemu: uncaught target signal 6 (Aborted) - core dumped
#10 4.125 Aborted
```

I was able to go around this bug by updating my adding the following line to my dockerfile

```
FROM ruby:2.3.4
```

but it didn't resolve the original issue and I wasn't truly able to diagnostic it properly either.

Backtrace:
```
#11 4.084 [BUG] Segmentation fault at 0x0000418d41e2a0
#11 4.085 ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]
#11 4.085
#11 4.085 -- Control frame information -----------------------------------------------
#11 4.086 c:0006 p:---- s:0017 e:000016 CFUNC  :pop
#11 4.087 c:0005 p:0010 s:0014 e:000013 BLOCK  /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/worker.rb:55 [FINISH]
#11 4.088 c:0004 p:---- s:0011 e:000010 CFUNC  :loop
#11 4.089 c:0003 p:0009 s:0008 e:000007 METHOD /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/worker.rb:54
#11 4.089 c:0002 p:0010 s:0004 e:000003 BLOCK  /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/worker.rb:88 [FINISH]
#11 4.090 c:0001 p:---- s:0002 e:000001 (none) [FINISH]
#11 4.090
#11 4.090 -- Ruby level backtrace information ----------------------------------------
#11 4.090 /usr/local/bin/bundle:22:in `<main>'
#11 4.090 /usr/local/bin/bundle:22:in `load'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/exe/bundle:37:in `<top (required)>'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/exe/bundle:49:in `block in <top (required)>'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/cli.rb:24:in `start'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/cli.rb:30:in `dispatch'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/cli.rb:258:in `install'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/settings.rb:134:in `temporary'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/cli.rb:259:in `block in install'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/cli/install.rb:64:in `run'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/installer.rb:24:in `install'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/installer.rb:72:in `run'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/process_lock.rb:9:in `lock'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/process_lock.rb:9:in `open'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/process_lock.rb:12:in `block in lock'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/installer.rb:84:in `block in run'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/installer.rb:254:in `ensure_specs_are_compatible!'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/definition.rb:183:in `specs'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/spec_set.rb:82:in `materialize'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/spec_set.rb:82:in `each'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/spec_set.rb:87:in `block in materialize'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/source/rubygems.rb:293:in `double_check_for'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/source/rubygems.rb:424:in `fetch_names'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/source/rubygems.rb:424:in `each'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/source/rubygems.rb:427:in `block in fetch_names'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/fetcher.rb:117:in `specs_with_retry'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/retry.rb:30:in `attempt'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/retry.rb:40:in `run'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/fetcher.rb:118:in `block in specs_with_retry'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/fetcher.rb:133:in `specs'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/fetcher.rb:133:in `each'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/fetcher.rb:134:in `block in specs'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/fetcher/compact_index.rb:16:in `block in compact_index_request'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/fetcher/compact_index.rb:16:in `call'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/fetcher/compact_index.rb:30:in `specs'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/fetcher/compact_index.rb:43:in `specs_for_names'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/compact_index_client.rb:70:in `dependencies'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/fetcher/compact_index.rb:99:in `block in parallel_compact_index_client'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/fetcher/compact_index.rb:99:in `each'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/fetcher/compact_index.rb:99:in `block (2 levels) in parallel_compact_index_client'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/worker.rb:36:in `enq'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/worker.rb:86:in `create_threads'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/worker.rb:86:in `new'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/worker.rb:86:in `initialize'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/worker.rb:88:in `block in create_threads'
#11 4.091 /usr/local/bundle/gems/bundler-2.2.17/lib/bundler/worker.rb:88:in `start'
#11 4.091
#11 4.091 -- Machine register context ------------------------------------------------
#11 4.092  RIP: 0x000000400215b1ca RBP: 0x0000000000000002 RSP: 0x000000401e398d50
#11 4.092  RAX: 0x000000002e382e2f RBX: 0x0000000000000020 RCX: 0x0000000000000024
#11 4.092  RDX: 0x000000401b807128 RDI: 0x000000401e399a20 RSI: 0x000000401e3996f8
#11 4.092   R8: 0x0000004003400000  R9: 0x000000401e398460 R10: 0x000000401e398410
#11 4.092  R11: 0x00000040034126c8 R12: 0x0000000000000020 R13: 0x000000400238a7a0
#11 4.092  R14: 0x000000401b806000 R15: 0x0000000000000020 EFL: 0x0000000000000202
#11 4.092
#11 4.092 -- C level backtrace information -------------------------------------------
#11 4.092 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
#11 4.105 Segmentation fault
```

### Information

* Macbook Pro M1 2020
* Mac OS Big Sur 11.2.3
* docker-compose version 1.29.1
* docker engine: 20.10.6
* docker desktop 3.3.3(64133)

### Steps to reproduce the behavior

According to these two links Docker Desktop comes packaged with QEMU.
- https://www.docker.com/blog/multi-arch-images/ 
- https://github.com/docker/for-mac/issues/5148#issuecomment-784992663
but I wasn't able to either get the QEMU version, do some debugging, or update its settings. Docker Desktop doesn't provide a lot of ways to diagnose what's happening with the component that are included in Docker Desktop. It'll be helpful if we could:
- 1) Change the QEMU configuration ourselves by passing our own config
- 2) View the actual logging the QEMU CLI returns ( or a verbose mode)
- 3) the ability to interact with those component by running for example:  `coredumpctl debug`

I reached out to the QEMU team about this issue as well  and they provided additional information and suggestion to the Docker team:
https://gitlab.com/qemu-project/qemu/-/issues/340#note_579882436

**Comment by j16sdiz** [comment]
The qemu-user is 5.0.1 , not 5.2.0 ..
The 5.2 is the host qemu

# /containers/services/binfmt/rootfs/usr/bin/qemu-x86_64 --version
qemu-x86_64 version 5.0.1 (cpu-set-max-5.0.1)
Copyright (c) 2003-2020 Fabrice Bellard and the QEMU Project developers

**Comment by j16sdiz** [comment]
The host Qemu is much newer:
```
$ /Applications/Docker.app/Contents/MacOS/qemu-system-aarch64 --version
QEMU emulator version 5.2.0 (v5.2.0-11-ge7395802aa)
Copyright (c) 2003-2020 Fabrice Bellard and the QEMU Project developers
```
