### ISSUE TITLE
Segmentation fault openssl docker m1

### ISSUE THREAD

**Issue by bsiguret** [docker/for-mac#5866]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `15698293-8A64-43D3-814A-5992F7F1AF89/20210721143735`

### Information
  - macOS Version: macOS Big Sur 11.4
  - Intel chip or Apple chip: Apple Chip
  - Docker Desktop Version: Version 3.5.2 (3.5.2.18)
  
  Hello, sorry in advance if it's totally not in here that i should make an issue but i don't really now where to begin anyway.

I'm running a rails backend in docker on a `macOS BigSur 11.4 M1 Chip` to make it easier to run the backend for us, humble frontend dev 😄 . At a certain point in our application, our backend use firebase (https://firebase.google.com/) and I got a segfault.

Note that I've also a Mac intel and everything works fine with the same environment (the only difference is the Intel Chip). I've tried a lot of thing here and there without success. I'm now forced to work on my mac intel due to this bug who appeared without anything but a new `docker-compose up --build --remove-orphans`. 

Note also that, I've a colleague who got a Mac M1 too without the problem I'm facing - but I don't know his env. Is this an openssl or docker problem or something else ? Feel free to redirect me to the right problem. I'm running out of ideas to solve this problem, except to wait for updates to hope that it resolves itself, since I didn't have it like a week or two.

Dockerfile :
- `FROM ruby:2.6.6`
- `ENV BUNDLER_VERSION 2.1.4`

The only thing i figured is that it might be a docker m1 problem (?) since i don't have it on my mac intel nor an image problem (?). I even reinstalled my whole OS and everything else to see if the problem persisted - spoiler, it does.

```
/usr/local/lib/ruby/2.6.0/openssl/buffering.rb:322: [BUG] Segmentation fault at 0x0020ffffb46f567c
ruby 2.6.6p146 (2020-03-31 revision 67876) [aarch64-linux]

-- Control frame information -----------------------------------------------
c:0054 p:---- s:0343 e:000342 CFUNC  :syswrite
c:0053 p:0094 s:0338 e:000337 METHOD /usr/local/lib/ruby/2.6.0/openssl/buffering.rb:322
c:0052 p:0007 s:0332 e:000331 BLOCK  /usr/local/lib/ruby/2.6.0/openssl/buffering.rb:339 [FINISH]
c:0051 p:---- s:0327 e:000326 IFUNC
c:0050 p:---- s:0324 e:000323 CFUNC  :each
c:0049 p:---- s:0321 e:000320 CFUNC  :inject
c:0048 p:0007 s:0316 e:000315 METHOD /usr/local/lib/ruby/2.6.0/openssl/buffering.rb:338
c:0047 p:0008 s:0311 e:000310 METHOD /usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:80
c:0046 p:0109 s:0305 e:000304 METHOD /usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient/http.rb:510
c:0045 p:0059 s:0299 e:000298 METHOD /usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient/http.rb:962
c:0044 p:0016 s:0293 e:000292 BLOCK  /usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient/session.rb:517
c:0043 p:0031 s:0290 E:002468 BLOCK  /usr/local/lib/ruby/2.6.0/timeout.rb:93
c:0042 p:0098 s:0284 E:0023f0 METHOD /usr/local/lib/ruby/2.6.0/timeout.rb:103
c:0041 p:0071 s:0272 E:000ed0 METHOD /usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient/session.rb:515
c:0040 p:0036 s:0266 e:000265 METHOD /usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient/session.rb:177
c:0039 p:0129 s:0259 e:000258 METHOD /usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient.rb:1242
c:0038 p:0027 s:0246 e:000245 BLOCK  /usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient.rb:1019
c:0037 p:0002 s:0242 e:000241 METHOD /usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient.rb:1133
c:0036 p:0117 s:0238 e:000237 METHOD /usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient.rb:1014
c:0035 p:0100 s:0220 e:000219 METHOD /usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient.rb:1104
c:0034 p:0110 s:0203 e:000202 METHOD /usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient.rb:854
c:0033 p:0186 s:0190 e:000188 METHOD /usr/local/bundle/gems/firebase-0.2.8/lib/firebase.rb:78
c:0032 p:0016 s:0181 e:000180 METHOD /usr/local/bundle/gems/firebase-0.2.8/lib/firebase.rb:51
c:0031 p:0010 s:0174 e:000173 EVAL   (pry):2 [FINISH]
c:0030 p:---- s:0171 e:000170 CFUNC  :eval
c:0029 p:0044 s:0164 e:000163 METHOD /usr/local/bundle/gems/pry-0.13.1/lib/pry/pry_instance.rb:290
c:0028 p:0251 s:0158 e:000157 METHOD /usr/local/bundle/gems/pry-0.13.1/lib/pry/pry_instance.rb:659
c:0027 p:0011 s:0147 e:000146 BLOCK  /usr/local/bundle/gems/pry-0.13.1/lib/pry/pry_instance.rb:261 [FINISH]
c:0026 p:---- s:0144 e:000143 CFUNC  :catch
c:0025 p:0008 s:0139 e:000138 BLOCK  /usr/local/bundle/gems/pry-0.13.1/lib/pry/pry_instance.rb:260 [FINISH]
c:0024 p:---- s:0136 e:000135 CFUNC  :catch
c:0023 p:0022 s:0131 e:000130 METHOD /usr/local/bundle/gems/pry-0.13.1/lib/pry/pry_instance.rb:259
c:0022 p:0062 s:0123 e:000122 BLOCK  /usr/local/bundle/gems/pry-0.13.1/lib/pry/repl.rb:77 [FINISH]
c:0021 p:---- s:0119 e:000118 CFUNC  :loop
c:0020 p:0005 s:0115 e:000114 METHOD /usr/local/bundle/gems/pry-0.13.1/lib/pry/repl.rb:67
c:0019 p:0005 s:0111 e:000110 BLOCK  /usr/local/bundle/gems/pry-0.13.1/lib/pry/repl.rb:38
c:0018 p:0011 s:0108 e:000107 METHOD /usr/local/bundle/gems/pry-0.13.1/lib/pry/input_lock.rb:61
c:0017 p:0025 s:0104 e:000103 METHOD /usr/local/bundle/gems/pry-0.13.1/lib/pry/input_lock.rb:78
c:0016 p:0023 s:0098 e:000097 METHOD /usr/local/bundle/gems/pry-0.13.1/lib/pry/repl.rb:38
c:0015 p:0019 s:0094 e:000093 METHOD /usr/local/bundle/gems/pry-0.13.1/lib/pry/repl.rb:15
c:0014 p:0202 s:0089 e:000088 METHOD /usr/local/bundle/gems/pry-0.13.1/lib/pry/pry_class.rb:191
c:0013 p:0078 s:0082 e:000081 METHOD /usr/local/bundle/gems/pry-byebug-3.9.0/lib/pry-byebug/pry_ext.rb:13
c:0012 p:0182 s:0076 e:000075 METHOD /usr/local/bundle/gems/railties-5.2.4.6/lib/rails/commands/console/console_command.rb:64
c:0011 p:0011 s:0072 e:000071 METHOD /usr/local/bundle/gems/railties-5.2.4.6/lib/rails/commands/console/console_command.rb:19
c:0010 p:0058 s:0067 e:000066 METHOD /usr/local/bundle/gems/railties-5.2.4.6/lib/rails/commands/console/console_command.rb:96
c:0009 p:0064 s:0063 e:000062 METHOD /usr/local/bundle/gems/thor-1.1.0/lib/thor/command.rb:27
c:0008 p:0047 s:0055 e:000054 METHOD /usr/local/bundle/gems/thor-1.1.0/lib/thor/invocation.rb:127
c:0007 p:0259 s:0048 e:000047 METHOD /usr/local/bundle/gems/thor-1.1.0/lib/thor.rb:392
c:0006 p:0043 s:0035 e:000034 METHOD /usr/local/bundle/gems/railties-5.2.4.6/lib/rails/command/base.rb:69
c:0005 p:0130 s:0028 e:000027 METHOD /usr/local/bundle/gems/railties-5.2.4.6/lib/rails/command.rb:46
c:0004 p:0059 s:0017 e:000016 TOP    /usr/local/bundle/gems/railties-5.2.4.6/lib/rails/commands.rb:18 [FINISH]
c:0003 p:---- s:0012 e:000011 CFUNC  :require
c:0002 p:0053 s:0007 E:001068 EVAL   bin/rails:9 [FINISH]
c:0001 p:0000 s:0003 E:001fa0 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
bin/rails:9:in `<main>'
bin/rails:9:in `require'
/usr/local/bundle/gems/railties-5.2.4.6/lib/rails/commands.rb:18:in `<top (required)>'
/usr/local/bundle/gems/railties-5.2.4.6/lib/rails/command.rb:46:in `invoke'
/usr/local/bundle/gems/railties-5.2.4.6/lib/rails/command/base.rb:69:in `perform'
/usr/local/bundle/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/railties-5.2.4.6/lib/rails/commands/console/console_command.rb:96:in `perform'
/usr/local/bundle/gems/railties-5.2.4.6/lib/rails/commands/console/console_command.rb:19:in `start'
/usr/local/bundle/gems/railties-5.2.4.6/lib/rails/commands/console/console_command.rb:64:in `start'
/usr/local/bundle/gems/pry-byebug-3.9.0/lib/pry-byebug/pry_ext.rb:13:in `start_with_pry_byebug'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/pry_class.rb:191:in `start'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/repl.rb:15:in `start'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/repl.rb:38:in `start'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/input_lock.rb:78:in `with_ownership'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/input_lock.rb:61:in `__with_ownership'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/repl.rb:38:in `block in start'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/repl.rb:67:in `repl'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/repl.rb:67:in `loop'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/repl.rb:77:in `block in repl'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/pry_instance.rb:259:in `eval'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/pry_instance.rb:259:in `catch'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/pry_instance.rb:260:in `block in eval'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/pry_instance.rb:260:in `catch'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/pry_instance.rb:261:in `block (2 levels) in eval'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/pry_instance.rb:659:in `handle_line'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/pry_instance.rb:290:in `evaluate_ruby'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/pry_instance.rb:290:in `eval'
(pry):2:in `<main>'
/usr/local/bundle/gems/firebase-0.2.8/lib/firebase.rb:51:in `push'
/usr/local/bundle/gems/firebase-0.2.8/lib/firebase.rb:78:in `process'
/usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient.rb:854:in `request'
/usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient.rb:1104:in `follow_redirect'
/usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
/usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
/usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
/usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
/usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
/usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient/session.rb:515:in `query'
/usr/local/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
/usr/local/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient/session.rb:517:in `block in query'
/usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient/http.rb:962:in `dump'
/usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient/http.rb:510:in `dump'
/usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:80:in `<<'
/usr/local/lib/ruby/2.6.0/openssl/buffering.rb:338:in `write'
/usr/local/lib/ruby/2.6.0/openssl/buffering.rb:338:in `inject'
/usr/local/lib/ruby/2.6.0/openssl/buffering.rb:338:in `each'
/usr/local/lib/ruby/2.6.0/openssl/buffering.rb:339:in `block in write'
/usr/local/lib/ruby/2.6.0/openssl/buffering.rb:322:in `do_write'
/usr/local/lib/ruby/2.6.0/openssl/buffering.rb:322:in `syswrite'

-- C level backtrace information -------------------------------------------
```

**Comment by stephen-turner** [comment]
I wonder if you're hitting the libssl bug described at https://docs.docker.com/docker-for-mac/release-notes/#known-issues

**Comment by bsiguret** [comment]
![image](https://user-images.githubusercontent.com/30038522/126611246-35e0b382-309d-463a-bed3-642858efd3d8.png)

@stephen-turner Well, bullseye. Is there a known fix for that problem ? Thanks

**Comment by bsiguret** [comment]
We seems to use `debian:buster` as mentionned in the known issue. I'll see how to upgrade to `debian:bulleye`
