### ISSUE TITLE
Ctrl-C'ing `docker-compose logs --follow` throws an exception

### ISSUE THREAD

**Issue by coredumperror** [docker/for-mac#5880]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 8FD1A2F4-8BFA-480D-9BF3-B6025BEC6103/20210727000249

### Expected behavior
When I hit Ctrl-C to kill `docker-compose logs --follow`, I expect it to cleanly exit.

### Actual behavior
Hitting Ctrl-C causes the following traceback to appear before the program exits:

```
^CTraceback (most recent call last):
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 731, in logs
  File "compose/cli/log_printer.py", line 88, in run
  File "compose/cli/log_printer.py", line 241, in consume_queue
  File "queue.py", line 180, in get
  File "threading.py", line 316, in wait
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 85, in main
  File "compose/cli/main.py", line 145, in exit_with_metrics
  File "logging/__init__.py", line 1463, in error
  File "logging/__init__.py", line 1565, in _log
  File "logging/__init__.py", line 1521, in findCaller
  File "posixpath.py", line 54, in normcase
KeyboardInterrupt
[14045] Failed to execute script docker-compose
```

### Information
This has been happening since I updated to the version of Docker For Mac that introduced `docker compose`, as a replacement for `docker-compose`. However, this issue affects only the older `docker-compose` command.

I would be more than happy to just use `docker compose logs --follow` to get around this, but for unknown reasons, the text colors are all lost when I run the output of that through `grep`, which I used to filter a bunch of log lines that I don't care to see. `grep` _doesn't_ break the colors when I use `docker-compose`.

  - macOS Version: 11.4 (Big Sur)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.5.2

### Steps to reproduce the behavior
1. Start a Docker network.
2. Run `docker-compose logs --follow`
3. Hit Ctrl-C.

**Comment by coredumperror** [comment]
I dunno what that "version/11.4" label is about. This issue is for Docker for Mac v3.5.2.
