### ISSUE TITLE
Docker Desktop quit unexpectedly

### ISSUE THREAD

**Issue by bgold0** [docker/for-mac#6051]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: There is no way to get one

### Expected behavior
Docker run successfully

### Actual behavior
When clicking on the docker it brings up the following image
![Screen Shot 2021-11-17 at 5 27 45 PM](https://user-images.githubusercontent.com/52385564/142292582-7713a470-8203-4431-84d1-d5b37018ae8d.png)

### Information

  - macOS Version: 12.0.1 (21A559)
  - Intel chip or Apple chip: Apple chip
  - Docker Desktop Version: Downloaded on Nov, 17 2021 from docker website (cannot view version)

### Steps to reproduce the behavior

  1. Download docker desktop for new m1 laptops
  2. Run docker desktop
  3. See error show up

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: 17680B81-6AA5-4B52-87E9-F517B36FB86B
CrashReporter Key:   ECE9DECE-964E-1355-BAB9-7FAC01393CA4
Hardware Model:      MacBookAir10,1
Process:             Docker Desktop [98008]
Path:                /Applications/Docker.app/Contents/MacOS/Docker Desktop.app/Contents/MacOS/Docker Desktop
Identifier:          com.electron.dockerdesktop
Version:             4.2.0 (4.2.0.5815)
Code Type:           X86-64 (Native)
Role:                Unspecified
Parent Process:      Docker [97974]
Coalition:           com.docker.docker [36956]
Responsible Process: Docker [97974]

Date/Time:           2021-11-17 17:17:27.2168 -0500
Launch Time:         2021-11-17 17:17:27.1199 -0500
OS Version:          macOS 12.0.1 (21A559)
Release Type:        User
Report Version:      104

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x00007ff7fffa6af8
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: SIGNAL 5 Trace/BPT trap: 5
Terminating Process: exc handler [98008]

Triggered by Thread:  0

Application Specific Information:
rosetta error: /var/db/oah/279281325309952_279281325309952/19114b8c8a4701cacfd1995478c57616246c5b2bbf8a16954b8a0f466f54aa9a/Docker Desktop.aot: attachment of code signature supplement failed: 1


Thread 0 Crashed:
0   runtime                       	    0x7ff7fffa6af8 0x7ff7fff8a000 + 117496
1   runtime                       	    0x7ff7fffa6b40 0x7ff7fff8a000 + 117568
2   runtime                       	    0x7ff7fff9d440 0x7ff7fff8a000 + 78912
3   runtime                       	    0x7ff7fff9e518 0x7ff7fff8a000 + 83224
4   runtime                       	    0x7ff7fff9dc94 0x7ff7fff8a000 + 81044
5   runtime                       	    0x7ff7fff8da80 0x7ff7fff8a000 + 14976
6   ???                           	               0x7 ???


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000003   x2: 0x000000000000003c   x3: 0x000000000000002c
    x4: 0x0000000000000303   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x00007ff7fffc5000   x9: 0x0000000000000000  x10: 0x0000000000000000  x11: 0x00007ff7fffc5951
   x12: 0x0000000000000000  x13: 0x0000000000000000  x14: 0x0000000000000000  x15: 0x00007ff7fffad828
   x16: 0xffffffffffffffe1  x17: 0x00000000ffffffff  x18: 0x000000030945cfeb  x19: 0x00007ff7fffbb2e1
   x20: 0x000000030945d6a0  x21: 0x000000010295f000  x22: 0x0000000000000004  x23: 0x000000010295f000
   x24: 0x0000000000000003  x25: 0x0000000000000001  x26: 0x000000030945cb00  x27: 0x0000000202b2b1b8
   x28: 0x00000003094658d0   fp: 0x000000030945b8e0   lr: 0x00007ff7fffa6af0
    sp: 0x000000030945b8c0   pc: 0x00007ff7fffa6af8 cpsr: 0x60000000
   far: 0x000000030945b8f8  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
    0x7ff7fff8a000 -     0x7ff7fffb9fff runtime (*) <9f5d65be-d8d0-3979-bb05-e651a67e785c> /usr/libexec/rosetta/runtime
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

Error Formulating Crash Report:
dyld_process_snapshot_get_shared_cache failed

EOF

-----------
Full Report
-----------

{"app_name":"Docker Desktop","timestamp":"2021-11-17 17:17:27.00 -0500","app_version":"4.2.0","slice_uuid":"6eaa1236-4641-3734-98cc-d858c59e4ba7","build_version":"4.2.0.5815","platform":0,"bundleID":"com.electron.dockerdesktop","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.0.1 (21A559)","incident_id":"17680B81-6AA5-4B52-87E9-F517B36FB86B","name":"Docker Desktop"}
{
  "uptime" : 230000,
  "procLaunch" : "2021-11-17 17:17:27.1199 -0500",
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookAir10,1",
  "procStartAbsTime" : 5677799451245,
  "coalitionID" : 36956,
  "osVersion" : {
    "train" : "macOS 12.0.1",
    "build" : "21A559",
    "releaseType" : "User"
  },
  "captureTime" : "2021-11-17 17:17:27.2168 -0500",
  "incident" : "17680B81-6AA5-4B52-87E9-F517B36FB86B",
  "bug_type" : "309",
  "pid" : 98008,
  "procExitAbsTime" : 5677800247443,
  "translated" : true,
  "cpuType" : "X86-64",
  "procName" : "Docker Desktop",
  "procPath" : "\/Applications\/Docker.app\/Contents\/MacOS\/Docker Desktop.app\/Contents\/MacOS\/Docker Desktop",
  "bundleInfo" : {"CFBundleShortVersionString":"4.2.0","CFBundleVersion":"4.2.0.5815","CFBundleIdentifier":"com.electron.dockerdesktop"},
  "storeInfo" : {"deviceIdentifierForVendor":"53D80E0B-D107-5E94-95DA-FC6094A0BA4C","thirdParty":true},
  "parentProc" : "Docker",
  "parentPid" : 97974,
  "coalitionName" : "com.docker.docker",
  "crashReporterKey" : "ECE9DECE-964E-1355-BAB9-7FAC01393CA4",
  "responsiblePid" : 97974,
  "responsibleProc" : "Docker",
  "wakeTime" : 464,
  "sleepWakeUUID" : "408CCC0C-6EA8-46B1-82CF-16AA12709EEA",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x00007ff7fffa6af8","rawCodes":[1,140703128251128],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":98008},
  "asi" : {"runtime":["rosetta error: \/var\/db\/oah\/279281325309952_279281325309952\/19114b8c8a4701cacfd1995478c57616246c5b2bbf8a16954b8a0f466f54aa9a\/Docker Desktop.aot: attachment of code signature supplement failed: 1"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":3772198,"threadState":{"x":[{"value":0},{"value":3},{"value":60},{"value":44},{"value":771},{"value":0},{"value":0},{"value":0},{"value":140703128375296},{"value":0},{"value":0},{"value":140703128377681,"symbolLocation":201,"symbol":"__crashreporter_info__"},{"value":0},{"value":0},{"value":0},{"value":140703128279080},{"value":18446744073709551585},{"value":4294967295},{"value":13040472043},{"value":140703128335073},{"value":13040473760},{"value":4338348032},{"value":4},{"value":4338348032},{"value":3},{"value":1},{"value":13040470784},{"value":8635199928,"symbolLocation":0,"symbol":"dyld_all_image_infos"},{"value":13040507088}],"flavor":"ARM_THREAD_STATE64","lr":{"value":140703128251120},"cpsr":{"value":1610612736},"fp":{"value":13040466144},"sp":{"value":13040466112},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":140703128251128,"matchesCrashFrame":1},"far":{"value":13040466168}},"frames":[{"imageOffset":117496,"imageIndex":0},{"imageOffset":117568,"imageIndex":0},{"imageOffset":78912,"imageIndex":0},{"imageOffset":83224,"imageIndex":0},{"imageOffset":81044,"imageIndex":0},{"imageOffset":14976,"imageIndex":0},{"imageOffset":7,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703128133632,
    "size" : 196608,
    "uuid" : "9f5d65be-d8d0-3979-bb05-e651a67e785c",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "vmSummary" : "ReadOnly portion of Libraries: Total=816K resident=0K(0%) swapped_out_or_unallocated=816K(100%)\nWritable regions: Total=21.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=21.3M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                       13.0M        4 \nVM_ALLOCATE (reserved)             256K        1         reserved VM address space (unallocated)\n__DATA                              80K        3 \n__DATA_CONST                        48K        1 \n__LINKEDIT                         240K        4 \n__TEXT                             624K        2 \nmapped file                        5.9G       27 \n===========                     =======  ======= \nTOTAL                              6.0G       44 \nTOTAL, minus reserved VM space     6.0G       44 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 250000063
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 250000007
    },
    {
      "rolloutId" : "60356660bbe37970735c5624",
      "factorPackIds" : {

      },
      "deploymentId" : 250000016
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "60ef663fa2f864203caf575c"
      },
      "deploymentId" : 250000055
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "6181ebb28763315b9604755e"
      },
      "deploymentId" : 250000266
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 250000160
    },
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "6193e7ac2171a2330e561ea0"
      },
      "deploymentId" : 250000320
    }
  ],
  "experiments" : [

  ]
},
  "reportNotes" : [
  "dyld_process_snapshot_get_shared_cache failed"
]
}

Model: MacBookAir10,1, BootROM 7429.41.5, proc 8:4:4 processors, 8 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: LS27R75, 2560 x 1440 (QHD/WQHD - Wide Quad High Definition), Main, MirrorOff, Online
Display: Color LCD, 2560 x 1600 Retina, MirrorOff, Online
Memory Module: LPDDR4
AirPort: Wi-Fi, wl0: Sep 13 2021 21:06:59 version 18.20.310.14.7.8.119 FWID 01-9d72ee4a
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB3.1 Hub
USB Device: USB 10/100/1000 LAN
USB Device: USB2.0 Hub
USB Device: DELL DA300
Thunderbolt Bus: MacBook Air, Apple Inc.
Thunderbolt Bus: MacBook Air, Apple Inc.
```

**Comment by dotneet** [comment]
I've got the same error.
After restarting my machine, worked without problems.

**Comment by mtricolici** [comment]
docker desktop for m1 has many issues.
example on x86 this run fine:
```
docker run jenkins/jenkins
```

and on my m1 (I want to use amd64 images)
```
export DOCKER_DEFAULT_PLATFORM=linux/amd64
docker run jenkins/jenkins
...
2021-11-23 15:03:59.362+0000 [id=32]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading global config
jenkins.model.InvalidBuildsDir: ${ITEM_ROOTDIR}/builds does not contain ${ITEM_FULL_NAME} or ${ITEM_ROOTDIR}, cannot distinguish between projects
	at jenkins.model.Jenkins.checkRawBuildsDir(Jenkins.java:3333)
	at jenkins.model.Jenkins.loadConfig(Jenkins.java:3276)
Caused: java.io.IOException
```

**Comment by bgold0** [comment]
Wow, this worked. Thank you @dotneet
