### ISSUE TITLE
uncaught target signal 6 (Aborted) - core dumped in MAC M1 machine.

### ISSUE THREAD

**Issue by Mohan2159** [docker/for-mac#6265]
Hi All,
We have created the simple .NET Core application and provided the docker support and build the image in amd64 architecture using docker commands by including this line **(FROM --platform=linux/amd64)** in the docker file. But on running the docker image using (docker run -d -p 6001:80 imageId)docker command they failed to lunch the localhost and the below error is thrown. We have also attached the docker file for your reference.

Unhandled exception. System.IO.IOException: Function not implemented
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationExtensions.Add[TSource](IConfigurationBuilder builder, Action`1 configureSource)
   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, IFileProvider provider, String path, Boolean optional, Bo
[docker.txt](https://github.com/docker/for-mac/files/8442841/docker.txt)
olean reloadOnChange)
   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, String path, Boolean optional, Boolean reloadOnChange)
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass11_0.<ConfigureDefaults>b__1(HostBuilderContext hostingContext, IConfigurationBuilder config)
   at Microsoft.AspNetCore.Hosting.BootstrapHostBuilder.RunDefaultCallbacks(ConfigurationManager configuration, HostBuilder innerBuilder)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)
   at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(String[] args)
   at Program.<Main>$(String[] args) in /src/Program.cs:line 1
qemu: uncaught target signal 6 (Aborted) - core dumped

**Note: On running the docker image in VS 2022 preview Mac M1 it works correctly.**

Docker file:

FROM --platform=linux/amd64 mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Viewerlatest.csproj", "."]
RUN dotnet restore "./Viewerlatest.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "Viewerlatest.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Viewerlatest.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Viewerlatest.dll"]

**Comment by djs55** [comment]
Thanks for the Dockerfile. Could you share the other files? For example "/Viewerlatest.csproj"

**Comment by Mohan2159** [comment]
Hi @djs55 ,

We have replicated the issue in a simple .NET CORE. Kindly refer the sample in the attachment.
[Project.zip](https://github.com/docker/for-mac/files/8713369/Project.zip)


Regards,
Mohan S

**Comment by johnsonmonohar** [comment]
Hi @djs55 ,

Is there any update on this?
