### ISSUE TITLE
Regression: 4.10.0 crashes when trying to install from command line

### ISSUE THREAD

**Issue by BenjaminPoulain** [docker/for-mac#6384]
With the release of Docker 4.10.0 today, we have been unable to install Docker from the command line. 

The install fails with the following error:
```
% sudo /Volumes/Docker/Docker.app/Contents/MacOS/install --accept-license
panic: paths have been accessed before the paths.Init(...) has been called. Decide which paths you want, and call paths.Init() from main()
goroutine 1 [running]:
[github.com/docker/pinata/common/pkg/paths.whereami()](http://github.com/docker/pinata/common/pkg/paths.whereami())
	/Users/administrator/jenkins/workspace/desktop_desktop-build_4.10.x/src/github.com/docker/pinata/common/pkg/paths/paths.go:87 +0x114
[github.com/docker/pinata/common/pkg/paths.hostServiceSockets.Backend({{0x14000230180](http://github.com/docker/pinata/common/pkg/paths.hostServiceSockets.Backend(%7B%7B0x14000230180)?, 0x0?}, {0x1045c8eba?, 0x14000212028?}})
	/Users/administrator/jenkins/workspace/desktop_desktop-build_4.10.x/src/github.com/docker/pinata/common/pkg/paths/sockets_host.go:39 +0x38
[github.com/docker/pinata/common/pkg/backend.NewClient({0x1045c9ae0](http://github.com/docker/pinata/common/pkg/backend.NewClient(%7B0x1045c9ae0), 0x7})
	/Users/administrator/jenkins/workspace/desktop_desktop-build_4.10.x/src/github.com/docker/pinata/common/pkg/backend/client.go:161 +0x44
main.copyApplicationTo({0x1045d1e1d, 0x18})
	/Users/administrator/jenkins/workspace/desktop_desktop-build_4.10.x/src/github.com/docker/pinata/mac/tools/install/main.go:71 +0x1b8
main.glob..func1(0x104a34720, {0x1400020a160, 0x1, 0x1})
	/Users/administrator/jenkins/workspace/desktop_desktop-build_4.10.x/src/github.com/docker/pinata/mac/tools/install/main.go:37 +0x90
[github.com/spf13/cobra.(*Command).execute(0x104a34720](http://github.com/spf13/cobra.(*Command).execute(0x104a34720), {0x14000136010, 0x1, 0x1})
	/Users/administrator/jenkins/workspace/desktop_desktop-build_4.10.x/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:856 +0x4c4
[github.com/spf13/cobra.(*Command).ExecuteC(0x104a34720)](http://github.com/spf13/cobra.(*Command).ExecuteC(0x104a34720))
	/Users/administrator/jenkins/workspace/desktop_desktop-build_4.10.x/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:974 +0x354
[github.com/spf13/cobra.(*Command).Execute(...)](http://github.com/spf13/cobra.(*Command).Execute(...))
	/Users/administrator/jenkins/workspace/desktop_desktop-build_4.10.x/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:902
main.main()
	/Users/administrator/jenkins/workspace/desktop_desktop-build_4.10.x/src/github.com/docker/pinata/mac/tools/install/main.go:89 +0xa8
```

The same command worked on Docker 4.9.1.

**Comment by mat007** [comment]
Thanks for reporting!
I created a high priority internal ticket to fix this.

**Comment by dkuss** [comment]
I get the same error on macOS Monterey 12.4 with an Intel chip MacBook Pro
```
$ sudo /Volumes/Docker/Docker.app/Contents/MacOS/install
panic: paths have been accessed before the paths.Init(...) has been called. Decide which paths you want, and call paths.Init() from main()

goroutine 1 [running]:
github.com/docker/pinata/common/pkg/paths.whereami()
	/Users/administrator/jenkins/workspace/desktop_desktop-build_4.10.x/src/github.com/docker/pinata/common/pkg/paths/paths.go:87 +0xca
github.com/docker/pinata/common/pkg/paths.hostServiceSockets.Backend({{0xc00002cb40?, 0x0?}, {0x45035fe?, 0x451abaf?}})
	/Users/administrator/jenkins/workspace/desktop_desktop-build_4.10.x/src/github.com/docker/pinata/common/pkg/paths/sockets_host.go:39 +0x3e
github.com/docker/pinata/common/pkg/backend.NewClient({0x4504236, 0x7})
	/Users/administrator/jenkins/workspace/desktop_desktop-build_4.10.x/src/github.com/docker/pinata/common/pkg/backend/client.go:161 +0x3b
main.copyApplicationTo({0x450c4b3, 0x18})
	/Users/administrator/jenkins/workspace/desktop_desktop-build_4.10.x/src/github.com/docker/pinata/mac/tools/install/main.go:71 +0x1c6
main.glob..func1(0x48a06e0, {0x48dbe18, 0x0, 0x0})
	/Users/administrator/jenkins/workspace/desktop_desktop-build_4.10.x/src/github.com/docker/pinata/mac/tools/install/main.go:37 +0x77
github.com/spf13/cobra.(*Command).execute(0x48a06e0, {0xc000020220, 0x0, 0x0})
	/Users/administrator/jenkins/workspace/desktop_desktop-build_4.10.x/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x48a06e0)
	/Users/administrator/jenkins/workspace/desktop_desktop-build_4.10.x/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/administrator/jenkins/workspace/desktop_desktop-build_4.10.x/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:902
main.main()
	/Users/administrator/jenkins/workspace/desktop_desktop-build_4.10.x/src/github.com/docker/pinata/mac/tools/install/main.go:89 +0xa5
```

**Comment by pehbehbeh** [comment]
> I get the same error on macOS Monterey 12.4 with an Intel chip MacBook Pro

Same here. I also unable to install via drag and drop:

> “Docker” is damaged and can’t be opened. You should move it to the Trash.

**Comment by mat007** [comment]
We are preparing a Docker Desktop 4.10.1 which will include a fix for this bug.
In the meanwhile here is an internal build which has it (it’s effectively just 2 commits forward from 4.10.0: the fix and the version bump):
- [Mac Intel](https://desktop-stage.docker.com/mac/main/amd64/82236/Docker.dmg)
- [Mac Arm](https://desktop-stage.docker.com/mac/main/arm64/82236/Docker.dmg)

**Comment by mat007** [comment]
> “Docker” is damaged and can’t be opened. You should move it to the Trash.

This looks like a download problem yielding a corrupted dmg? 🤔

**Comment by maxcleme** [comment]
This issue has been fixed in latest release, please consider updating to latest version and give us your feedback!

[4.10.1 Release notes](https://docs.docker.com/desktop/release-notes/#docker-desktop-4101)
