### ISSUE TITLE
Random crashes when accessing filesystem

### ISSUE THREAD

**Issue by BenjaminPoulain** [docker/for-mac#6393]
With Docker 4.10.1, we are observing random failures while using the filesystem.

Some cases that may be useful for debugging:

```
fatal error: schedule: holding locks

runtime stack:
runtime.throw(0x103fd8b4e, 0x17)
	runtime/panic.go:1117 +0x54
runtime.schedule()
	runtime/proc.go:3099 +0x488
runtime.park_m(0x14000500180)
	runtime/proc.go:3318 +0x88
runtime.mcall(0x0)
	runtime/asm_arm64.s:185 +0x58

goroutine 1 [runnable, locked to thread]:
encoding/gob.init.1()
	encoding/gob/type.go:274 +0x3a4

goroutine 49 [chan send]:
github.com/docker/compose/v2/cmd/formatter.init.0.func1(0x140002043f0)
	github.com/docker/compose/v2@v2.2.0/cmd/formatter/colors.go:120 +0x28c
created by github.com/docker/compose/v2/cmd/formatter.init.0
	github.com/docker/compose/v2@v2.2.0/cmd/formatter/colors.go:104 +0x1f4

goroutine 50 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x105f55500)
	k8s.io/klog/v2@v2.8.0/klog.go:1164 +0x70
created by k8s.io/klog/v2.init.0
	k8s.io/klog/v2@v2.8.0/klog.go:418 +0x128
```
This happened while listing a directory with `ls` through `docker exec` on a shared file system after heavy VirtioFS I/O.

An other:
```
fatal error: schedule: holding locks

runtime stack:
runtime.throw({0x103e688c0, 0x17})
	/usr/local/go/src/runtime/panic.go:1198 +0x54
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:3295 +0x47c
runtime.park_m(0x14000102820)
	/usr/local/go/src/runtime/proc.go:3516 +0x188
runtime.mcall()
	/usr/local/go/src/runtime/asm_arm64.s:179 +0x54

goroutine 1 [runnable]:
github.com/docker/cli/vendor/github.com/spf13/pflag.(*FlagSet).AddFlag(0x14000646d00, 0x1400065d0e0)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/pflag/flag.go:856 +0x178
github.com/docker/cli/vendor/github.com/spf13/pflag.(*FlagSet).VarPF(0x14000646d00, {0x104482080, 0x1400063b6e0}, {0x103e4a02b, 0x5}, {0x103e48002, 0x1}, {0x103e5a952, 0x10})
	/go/src/github.com/docker/cli/vendor/github.com/spf13/pflag/flag.go:831 +0x164
github.com/docker/cli/vendor/github.com/spf13/pflag.(*FlagSet).BoolVarP(0x14000646d00, 0x1400063b6e0, {0x103e4a02b, 0x5}, {0x103e48002, 0x1}, 0x0, {0x103e5a952, 0x10})
	/go/src/github.com/docker/cli/vendor/github.com/spf13/pflag/bool.go:55 +0x74
github.com/docker/cli/cli/command/stack.newServicesCommand({0x1044e1678, 0x140001c6410}, 0x1400063c590)
	/go/src/github.com/docker/cli/cli/command/stack/services.go:37 +0x214
github.com/docker/cli/cli/command/stack.NewStackCommand({0x1044e1678, 0x140001c6410})
	/go/src/github.com/docker/cli/cli/command/stack/cmd.go:67 +0x35c
github.com/docker/cli/cli/command/commands.AddCommands(0x140004fc840, {0x1044e1678, 0x140001c6410})
	/go/src/github.com/docker/cli/cli/command/commands/commands.go:76 +0x230
main.newDockerCommand(0x140001c6410)
	/go/src/github.com/docker/cli/cmd/docker/docker.go:64 +0x368
main.runDocker(0x140001c6410)
	/go/src/github.com/docker/cli/cmd/docker/docker.go:256 +0x28
main.main()
	/go/src/github.com/docker/cli/cmd/docker/docker.go:298 +0xd0

goroutine 34 [chan receive]:
github.com/docker/cli/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x1053490a0)
	/go/src/github.com/docker/cli/vendor/k8s.io/klog/klog.go:1010 +0x70
created by github.com/docker/cli/vendor/k8s.io/klog.init.0
	/go/src/github.com/docker/cli/vendor/k8s.io/klog/klog.go:411 +0x144
```
This happened while copying a file from host to container on a local file system.

**Comment by trungutt** [comment]
Hi @BenjaminPoulain, does this error happen with 4.10.0?

**Comment by BenjaminPoulain** [comment]
4.10.1.

We don't use 4.10.0 due to https://github.com/docker/for-mac/issues/6384

**Comment by dgageot** [comment]
@BenjaminPoulain I'm going to take a look. Any help you might provide to reproduce the issue would be welcome.

**Comment by misiek08** [comment]
@BenjaminPoulain please try to use volume instead of dir mount. 
May be related to same bug that was already in Docker years ago, got fixed and is probably back with us.
