### ISSUE TITLE
Cannot run a container with Docker Desktop's containerd experimental feature flagged

### ISSUE THREAD

**Issue by niccolomineo** [docker/for-mac#6468]
- [X] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: What's this?

### Expected behavior

I should be able to open a container.

### Actual behavior

Attempting to open a container fails.

### Information

Since enabling `containerd` in Docker Desktop, I cannot open containers anymore.

  - macOS Version: 12.5.1
  - Intel chip or Apple chip: Apple chip
  - Docker Desktop Version: 4.12.0

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
```

### Steps to reproduce the behavior

  1. Enable "Use containerd for pulling and storing images" under the "Experimental features" in Docker Desktop.
  2. Rebuild the project.
  3. Acknowledge that you are brought back to the local environment and are presented by the the `vscode-remote` extension with the following log:

```
[2022-09-01T19:38:00.823Z] Remote-Containers 0.251.0 in VS Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c).
[2022-09-01T19:38:00.823Z] Start: Resolving Remote
[2022-09-01T19:38:00.930Z] Setting up container for folder or workspace: /Users/me/Developer/MYPROJECT
[2022-09-01T19:38:00.935Z] Start: Check Docker is running
[2022-09-01T19:38:00.935Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2022-09-01T19:38:01.002Z] Stop (67 ms): Run: docker version --format {{.Server.APIVersion}}
[2022-09-01T19:38:01.003Z] Server API version: 1.43
[2022-09-01T19:38:01.003Z] Stop (68 ms): Check Docker is running
[2022-09-01T19:38:01.004Z] Start: Run: docker volume ls -q
[2022-09-01T19:38:01.089Z] Stop (85 ms): Run: docker volume ls -q
[2022-09-01T19:38:01.121Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/me/Developer/MYPROJECT --filter label=vsch.quality=stable
[2022-09-01T19:38:01.170Z] Stop (49 ms): Run: docker ps -q -a --filter label=vsch.local.folder=/Users/me/Developer/MYPROJECT --filter label=vsch.quality=stable
[2022-09-01T19:38:01.172Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/me/Developer/MYPROJECT
[2022-09-01T19:38:01.231Z] Stop (59 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/me/Developer/MYPROJECT
[2022-09-01T19:38:01.232Z] Start: Run: docker inspect --type container e113ea362715
[2022-09-01T19:38:01.288Z] Stop (56 ms): Run: docker inspect --type container e113ea362715
[2022-09-01T19:38:01.292Z] Start: Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/me/.vscode/extensions/ms-vscode-remote.remote-containers-0.251.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/me/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --docker-compose-path docker compose --workspace-folder /Users/me/Developer/MYPROJECT --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/me/Developer/MYPROJECT --log-level debug --log-format json --config /Users/me/Developer/MYPROJECT/.devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-09-01T19:38:01.738Z] remote-containers 0.251.0.
[2022-09-01T19:38:01.738Z] Start: Run: docker buildx version
[2022-09-01T19:38:01.919Z] Stop (181 ms): Run: docker buildx version
[2022-09-01T19:38:01.921Z] Start: Resolving Remote
[2022-09-01T19:38:01.934Z] Start: Run: docker compose version --short
[2022-09-01T19:38:01.948Z] Stop (14 ms): Run: docker compose version --short
[2022-09-01T19:38:01.950Z] Start: Run: docker compose version --short
[2022-09-01T19:38:01.967Z] Stop (33 ms): Run: docker compose version --short
[2022-09-01T19:38:02.023Z] Stop (73 ms): Run: docker compose version --short
[2022-09-01T19:38:02.023Z] Docker Compose version: 2.10.2
[2022-09-01T19:38:02.027Z] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=MYPROJECT --filter label=com.docker.compose.service=backend
[2022-09-01T19:38:02.091Z] Stop (64 ms): Run: docker ps -q -a --filter label=com.docker.compose.project=MYPROJECT --filter label=com.docker.compose.service=backend
[2022-09-01T19:38:02.092Z] Start: Run: docker inspect --type container e113ea362715
[2022-09-01T19:38:02.152Z] Stop (60 ms): Run: docker inspect --type container e113ea362715
[2022-09-01T19:38:02.155Z] Start: Inspecting container
[2022-09-01T19:38:02.155Z] Start: Run: docker inspect --type container e113ea362715f4ab10684c62aa7841b56f705086baa2021b66b0d2a581826c79
[2022-09-01T19:38:02.204Z] Stop (49 ms): Run: docker inspect --type container e113ea362715f4ab10684c62aa7841b56f705086baa2021b66b0d2a581826c79
[2022-09-01T19:38:02.205Z] Stop (50 ms): Inspecting container
[2022-09-01T19:38:02.210Z] Start: Run in container: /bin/sh
[2022-09-01T19:38:02.215Z] Start: Run in container: uname -m
[2022-09-01T19:38:02.280Z] Stop (70 ms): Run in container: /bin/sh
[2022-09-01T19:38:02.281Z] Shell server terminated (code: 126, signal: null)
[2022-09-01T19:38:02.282Z] GetResourcePath: BaseFS of container e113ea362715f4ab10684c62aa7841b56f705086baa2021b66b0d2a581826c79 is unexpectedly nil
[2022-09-01T19:38:02.280Z] Start: Run in container: cat /etc/passwd
[2022-09-01T19:38:02.281Z] Stdin closed!
[2022-09-01T19:38:02.284Z] Error: An error occurred setting up the container.
[2022-09-01T19:38:02.285Z]     at dF (/Users/me/.vscode/extensions/ms-vscode-remote.remote-containers-0.251.0/dist/spec-node/devContainersSpecCLI.js:206:2698)
[2022-09-01T19:38:02.285Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-09-01T19:38:02.285Z]     at async DF (/Users/me/.vscode/extensions/ms-vscode-remote.remote-containers-0.251.0/dist/spec-node/devContainersSpecCLI.js:263:2177)
[2022-09-01T19:38:02.285Z]     at async to (/Users/me/.vscode/extensions/ms-vscode-remote.remote-containers-0.251.0/dist/spec-node/devContainersSpecCLI.js:263:3110)
[2022-09-01T19:38:02.285Z]     at async Ak (/Users/me/.vscode/extensions/ms-vscode-remote.remote-containers-0.251.0/dist/spec-node/devContainersSpecCLI.js:383:8108)
[2022-09-01T19:38:02.285Z]     at async Ok (/Users/me/.vscode/extensions/ms-vscode-remote.remote-containers-0.251.0/dist/spec-node/devContainersSpecCLI.js:383:7864)
[2022-09-01T19:38:02.291Z] Stop (999 ms): Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/me/.vscode/extensions/ms-vscode-remote.remote-containers-0.251.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/me/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --docker-compose-path docker compose --workspace-folder /Users/me/Developer/MYPROJECT --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/me/Developer/MYPROJECT --log-level debug --log-format json --config /Users/me/Developer/MYPROJECT/.devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-09-01T19:38:02.292Z] Exit code 1
[2022-09-01T19:38:02.306Z] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/me/.vscode/extensions/ms-vscode-remote.remote-containers-0.251.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/me/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --docker-compose-path docker compose --workspace-folder /Users/me/Developer/MYPROJECT --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/me/Developer/MYPROJECT --log-level debug --log-format json --config /Users/me/Developer/MYPROJECT/.devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-09-01T19:38:02.307Z] Exit code 1
```

**Comment by daniel060896** [comment]
Hi, I had the same problem.
This problem happen because you're not using containers from [VSCode Container Images](https://hub.docker.com/_/microsoft-vscode-devcontainers).

In the `Dockerfile` file, you can replace some images with another `VSCode Container Image`:
```yml
# FROM python:3.8
FROM mcr.microsoft.com/vscode/devcontainers/python:3.8
```
I hope it can help you.

**Comment by moesy** [comment]
This is still an issue with the following images taken from https://hub.docker.com/_/microsoft-vscode-devcontainers?tab=description

- ubuntu18.04
- ubuntu-22.04

**Comment by niccolomineo** [comment]
> Hi, I had the same problem.
> 
> This problem happen because you're not using containers from [VSCode Container Images](https://hub.docker.com/_/microsoft-vscode-devcontainers).
> 
> 
> 
> In the `Dockerfile` file, you can replace some images with another `VSCode Container Image`:
> 
> ```dockerfile
> 
> # FROM python:3.8
> 
> FROM mcr.microsoft.com/vscode/devcontainers/python:3.8
> 
> ```
> 
> I hope it can help you.

Hi, if that's really why it's not working on my machine, I am probably never going too use the functionality at all, because at my workplace not everyone adopts VSCode. 🤷🏻‍♂️

**Comment by moesy** [comment]
Hi @niccolomineo thank you for adding context. I'm using ```FROM mcr.microsoft.com/vscode/devcontainers/base:0-${VARIANT}``` with VARIANT being ubuntu18.04
and ubuntu-22.04 and still had the same issue. 

Turning off the feature solved my issue.

**Comment by niccolomineo** [comment]
> Hi @niccolomineo thank you for adding context. I'm using `FROM mcr.microsoft.com/vscode/devcontainers/base:0-${VARIANT}` with VARIANT being ubuntu18.04 and ubuntu-22.04 and still had the same issue.
> 
> Turning off the feature solved my issue.

In my case, it's a Debian-based image that's failing, `python:3.10-slim-bullseye`.

**Comment by rnarkk** [comment]
Let's keep this issue open as just turning off the experimental `containerd` feature shouldn't be the solution.
