### ISSUE TITLE
Docker for Mac 4.17.0 doesn't work anymore with Python. Worked with 4.16.2

### ISSUE THREAD

**Issue by apacha** [docker/for-mac#6768]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
Update 23.03.2023:
  - Diagnostics ID after manual re-installing 4.17.0 before restarting the computer (problem doesn't occur yet): 6E94C265-55F1-4090-AB27-F253683909BF/20230323104446
 - Diagnostics ID after manual re-installing 4.17.0 after restarting the computer (where the problem now exists): 6E94C265-55F1-4090-AB27-F253683909BF/20230323105408
  - Diagnostics ID after downgrading to 4.16.2 (where the problem is gone): 6E94C265-55F1-4090-AB27-F253683909BF/20230316134349
   
### Expected behavior
When running stuff like 
```python
        client = docker.from_env()
        build_logs = client.api.build(
            path=PROJECT_ROOT_DIRECTORY,
            dockerfile=str(PROJECT_ROOT_PATH / "Dockerfile"),
            tag=PDF_PNG_CONVERTER_TAG
        )
```
Docker should build the image.

### Actual behavior
```
Traceback (most recent call last):
  File "/Users/project/start_something.py", line 54, in <module>
    client = docker.from_env()
  File "/Users/project/venv/lib/python3.9/site-packages/docker/client.py", line 96, in from_env
    return cls(
  File "/Users/project/venv/lib/python3.9/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/Users/project/venv/lib/python3.9/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/Users/project/venv/lib/python3.9/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

### Information

* Problem appeared after upgrading to 4.17.0
* I've tried to re-install 4.17.0 - problem still persisted
* Directly after the installation of 4.17.0 it worked, but once I restarted my MacBook, the problem started to appear
* Downgraded to 4.16.2 solved the problem

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check` after downgrade
```
alex@Alexanders-MacBook-Pro ~ % /Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0038: is the connection to Docker working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?
No fatal errors detected.
alex@Alexanders-MacBook-Pro ~ %
```

**Comment by tanzislam** [comment]
It's important to get the diagnostics while the problem is still there, so that the bot can apply the correct version label.

This issue should be the same as #6767.

**Comment by apacha** [comment]
Will try to upgrade again and get fresh diagnostics in three next couple of days

**Comment by bartwozniak** [comment]
Having the same problem. MacOS 13.2.1 (22D68) and Docker 4.17.0. 4.16.2 works fine.

**Comment by apacha** [comment]
@tanzislam I've updated the Diagnostics IDs and provided a total of three different ones.
