### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference - SEGV, go-fuse

### ISSUE THREAD

**Issue by rfay** [docker/for-mac#6895]
### Description

Dialog box with "Something went wrong":

<img width="388" alt="image" src="https://github.com/docker/for-mac/assets/112444/92fa49ae-9056-4b5b-b531-ee708816b89b">

```
Docker panic: [2023-06-29T22:38:49.278869483Z][docker][I] panic: runtime error: invalid memory address or nil pointer dereference
[2023-06-29T22:38:49.278879291Z][docker][I] [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x9def37]
[2023-06-29T22:38:49.278897496Z][docker][I] 
[2023-06-29T22:38:49.278897695Z][docker][I] goroutine 9100007 [running]:
[2023-06-29T22:38:49.279226366Z][docker][I] github.com/hanwen/go-fuse/v2/fuse/nodefs.(*Inode).Node(...)
[2023-06-29T22:38:49.279242985Z][docker][I] 	github.com/hanwen/go-fuse/v2@v2.1.0/fuse/nodefs/inode.go:126
[2023-06-29T22:38:49.279622874Z][docker][I] github.com/hanwen/go-fuse/v2/fuse/pathfs.(*PathNodeFs).Path(...)
[2023-06-29T22:38:49.279627499Z][docker][I] 	github.com/hanwen/go-fuse/v2@v2.1.0/fuse/pathfs/pathfs.go:137
[2023-06-29T22:38:49.279636600Z][docker][I] github.com/docker/grpcfuse/pkg/mount.(*fuseMount).delete(0xc000364420?, 0xc00087b100?, 0x10?, 0xc000347928?, {0x0?, 0x7f1fe96e0ff8?})
[2023-06-29T22:38:49.279637215Z][docker][I] 	github.com/docker/grpcfuse@v0.0.0-20230427082218-7c000cca7677/pkg/mount/fuse_linux.go:175 +0x37
[2023-06-29T22:38:49.279640570Z][docker][I] github.com/docker/grpcfuse/pkg/mount.(*fuseMount).parents(0xc000232b80, 0xbff9da?, 0xc000f20380, {0xc049e3?, 0xc?})
[2023-06-29T22:38:49.279641109Z][docker][I] 	github.com/docker/grpcfuse@v0.0.0-20230427082218-7c000cca7677/pkg/mount/fuse_linux.go:274 +0x185
[2023-06-29T22:38:49.279643957Z][docker][I] github.com/docker/grpcfuse/pkg/mount.(*fuseMount).All(0xc000232b80, 0x0, {0xc000b10d41, 0x3b})
[2023-06-29T22:38:49.279644146Z][docker][I] 	github.com/docker/grpcfuse@v0.0.0-20230427082218-7c000cca7677/pkg/mount/fuse_linux.go:350 +0x2a5
[2023-06-29T22:38:49.279646729Z][docker][I] github.com/docker/grpcfuse/pkg/mount.(*server).All(0xea0e00?, {0xc000ae7f40?, 0x49cda6?}, 0xc000ae7f40)
[2023-06-29T22:38:49.279646906Z][docker][I] 	github.com/docker/grpcfuse@v0.0.0-20230427082218-7c000cca7677/pkg/mount/server.go:318 +0x8a
[2023-06-29T22:38:49.287551749Z][docker][I] github.com/docker/grpcfuse/pkg/pb._Invalidate_All_Handler({0xeece80?, 0xc000038200}, {0xf46838, 0xc00106e960}, 0xc000b6a5b0, 0x0)
[2023-06-29T22:38:49.287561308Z][docker][I] 	github.com/docker/grpcfuse@v0.0.0-20230427082218-7c000cca7677/pkg/pb/invalidate.pb.go:560 +0x170
[2023-06-29T22:38:49.287582425Z][docker][I] google.golang.org/grpc.(*Server).processUnaryRPC(0xc000472000, {0xf4c600, 0xc000bcf6c0}, 0xc000518120, 0xc0003fb3e0, 0x147ef20, 0x0)
[2023-06-29T22:38:49.287582643Z][docker][I] 	google.golang.org/grpc@v1.54.0/server.go:1345 +0xdf3
[2023-06-29T22:38:49.287604462Z][docker][I] google.golang.org/grpc.(*Server).handleStream(0xc000472000, {0xf4c600, 0xc000bcf6c0}, 0xc000518120, 0x0)
[2023-06-29T22:38:49.287604805Z][docker][I] 	google.golang.org/grpc@v1.54.0/server.go:1722 +0xa36
[2023-06-29T22:38:49.287607824Z][docker][I] google.golang.org/grpc.(*Server).serveStreams.func1.2()
[2023-06-29T22:38:49.287608050Z][docker][I] 	google.golang.org/grpc@v1.54.0/server.go:966 +0x98
[2023-06-29T22:38:49.287610585Z][docker][I] created by google.golang.org/grpc.(*Server).serveStreams.func1
[2023-06-29T22:38:49.287610783Z][docker][I] 	google.golang.org/grpc@v1.54.0/server.go:964 +0x28a
[2023-06-29T22:38:49.415401005Z][docker][I] EOF
```

### Reproduce

Happens intermittently in DDEV automated testing

### Expected behavior

Crashes/panics/SEGVs are bad.

### docker version

```bash
Client:
 Cloud integration: v1.0.33
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:51:16 2023
 OS/Arch:           darwin/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.20.1 (110738)
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.2
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     /Users/testbot/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /Users/testbot/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/testbot/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     /Users/testbot/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     /Users/testbot/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/testbot/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/testbot/.docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.12.0
    Path:     /Users/testbot/.docker/cli-plugins/docker-scout

Server:
 Containers: 4
  Running: 3
  Paused: 0
  Stopped: 1
 Images: 30
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.49-linuxkit-pr
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 5.805GiB
 Name: docker-desktop
 ID: f1113599-882f-47b0-8287-08a0809dcb14
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Diagnostics ID

A809B877-3A61-4D4B-A198-C55B79DC16BE/20230629225029

### Additional Info

DDEV's automated test suite runs loads and loads of stops/starts/etc. Hours worth. Over and over.

**Comment by rfay** [comment]
<img width="481" alt="image" src="https://github.com/docker/for-mac/assets/112444/45b106cb-0119-4bfe-a6c0-ef4bf4204266">

**Comment by rfay** [comment]
Again today.

**Comment by rfay** [comment]
Still happens periodically, "Something went wrong" with panic.

**Comment by rfay** [comment]
Saw it this morning.

**Comment by claudio-destro** [comment]
Still present on 4.22.1.
Reproducible by clicking in the status column of a stopped container (right after Docker Desktop start).

My Diagnostics ID `d4455dca-44f4-449f-8892-f14400bde59f/20230831083431`

<img width="713" alt="Screenshot 2023-08-31 alle 10 39 00" src="https://github.com/docker/for-mac/assets/11568024/83935897-c4a1-407d-a58d-50e1cb42ec0b">

**Comment by claudio-destro** [comment]
Thanks @thaJeztah 

so it seems https://github.com/docker/for-mac/issues/6942 still not fixed in 4.22.1 🥲

**Comment by rfay** [comment]
This is so old and fuse is so obsolete, closing.
