### ISSUE TITLE
Docker crashing daily on restart

### ISSUE THREAD

**Issue by shimonacarvalho** [docker/for-mac#6966]
### Description

Often every morning on wakeup, docker has crashed. There's an error on screen and I have to close it. A second one pops up about a watchdog and I close that. Then I have to restart docker, then restart my containers. 

### Reproduce

Docker is running with two containers everyday. 
`docker-compose up -d api`

Mac OS sleeps each night. 
Often every morning on wakeup, docker has crashed. 
Error 1 on screen about the crash. I close it. 
Error 2 on screen about a watchdog. I close it. 

### Expected behavior

Docker containers should continue to be running. 

### docker version

```bash
Client:
 Cloud integration: v1.0.35
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:51:16 2023
 OS/Arch:           darwin/amd64
 Context:           default
```

### docker info

```bash
Client:
 Version:    24.0.2
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.0
    Path:     /Users/shimona/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.19.1
    Path:     /Users/shimona/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/shimona/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/shimona/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.6
    Path:     /Users/shimona/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/shimona/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/shimona/.docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.16.1
    Path:     /Users/shimona/.docker/cli-plugins/docker-scout

Server:
 Containers: 3
  Running: 1
  Paused: 0
  Stopped: 2
 Images: 3
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.49-linuxkit-pr
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.675GiB
 Name: docker-desktop
 ID: 0c61ebb8-71c4-4956-9ae0-ef41e135726d
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Diagnostics ID

A8AFD88B-A383-41AD-A3DE-1C52C469A2CD/20230906155023

### Additional Info

To make our docker files work I've had to switch to gRPC file system.

**Comment by djs55** [comment]
Thanks for the diagnostics. I think the cause of the crash is
```
[2023-09-06T07:54:10.079013400Z][dockerd][I] [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x55ef20f1cb44]
[2023-09-06T07:54:10.079039913Z][dockerd][I]
[2023-09-06T07:54:10.079040176Z][dockerd][I] goroutine 222387 [running]:
[2023-09-06T07:54:10.079312420Z][dockerd][I] github.com/docker/docker/daemon.(*Daemon).ProcessEvent.func1()
[2023-09-06T07:54:10.082663024Z][dockerd][I]    /go/src/github.com/docker/docker/daemon/monitor.go:190 +0x44
[2023-09-06T07:54:10.082686565Z][dockerd][I] created by github.com/docker/docker/daemon.(*Daemon).ProcessEvent
[2023-09-06T07:54:10.082687844Z][dockerd][I]    /go/src/github.com/docker/docker/daemon/monitor.go:189 +0x55d
[2023-09-06T07:54:10.404940037Z][dockerd][I] EOF
```

**Comment by vvoland** [comment]
Hi,
This crash is already fixed in the Docker Engine v24.0.3 release. Please upgrade your Docker Desktop to the 4.22 (or higher) version.
