### ISSUE TITLE
Build directory not properly ADDed

### ISSUE THREAD

**Issue by iainhouston** [docker/for-mac#709]
### Expected behavior

The `web` directory should be correctly `ADD`ed to `/usr/src/app` in the following case.( See directory structure below.)

The  `docker-compose.yml` file has the `web/Dockerfile` build an image, copying the context (the contents of its build directory) i.e. the `web` directory.

### Actual behavior

The image does not contain the expected `web` directory structure. `command: ls -la /usr/src/app/mycms`  indicates that the directory `mycms/wsgi` is not present. Consequently, `command: /usr/local/bin/gunicorn mycms.wsgi:application -w 2 -b :8000` fails with:  

```
    __import__(module)
ImportError: No module named 'mycms.wsgi'
```

See fuller diagnostics below.

### Information

I am using: 

-  docker-compose version 1.8.0, build f3628c7
-  Docker version 1.12.1, build 6f9534c (Docker for Mac)

  The `docker-compose.yml` file:  

```
web:
  restart: always
  build: ./web
  expose:
    - "8000"
  links:
    - postgres:postgres 
  volumes:
    - web:/usr/src/app
  env_file: .env

  # DEBUG:
  # working_dir: /usr/src/app
  # command: ls mycms
  # command: ls -la /usr/src/app/mycms

  command: /usr/local/bin/gunicorn mycms.wsgi:application -w 2 -b :8000

nginx:
   ...
```

`web/Dockerfile`:   

```
FROM python:3.5

ENV BUILD_TIMESTAMP 2016-09-27T19:07:00Z

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /usr/src/app
```

Directory structure:  

```
.
├── docker-compose.yml
├── nginx
│   ├── Dockerfile
│   └── sites-enabled
│       └── django_project
└── web
    ├── Dockerfile
    ├── manage.py
    ├── media
    ├── mycms
    │   ├── __init__.py
    │   ├── __pycache__
    │   ├── settings.py
    │   ├── static
    │   ├── templates
    │   ├── urls.py
    │   └── wsgi.py
    ├── project.db
    ├── requirements.txt
    └── static
```

Fuller diagnostics:  

build:  

```
...
Step 7 : COPY . /usr/src/app
 ---> 40f78fb50798
Removing intermediate container 282c6e804331
Successfully built 40f78fb50798
...
```

log:  

```
...
[2016-09-27 17:36:49 +0000] [1] [INFO] Starting gunicorn 19.6.0
[2016-09-27 17:36:49 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2016-09-27 17:36:49 +0000] [1] [INFO] Using worker: sync
[2016-09-27 17:36:49 +0000] [9] [INFO] Booting worker with pid: 9
[2016-09-27 17:36:49 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.5/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
ImportError: No module named 'mycms.wsgi'
[2016-09-27 17:36:49 +0000] [9] [INFO] Worker exiting (pid: 9)
[2016-09-27 17:36:49 +0000] [9] [INFO] Worker exiting (pid: 9)
[2016-09-27 17:36:49 +0000] [10] [ERROR] Exception in worker process
...
```

**Comment by dsheets** [comment]
I believe that an unqualified volume name like `web` will result in the creation of a new Docker volume called `web`. If you want to mount the local directory `web` (relative to the working directory), you should use `./web`. Does that solve your issue?

**Comment by iainhouston** [comment]
@dsheets oh yes! I do believe it has solved my issue. Thank you!
