### ISSUE TITLE
Launch docker desktop always makes my macbook reboot

### ISSUE THREAD

**Issue by Angryshark128** [docker/for-mac#7426]
### Description

When i try to launch docker desktop at my laptop, i will always make it reboot before the docker desktop window shows. Although i tried many times to restart, or deleted all files and reinstalled all of older versions, this issue isn't resolved yet.

My laptop: MacBook Pro (16-inch, 2021), chip: Apple M1 Pro

### Reproduce

1. Install docker desktop
2. Launch it
3. Mouse cursor is freezen and reboot immediately

### Expected behavior

Shall not reboot my laptop and show the main window

### docker version

```bash
Client:
 Version:           27.1.1
 API version:       1.46
 Go version:        go1.21.12
 Git commit:        6312585
 Built:             Tue Jul 23 19:54:12 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux
```

### docker info

```bash
Client:
 Version:    27.1.1
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.1-desktop.1
    Path:     ~/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.1-desktop.1
    Path:     ~/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.34
    Path:     ~/.docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.14
    Path:     ~/.docker/cli-plugins/docker-desktop
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     ~/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.25
    Path:     ~/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     ~/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.3.0
    Path:     ~/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     ~/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.11.0
    Path:     ~/.docker/cli-plugins/docker-scout
```

### Diagnostics ID

106F6DB7-6496-44E1-9323-B36E938EF546/20240920070747

**Comment by geshan** [comment]
I am also facing this same issue after the docker desktop upgrade.

**Comment by Angryshark128** [comment]
> I am also facing this same issue after the docker desktop upgrade.

I choose to use [`colima`](https://github.com/abiosoft/colima)instead of docker desktop as the workaround now.

**Comment by geshan** [comment]
@Angryshark128 I also did the same to unblock myself, the mounted volumes had an issue but it basically worked.

**Comment by nikolozz** [comment]
Is there any update on it? I'm also facing the same issue.

**Comment by XijiaoLi** [comment]
+1 I am also facing this same issue on both 4.33.0 and 4.34.2. Also I can't run uninstall:
```
% sudo /Applications/Docker.app/Contents/MacOS/uninstall
Password:
Uninstalling Docker Desktop...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x103f8ac84]

goroutine 1 [running]:
github.com/docker/pinata/common/cmd/com.docker.backend/internal/component.NewSettingsUpdater[...]({0x103fa1b05, 0xa}, {0x0, 0x0})
	github.com/docker/pinata/common/cmd/com.docker.backend/internal/component/settings_updater.go:17 +0xa4
github.com/docker/pinata/common/cmd/com.docker.backend/internal/app.New({0x0, 0x0}, {0x0, 0x0}, {0x104703b58, 0x105b813a0}, {0x0, 0x0}, {0x0, 0x0}, ...)
	github.com/docker/pinata/common/cmd/com.docker.backend/internal/app/app.go:66 +0xa4
github.com/docker/pinata/common/cmd/com.docker.backend/application.Uninstall({0x0?, 0x0?}, {0x140000546e0, 0x42})
	github.com/docker/pinata/common/cmd/com.docker.backend/application/uninstall.go:25 +0x128
main.init.func1(0x140004ae400?, {0x105b813a0?, 0x4?, 0x103f93d56?})
	github.com/docker/pinata/mac/tools/uninstall/main.go:34 +0x108
github.com/spf13/cobra.(*Command).execute(0x1055546c0, {0x1400004e090, 0x0, 0x0})
	github.com/spf13/cobra@v1.8.1/command.go:985 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x1055546c0)
	github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.1/command.go:1041
main.main()
	github.com/docker/pinata/mac/tools/uninstall/main.go:52 +0x24
```
