### ISSUE TITLE
containerd panic

### ISSUE THREAD

**Issue by medecau** [docker/for-mac#7476]
### Description

after starting docker desktop on macos m1 it crashes with a "VM has shutdown" and "containerd panic" messages.

![Image](https://github.com/user-attachments/assets/2833f5ec-e04b-428c-933b-a1f08805742b)

```
$ uname -a
Darwin airpro.local 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:05:14 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8103 arm64
```

### Reproduce

1. reboot computer
2. start docker desktop
3. wait a few seconds for pop-up

### Expected behavior

normal docker desktop operation

### docker version

n/a

### docker info

n/a

### Diagnostics ID

69CCF432-BA58-4AB2-A5D7-6E899C00A2FD/20241106083350

**Comment by medecau** [comment]
i might have fixed this for myself by having a fight with docker – think `kill -9 <a bunch of pids>` and `rm -rf /Users/medecau/Library/Application\ Support/Docker\ Desktop` followed by a reinstall.

i'll leave the ticket open to allow you the opportunity to decide on it

**Comment by thaJeztah** [comment]
Thanks for providing the diagnostics. From what I can see, it looks like the Docker Desktop VM ran out of disk space, which likely resulted in corruption in a database-file that containerd uses; here's where the "no space left on device" errors showed up;

```
time="2024-07-12T09:03:37.411093708Z" level=info msg="starting containerd" revision=d2d58213f83a351ca8f528a95fbd145f5654e957 version=1.6.33
...
ime="2024-07-12T16:44:10.428585666Z" level=info msg="loading plugin \"io.containerd.internal.v1.tracing\"..." type=io.containerd.internal.v1
time="2024-07-12T16:44:10.428615083Z" level=info msg="skip loading plugin \"io.containerd.internal.v1.tracing\"..." error="skip plugin: tracing endpoint not configured" type=io.containerd.internal.v1
time="2024-07-12T16:44:10.428631458Z" level=info msg="loading plugin \"io.containerd.grpc.v1.healthcheck\"..." type=io.containerd.grpc.v1
time="2024-07-12T16:44:10.428788625Z" level=info msg=serving... address=/run/containerd/containerd.sock.ttrpc
time="2024-07-12T16:44:10.428840541Z" level=info msg=serving... address=/run/containerd/containerd.sock
time="2024-07-12T16:44:10.428860125Z" level=info msg="containerd successfully booted in 0.020097s"
time="2024-07-12T16:51:43.092753918Z" level=error msg="garbage collection failed" error="write /var/lib/desktop-containerd/daemon/io.containerd.metadata.v1.bolt/meta.db: no space left on device"
time="2024-07-12T16:53:25.519606590Z" level=error msg="garbage collection failed" error="write /var/lib/desktop-containerd/daemon/io.containerd.metadata.v1.bolt/meta.db: no space left on device"
time="2024-07-12T16:55:08.940613138Z" level=error msg="garbage collection failed" error="write /var/lib/desktop-containerd/daemon/io.containerd.metadata.v1.bolt/meta.db: no space left on device"
EOF
```

The first reboot after this showed a panic happening when handling that file;

```
time="2024-08-16T11:56:57.692159542Z" level=info msg="starting containerd" revision=d2d58213f83a351ca8f528a95fbd145f5654e957 version=1.6.33
...
time="2024-08-16T11:56:57.734892958Z" level=info msg="skip loading plugin \"io.containerd.internal.v1.tracing\"..." error="skip plugin: tracing endpoint not configured" type=io.containerd.internal.v1
time="2024-08-16T11:56:57.734909333Z" level=info msg="loading plugin \"io.containerd.grpc.v1.healthcheck\"..." type=io.containerd.grpc.v1
time="2024-08-16T11:56:57.735230000Z" level=info msg=serving... address=/run/containerd/containerd.sock.ttrpc
time="2024-08-16T11:56:57.735384750Z" level=info msg=serving... address=/run/containerd/containerd.sock
time="2024-08-16T11:56:57.735450708Z" level=info msg="containerd successfully booted in 0.045366s"
time="2024-08-16T11:56:57.965555375Z" level=error msg="garbage collection failed" error="write /var/lib/desktop-containerd/daemon/io.containerd.metadata.v1.bolt/meta.db: no space left on device"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xaaaae90f38a8]

goroutine 72 [running]:
github.com/containerd/containerd/gc/scheduler.(*gcScheduler).run(0x400001cc00, {0xaaaaea321790, 0x400019ca00})
	/go/src/github.com/containerd/containerd/gc/scheduler/scheduler.go:317 +0x4c8
created by github.com/containerd/containerd/gc/scheduler.init.0.func1 in goroutine 56
	/go/src/github.com/containerd/containerd/gc/scheduler/scheduler.go:132 +0x368
EOF
```

**Comment by medecau** [comment]
hey @thaJeztah thanks for replying, i think i figured it out and things have been working smoothly ever since; it's okay to close this issue now.

---

_as a_ user of docker desktop _i want to_ have a chance to adjust the configuration before the engine is restarted _so i_ don't have to nuke my installation.

**Comment by nickovs** [comment]
I'm suffering from the same problem. I've tried killing off all Docker-related processes, removing `~/Library/Application Support/Docker Desktop`, rebooting and reinstalling, but it's still panicking. Suggestions for fixes welcome.

Diagnostic ID: `399C0E73-4310-4D9E-9D5B-EE53CCEB2ABE/20241126004357`

**Comment by nickovs** [comment]
For others who run into this issue, forcibly removing all container storage seems to have done the trick:
```
rm -rf ~/Library/Containers/com.docker.docker
```

**Comment by joeldavuk** [comment]
> For others who run into this issue, forcibly removing all container storage seems to have done the trick:
> 
> ```
> rm -rf ~/Library/Containers/com.docker.docker
> ```

That's one solution, in my case running from an external SSD, which likely laptop ran out of power or unplugged without ejecting, looks like there is some solutions in https://github.com/containerd/containerd/issues/3347 if you don't want to re-install all of your docker containers

**Comment by mkarajohn** [comment]
For anyone else coming to this, if this happened due to no space left in the VM, you can resize it and then restart docker desktop. 

You do not need to lose all your containers. 

For me on Ubuntu this did the trick:
`qemu-img resize ~/.docker/desktop/vms/0/data/Docker.raw +10G`
