### ISSUE TITLE
Issues setting up development container

### ISSUE THREAD

**Issue by crmejia** [docker/for-mac#759]
### Expected behavior

I'm trying to complete the development guide: https://docs.docker.com/opensource/project/set-up-dev-env/#/task-2-start-a-development-container
### Actual behavior

I've found two issues so far:

First, when following Task 2.4(Use make to build a development environment image and run it in a container.) the make would fail when running Step 6 : RUN apt-get update && apt-get install -y 

I was able to get over this hurdle after resetting a couple times.

Second, when following Task 2.6(Make a docker binary.) The build would failed while running test. 

--- FAIL: Test (3482.97s)
panic: DockerSuite.TestHealth test timed out after 5m0s [recovered]
    panic: DockerSuite.TestHealth test timed out after 5m0s
### Information

```
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/9F64B7D5-C334-4584-8630-C1194215BDC8/20161006-222112.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```
### Steps to reproduce the behavior

Following the guide.

I understand that it might be silly to report a failing test but I've been stuck for a while and I've run out of ideas.

**Comment by samoht** [comment]
Could you try with Beta27? We don't seem to be able to reproduce your issue in our settings. Could you also try to post the full logs for the failing tests?

```
panic: DockerSuite.TestHealth test timed out after 5m0s [recovered]
panic: DockerSuite.TestHealth test timed out after 5m0s
```

You can select to run just these tests by running `env TESTFLAGS='-check.f DockerSuite.TestHealth*' make test-integration-cli`

Thanks!

**Comment by crmejia** [comment]
I had to run 
`env TESTFLAGS='-check.f DockerSuite.TestHealth*' hack/make.sh binary-daemon binary-client test-integration-cli`
as I kept getting: 
`error: binary-client or dynbinary-client must be run before .integration-daemon-start` and
`error: binary-daemon or dynbinary-daemon must be run before .integration-daemon-start`

The test passes. This is the output:

```
root@eb20886b649b:/go/src/github.com/docker/docker# env TESTFLAGS='-check.f DockerSuite.TestHealth*' hack/make.sh binary-daemon binary-client test-integration-cli

bundles/1.13.0-dev already exists. Removing.

---> Making bundle: binary-daemon (in bundles/1.13.0-dev/binary-daemon)
Building: bundles/1.13.0-dev/binary-daemon/dockerd-1.13.0-dev
Created binary: bundles/1.13.0-dev/binary-daemon/dockerd-1.13.0-dev
Building: bundles/1.13.0-dev/binary-daemon/docker-proxy-1.13.0-dev
Created binary: bundles/1.13.0-dev/binary-daemon/docker-proxy-1.13.0-dev
Copying nested executables into bundles/1.13.0-dev/binary-daemon

---> Making bundle: binary-client (in bundles/1.13.0-dev/binary-client)
Building: bundles/1.13.0-dev/binary-client/docker-1.13.0-dev
Created binary: bundles/1.13.0-dev/binary-client/docker-1.13.0-dev

---> Making bundle: test-integration-cli (in bundles/1.13.0-dev/test-integration-cli)
---> Making bundle: .integration-daemon-start (in bundles/1.13.0-dev/test-integration-cli)
INFO: Waiting for daemon to start...
+++ exec dockerd --debug --host unix:///go/src/github.com/docker/docker/bundles/1.13.0-dev/test-integration-cli/docker.sock --storage-driver aufs --pidfile bundles/1.13.0-dev/test-integration-cli/docker.pid --userland-proxy=true
.
---> Making bundle: .integration-daemon-setup (in bundles/1.13.0-dev/test-integration-cli)
---> Making bundle: .detect-daemon-osarch (in bundles/1.13.0-dev/test-integration-cli)
---> Making bundle: .ensure-emptyfs (in bundles/1.13.0-dev/test-integration-cli)
++++ tar -cC bundles/1.13.0-dev/test-integration-cli/emptyfs .
++++ docker load
Building test dir: integration-cli
++ cd integration-cli
++ go test -c -o bundles/1.13.0-dev/test-integration-cli/test.main -ldflags -w -tags 'autogen netgo static_build sqlite_omit_load_extension apparmor pkcs11 seccomp selinux daemon journald libdm_no_deferred_remove' -installsuffix netgo -a
++ env -i DEST=/go/src/github.com/docker/docker/bundles/1.13.0-dev/test-integration-cli DOCKER_TLS_VERIFY= DOCKER_CERT_PATH= DOCKER_ENGINE_GOARCH=amd64 DOCKER_GRAPHDRIVER=aufs DOCKER_USERLANDPROXY=true DOCKER_HOST=unix:///go/src/github.com/docker/docker/bundles/1.13.0-dev/test-integration-cli/docker.sock DOCKER_REMAP_ROOT= DOCKER_REMOTE_DAEMON= DOCKERFILE=Dockerfile GOPATH=/go:/go/src/github.com/docker/docker/vendor GOTRACEBACK=all HOME=/go/src/github.com/docker/docker/bundles/1.13.0-dev/test-integration-cli/fake-HOME PATH=/go/src/github.com/docker/docker/bundles/1.13.0-dev/test-integration-cli/../binary-client:/go/src/github.com/docker/docker/bundles/1.13.0-dev/test-integration-cli/../binary-daemon:/go/src/github.com/docker/docker/bundles/1.13.0-dev/test-integration-cli/../dynbinary-client:/go/src/github.com/docker/docker/bundles/1.13.0-dev/test-integration-cli/../dynbinary-daemon:/go/bin:/usr/local/go/bin:/osxcross/target/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin TEMP= TEST_IMAGE_NAMESPACE= bundles/1.13.0-dev/test-integration-cli/test.main -check.f 'DockerSuite.TestHealth*' -check.v -check.timeout=5m -test.timeout=360m
INFO: Testing against a local daemon
PASS: docker_cli_health_test.go:53: DockerSuite.TestHealth	23.314s
OK: 1 passed
PASS
---> Making bundle: .integration-daemon-stop (in bundles/1.13.0-dev/test-integration-cli)
++++ cat bundles/1.13.0-dev/test-integration-cli/docker.pid
+++ kill 7045
```

I decided to keep digging a little more so I tried running `env TESTFLAGS='-check.f DockerSuite.TestHealth*' hack/make.sh` but it failed with:
```
---> Making bundle: dynbinary (in bundles/1.13.0-dev/dynbinary)
Building: bundles/1.13.0-dev/dynbinary-client/docker-1.13.0-dev
Created binary: bundles/1.13.0-dev/dynbinary-client/docker-1.13.0-dev
Building: bundles/1.13.0-dev/dynbinary-daemon/dockerd-1.13.0-dev
Created binary: bundles/1.13.0-dev/dynbinary-daemon/dockerd-1.13.0-dev
Building: bundles/1.13.0-dev/dynbinary-daemon/docker-proxy-1.13.0-dev
Created binary: bundles/1.13.0-dev/dynbinary-daemon/docker-proxy-1.13.0-dev

---> Making bundle: test-unit (in bundles/1.13.0-dev/test-unit)
Tue Oct 11 02:23:49 UTC 2016
can't load package: package github.com/docker/docker: no buildable Go source files in /go/src/github.com/docker/docker
```

Maybe this is expected as per the flag. I don't know what the flags does.

Finally, I ran `hack/make.sh ` again. And it failed. Here is a longer output:
```
goroutine 9071 [syscall, 4 minutes]:
syscall.Syscall6(0xf7, 0x1, 0x2af3, 0xc420226980, 0x1000004, 0x0, 0x0, 0xc4203f4000, 0xc42183ac60, 0x7f89253b64b0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
os.(*Process).blockUntilWaitable(0xc4204a4ff0, 0xc42048d600, 0x1187d00, 0x1)
	/usr/local/go/src/os/wait_waitid.go:28 +0xbc
os.(*Process).wait(0xc4204a4ff0, 0x10, 0x12b5ec8, 0xc4202f5760)
	/usr/local/go/src/os/exec_unix.go:22 +0xab
os.(*Process).Wait(0xc4204a4ff0, 0xc4204a4ff0, 0x0, 0x0)
	/usr/local/go/src/os/doc.go:49 +0x2b
os/exec.(*Cmd).Wait(0xc4202f5760, 0xc4202f5838, 0xc4206750b8)
	/usr/local/go/src/os/exec/exec.go:434 +0x6d
github.com/docker/docker/pkg/integration/cmd.WaitOnCmd(0x0, 0xc4217b5f40, 0x4)
	/go/src/github.com/docker/docker/pkg/integration/cmd/command.go:299 +0x53
github.com/docker/docker/pkg/integration/cmd.RunCmd(0xc4217b5ec0, 0x4, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/docker/pkg/integration/cmd/command.go:250 +0x76
github.com/docker/docker/pkg/integration/cmd.RunCommand(0xc420223ae0, 0x48, 0xc4206756b8, 0x3, 0x3, 0x1978740)
	/go/src/github.com/docker/docker/pkg/integration/cmd/command.go:255 +0x196
github.com/docker/docker/integration-cli.dockerCmd(0xc4200c0960, 0xc4206756b8, 0x3, 0x3, 0xc420026090, 0xc420675460, 0x1)
	/go/src/github.com/docker/docker/integration-cli/docker_utils.go:469 +0x96
github.com/docker/docker/integration-cli.(*DockerSuite).TestHealth(0x19c1070, 0xc4200c0960)
	/go/src/github.com/docker/docker/integration-cli/docker_cli_health_test.go:138 +0x14cd
reflect.Value.call(0x11cffa0, 0x19c1070, 0x84e13, 0x11d51ea, 0x4, 0xc420675f20, 0x1, 0x1, 0x19c3700, 0x11bbde0, ...)
	/usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x11cffa0, 0x19c1070, 0x84e13, 0xc420675f20, 0x1, 0x1, 0x0, 0xc4201deecf, 0x4)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/go-check/check.(*suiteRunner).forkTest.func1(0xc4200c0960)
	/go/src/github.com/docker/docker/vendor/src/github.com/go-check/check/check.go:816 +0x6b8
github.com/go-check/check.(*suiteRunner).forkCall.func1(0xc4203b8630, 0xc4200c0960, 0xc422e0ae60)
	/go/src/github.com/docker/docker/vendor/src/github.com/go-check/check/check.go:672 +0x7c
created by github.com/go-check/check.(*suiteRunner).forkCall
	/go/src/github.com/docker/docker/vendor/src/github.com/go-check/check/check.go:673 +0x251
---> Making bundle: .integration-daemon-stop (in bundles/1.13.0-dev/test-integration-cli)
+++++ cat bundles/1.13.0-dev/test-integration-cli/docker.pid
++++ kill 8148
/go/src/github.com/docker/docker/hack/make/.integration-daemon-stop: line 8: kill: (8148) - No such process
```

I'll try with beta27 tomorrow.

**Comment by crmejia** [comment]
### Summary 
Got beta27 and ran into trouble again(in a different test).

### Information
currently commit 8658748ef716e43a5f6d834825d818012ed6e2c4
Merge: aba3a99 c5393ee
```
Docker for Mac: version: 1.12.2-rc1-beta27 (179c18c)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/5288AEDC-85C2-42EA-A000-E4BDB6E31D21/20161013-120022.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
```

### $make shell

Installed docker beta27 had to restart docker 3 times(is the charm) doing the `host $ make shell` and once again got this issue:

```
Get:216 http://httpredir.debian.org/debian/ jessie/main python-mock all 1.0.1-3 [33.2 kB]
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/n/net-tools/net-tools_1.60-26+b1_amd64.deb  Error reading from server. Remote end closed connection [IP: 5.153.231.35 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

After this, the process went smoothly.
**Find the complete log attached as host.log **

### $hack/make.sh

The process broke here:
```
PASS: docker_cli_pull_test.go:41: DockerHubPullSuite.TestPullNonExistingImage	1.642s
PASS: docker_cli_pull_test.go:191: DockerHubPullSuite.TestPullScratchNotAllowed	0.100s
OOPS: 1313 passed, 50 skipped, 105 FAILED
--- FAIL: Test (7314.99s)
FAIL
---> Making bundle: .integration-daemon-stop (in bundles/1.13.0-dev/test-integration-cli)
```
 Also i kept getting errors such as:

 ```
 FAIL: docker_cli_network_unix_test.go:1086: DockerNetworkSuite.TestDockerNetworkMultipleNetworksUngracefulDaemonRestart

[dd8ae843999b8] waiting for daemon to start
[dd8ae843999b8] daemon started
docker_cli_network_unix_test.go:1092:
    connectContainerToNetworks(c, s.d, cName, nwList)
docker_cli_network_unix_test.go:1048:
    c.Assert(err, checker.IsNil, check.Commentf(out))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc4203e1e20), Stderr:[]uint8(nil)} ("exit status 125")
... /go/src/github.com/docker/docker/bundles/1.13.0-dev/binary-client/docker: Error response from daemon: error creating aufs mount to /go/src/github.com/docker/docker/bundles/1.13.0-dev/test-integration-cli/dd8ae843999b8/root/aufs/mnt/bfe60b17886a9aee1ce656b569babd24923b6d14f61fcebc2aa31ec2e6531362-init: function not implemented.
See '/go/src/github.com/docker/docker/bundles/1.13.0-dev/binary-client/docker run --help'.
```

but the process did not break. 

**Find the complete log attached as container.log **

@samoht Here's with beta 27. If there's anything else I can provide let me know.

[host.txt](https://github.com/docker/for-mac/files/527611/host.txt)
[container.txt](https://github.com/docker/for-mac/files/527612/container.txt)

**Comment by ijc25** [comment]
```
Get:216 http://httpredir.debian.org/debian/ jessie/main python-mock all 1.0.1-3 [33.2 kB]
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/n/net-tools/net-tools_1.60-26+b1_amd64.deb  Error reading from server. Remote end closed connection [IP: 5.153.231.35 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

This is a bug with the `httpredir.debian.org` service (which keeps putting the same bad mirror back in rotation, sigh) and not with Docker (for Mac or otherwise).

**Comment by dave-tucker** [comment]
@crmejia the issue with `httpredir` should have been fixed in https://github.com/docker/docker/pull/27620

I've tested this on `Beta 29.2` with the latest docker master (https://github.com/docker/docker/commit/8cced8702261224ffd726774812eb50e8a600e52 at the time of writing) and cannot reproduce.

If you're following the guide and you are on the `dry_run` branch you can update to the latest docker code with the following commands:

```
$ git fetch upstream master
$ git rebase FETCH_HEAD
```
Following that guide, I don't see the `integration-cli` being run, so not sure where that comes in to play in this. Perhaps the Makefile has changed since you filed this issue.

**Comment by ijc25** [comment]
This issue has been inactive for more than 14 days while marked as `status/0-more-info-needed`. It is being closed due to abandonment. Please feel free to re-open with more information about the problem. 

MORE_INFO_EXPIRY_TIMEOUT
