### ISSUE TITLE
dial unix Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused

### ISSUE THREAD

**Issue by eric-zhu** [docker/for-mac#818]
### Expected behavior

Use Docker normally: 'docker-compose up' to launch all containers(db, web).
Make code changes, web server restarts and reloads updated code.
### Actual behavior

Occasionally both my containers crashed and reported the following errors.

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.py", line 810, in __bootstrap_inner
  File "threading.py", line 763, in run
  File "compose/cli/log_printer.py", line 149, in tail_container_logs
  File "compose/cli/log_printer.py", line 179, in wait_on_exit
  File "compose/container.py", line 239, in wait
  File "site-packages/docker/utils/decorators.py", line 21, in wrapped
  File "site-packages/docker/api/container.py", line 441, in wait
  File "site-packages/docker/client.py", line 174, in _raise_for_status
APIError: 500 Server Error: Internal Server Error ("dial unix /Users/eric/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused")

Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.py", line 810, in __bootstrap_inner
  File "threading.py", line 763, in run
  File "compose/cli/log_printer.py", line 149, in tail_container_logs
  File "compose/cli/log_printer.py", line 179, in wait_on_exit
  File "compose/container.py", line 239, in wait
  File "site-packages/docker/utils/decorators.py", line 21, in wrapped
  File "site-packages/docker/api/container.py", line 441, in wait
  File "site-packages/docker/client.py", line 174, in _raise_for_status
APIError: 500 Server Error: Internal Server Error ("dial unix /Users/eric/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused")
```
### Information

Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/75393C3D-9C6E-4415-AABB-488A913DA357/20161018-154421.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
### Steps to reproduce the behavior
1. "docker-compose up" to start both containers.
2. Access the web server via browser on docker host.

**Comment by samoht** [comment]
There were a number of updates to the hypervisor transport system in the recently released Beta 27. If you are comfortable running a beta (we still do QA on it), you could give that a try and see if it stops the frequent crashing.

May be related to docker/hyperkit#50

**Comment by eric-zhu** [comment]
I tried Beta 28 and the issue was resolved. thanks a lot.
