### ISSUE TITLE
ERROR: for app  'ascii' codec can't decode byte 0xc5 in position 4: ordinal not in range(128)

### ISSUE THREAD

**Issue by bauerpl** [docker/for-mac#869]
### Expected behavior

`docker-compose up -d` creates containers.
### Actual behavior

I got:

```
ERROR: for app  'ascii' codec can't decode byte 0xc5 in position 4: ordinal not in range(128)

ERROR: for app53  'ascii' codec can't decode byte 0xc5 in position 4: ordinal not in range(128)
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 61, in main
  File "compose/cli/main.py", line 113, in perform_command
  File "compose/cli/main.py", line 835, in up
  File "compose/project.py", line 400, in up
  File "compose/parallel.py", line 64, in parallel_execute
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 4: ordinal not in range(128)
docker-compose returned -1
```
### Information

```
Output from Diagnose & Feedback:
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.12.1 (build: 16B2555)
logs: /tmp/02C2D2B2-7118-4A88-8D47-A2EAFBDBAAF2/20161028-205858.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

I'm using Docker for Mac (stable version):

`Docker version 1.12.1, build 6f9534c`
`docker-compose version 1.8.0, build f3628c7`

**Comment by dsheets** [comment]
Would it be possible for you to post a `docker-compose.yml` file that causes this error? It looks like a problem with character encoding in your compose configuration.

**Comment by ijc25** [comment]
@bauerpl FYI I've added the more-info tag in response to @dsheets question above. Issues with that tag are automatically closed 14 days after the tag was added.

**Comment by vovkins** [comment]
Noticed same behaviour on Linux (SUSE Linux Enterprise Server 12 (x86_64))

Here is `docker-compose up` command output with same error:
```
ERROR: for gen-ws  'ascii' codec can't decode byte 0xd0 in position 3: ordinal not in range(128)
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 61, in main
  File "compose/cli/main.py", line 113, in perform_command
  File "compose/cli/main.py", line 835, in up
  File "compose/project.py", line 400, in up
  File "compose/parallel.py", line 64, in parallel_execute
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 3: ordinal not in range(128)
docker-compose returned -1
```

In my case this problem is caused by non-ascii symbols in environment variables that are passed to containers at startup.

Here is the part of my `docker-compose.yml`
```
man-ws:
  build: ./man-ws
  expose:
   - "6003"
  ports:
   - "${IBREPORTING_MANWS_EXTERNAL_PORT}:6003"
  hostname: "man-ws"
  links:
   - gen-api
  environment:
   - IBREPORTING_LDAP_ATTR_BASE
```
When environment variable IBREPORTING_LDAP_ATTR_BASE contains non-ascii symbols (but utf-8) i got error mentioned above. As soon as i remove non-ascii symbols from environment variable IBREPORTING_LDAP_ATTR_BASE container starts normally.

Docker versions:
`Docker version 1.6.2, build 7c8fca2`
`docker-compose version 1.8.0, build f3628c7`

**Comment by rogaha** [comment]
@bauerpl if you are still experiencing this issue, please feel free to re-open it.
