### ISSUE TITLE
beta30: Bad response from Docker engine

### ISSUE THREAD

**Issue by riyazdf** [docker/for-mac#947]
I've noticed that recently my docker4mac has been failing on `docker-compose` and other `docker` commands with "`Bad response from Docker engine`.  I've tried to restart my docker app and the host itself but haven't had any luck 

DiagnosticID: `A2527B0A-43F6-4DC9-9AB1-DA74B0ED0879`

```
🐳 $ docker-compose up
ERROR: Bad response from Docker engine
```
```
🐳 $ docker volume ls
Error response from daemon: Bad response from Docker engine
```
```
🐳 $ docker run --rm -it alpine sh
docker: Error response from daemon: Bad response from Docker engine.
See 'docker run --help'.
```

**Comment by ijc25** [comment]
Hi @riyazdf. Your `/var/log/docker.log` contains a lot of Go panic spew from the engine, things like
```
time="2016-11-10T22:19:15.956485417Z" level=debug msg="Calling GET /v1.24/volumes" 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xc61aff]

goroutine 3196 [running]:
panic(0x1b5e4e0, 0xc8200100e0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/docker/docker/pkg/plugins.(*Client).callWithRetry(0x0, 0x1f8a770, 0x11, 0x7f947a6f2c38, 0xc821fa2150, 0xc81ff71001, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/pkg/plugins/client.go:115 +0xadf
github.com/docker/docker/pkg/plugins.(*Client).Call(0x0, 0x1f8a770, 0x11, 0x17fdbc0, 0x2c01af0, 0x1723ba0, 0xc8211de390, 0x0, 0x0)
        /go/src/github.com/docker/docker/pkg/plugins/client.go:77 +0x1f6
github.com/docker/docker/volume/drivers.(*volumeDriverProxy).List(0xc821110190, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/volume/drivers/proxy.go:174 +0x129
github.com/docker/docker/volume/drivers.(*volumeDriverAdapter).List(0xc821f0a380, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/volume/drivers/adapter.go:42 +0x60
github.com/docker/docker/volume/store.(*VolumeStore).list.func1(0xc8210a00c0, 0xc8204cc210, 0x7f94784ca460, 0xc821f0a380)
        /go/src/github.com/docker/docker/volume/store/store.go:179 +0x3c
created by github.com/docker/docker/volume/store.(*VolumeStore).list
        /go/src/github.com/docker/docker/volume/store/store.go:189 +0x233
```

or

```
time="2016-11-14T23:23:56.267440098Z" level=debug msg="Probing all drivers for volume with name: resources_notary_data" 
2016-11-14 23:23:56.280661 I | http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 1230 [running]:
net/http.(*conn).serve.func1(0xc821263880)
        /usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x1b5e4e0, 0xc8200100e0)
        /usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/docker/docker/pkg/plugins.(*Client).callWithRetry(0x0, 0x1f8a750, 0x10, 0x7fc4250d61f0, 0xc820578460, 0xc81ffb5d01, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/pkg/plugins/client.go:115 +0xadf
github.com/docker/docker/pkg/plugins.(*Client).Call(0x0, 0x1f8a750, 0x10, 0x1b07020, 0xc820946590, 0x1723ae0, 0xc820944640, 0x0, 0x0)
        /go/src/github.com/docker/docker/pkg/plugins/client.go:77 +0x1f6
github.com/docker/docker/volume/drivers.(*volumeDriverProxy).Get(0xc820946580, 0xc820b008d3, 0x15, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/volume/drivers/proxy.go:203 +0x14c
github.com/docker/docker/volume/drivers.(*volumeDriverAdapter).Get(0xc8209445e0, 0xc820b008d3, 0x15, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/volume/drivers/adapter.go:60 +0x61
github.com/docker/docker/volume/store.(*VolumeStore).getVolume(0xc820385c20, 0xc820b008d3, 0x15, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/volume/store/store.go:406 +0x744
github.com/docker/docker/volume/store.(*VolumeStore).Get(0xc820385c20, 0xc820b008d3, 0x15, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/volume/store/store.go:345 +0x108
github.com/docker/docker/daemon.(*Daemon).VolumeInspect(0xc82015c9c0, 0xc820b008d3, 0x15, 0x4, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/inspect.go:205 +0x58
github.com/docker/docker/api/server/router/volume.(*volumeRouter).getVolumeByName(0xc8209e00c0, 0x7fc424097680, 0xc820e5a960, 0x7fc4240c6408, 0xc820173ba0, 0xc82016cd20, 0xc820e5a5a0, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/server/router/volume/volume_routes.go:29 +0x113
github.com/docker/docker/api/server/router/volume.(*volumeRouter).(github.com/docker/docker/api/server/router/volume.getVolumeByName)-fm(0x7fc424097680, 0xc820e5a960, 0x7fc4240c6408, 0xc820173ba0, 0xc82016cd20, 0xc820e5a5a0, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/server/router/volume/volume.go:29 +0x74
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7fc424097680, 0xc820e5a960, 0x7fc4240c6408, 0xc820173ba0, 0xc82016cd20, 0xc820e5a5a0, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/server/middleware/version.go:56 +0x9aa
github.com/docker/docker/api/server/middleware.UserAgentMiddleware.WrapHandler.func1(0x7fc424097680, 0xc820e5a930, 0x7fc4240c6408, 0xc820173ba0, 0xc82016cd20, 0xc820e5a5a0, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/server/middleware/user_agent.go:45 +0x68e
github.com/docker/docker/api/server/middleware.DebugRequestMiddleware.func1(0x7fc42408b190, 0xc8200106c8, 0x7fc4240c6408, 0xc820173ba0, 0xc82016cd20, 0xc820e5a5a0, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/server/middleware/debug.go:22 +0xc77
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7fc4240c6408, 0xc820173ba0, 0xc82016cd20)
        /go/src/github.com/docker/docker/api/server/server.go:139 +0x138
net/http.HandlerFunc.ServeHTTP(0xc8205ac8e0, 0x7fc4240c6408, 0xc820173ba0, 0xc82016cd20)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc8204841e0, 0x7fc4240c6408, 0xc820173ba0, 0xc82016cd20)
        /go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc820b708f0, 0x7fc4240c6408, 0xc820173ba0, 0xc82016cd20)
        /go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
net/http.serverHandler.ServeHTTP(0xc820057a80, 0x7fc4240c6408, 0xc820173ba0, 0xc82016cd20)
        /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc821263880)
        /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2137 +0x44e
```

The first (shorter one above) seems to have happened occasionally since 2016-10-24T20:08:36.166163781Z but starting from
```
time="2016-11-14T23:23:56.267440098Z" level=debug msg="Probing all drivers for volume with name: resources_notary_data"
```
they seem to become more frequent. I don't see anything right before which is an obvious precursor. Given the name of the container it is looking for perhaps this might explain it for you?

Otherwise it looks to me as if your filesystem has become corrupted somehow. Did docker and/or your mac crash or exit unexpectedly at some point recently?

**Comment by riyazdf** [comment]
thanks for the help @ijc25 - unfortunately the container isn't doing anything so there must be a problem with my filesystem even though I'm not aware of any unexpected crashes.  I'll investigate further.

**Comment by riyazdf** [comment]
I couldn't figure it out so I went with a factory reset and everything seems to be fine now -- probably some corrupted volume state messing with the engine :/

thanks again @ijc25 for your help!
